### ISSUE TITLE
Cannot escape variable value with space

### ISSUE THREAD

**Issue by elektromodulator** [RicoSuter/NSwag#1318]
I try to pass the output directory as a variable to command line nswag tool via MsBuild.
nswag file:
```json
{
  "runtime": "WinX86",
  "defaultVariables": "OutDir=bin\\x86\\Debug",
  "swaggerGenerator": {
    "webApiToSwagger": {
      ...
      "assemblyPaths": [
        "$(OutDir)\\target.dll"
      ],
      "assemblyConfig": "",
      "referencePaths": []
      ...
    }
  }
  ...
````
MsBuild Script fragment:
```xml
<PostBuildEvent>$(NSwagExe_x86) run $(ProjectDir)MyProject.nswag /variables:OutDir=$(OutDir)</PostBuildEvent>
```
If the output directory has a space in it, this does not work (obviously), and invalid path io error is reported, because the path fragment after the first space is not picked up.

I tried to escape the variable like this:
```xml
<PostBuildEvent>$(NSwagExe_x86) run $(ProjectDir)MyProject.nswag "/variables:OutDir=$(OutDir)"</PostBuildEvent>
```
or like this:
```xml
<PostBuildEvent>$(NSwagExe_x86) run $(ProjectDir)MyProject.nswag /variables:OutDir="$(OutDir)"</PostBuildEvent>
```
but the end result is in both cases illegal characters in path exception, bacuse the quotes are included in the variable value.

>  System.ArgumentException: Illegal characters in path.
>     at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
>     at System.IO.Path.IsPathRooted(String path)
>     at NSwag.Commands.NSwagDocument.ConvertToAbsolutePath(String pathToConvert)
>     at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
>     at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
>     at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
>     at NSwag.Commands.NSwagDocumentBase.ConvertToAbsolutePaths()
>     at NSwag.Commands.NSwagDocumentBase.FromJson[TDocument](String filePath, String data)
>     at NSwag.Commands.NSwagDocumentBase.<>c__DisplayClass35_0`1.<<LoadAsync>b__0>d.MoveNext()
>  --- End of stack trace from previous location where exception was thrown ---
>     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>     at NSwag.Commands.NSwagDocument.<LoadWithTransformationsAsync>d__7.MoveNext()
>  --- End of stack trace from previous location where exception was thrown ---
>     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>     at NSwag.Commands.Document.ExecuteDocumentCommand.<ExecuteDocumentAsync>d__9.MoveNext()
>  --- End of stack trace from previous location where exception was thrown ---
>     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>     at NSwag.Commands.Document.ExecuteDocumentCommand.<RunAsync>d__8.MoveNext()
>  --- End of stack trace from previous location where exception was thrown ---
>     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>     at NConsole.CommandLineProcessor.<ProcessSingleAsync>d__12.MoveNext()
>  --- End of stack trace from previous location where exception was thrown ---
>     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>     at NConsole.CommandLineProcessor.<ProcessAsync>d__11.MoveNext()
>  --- End of stack trace from previous location where exception was thrown ---
>     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>     at NConsole.CommandLineProcessor.Process(String[] args, Object input)
>     at NSwag.Commands.NSwagCommandProcessor.Process(String[] args)

Is there a way to escape spaces in variables? Or is this not supported?

**Comment by elektromodulator** [comment]
As a workaround I can use the TargetPath as an input, which works like this:
nswag file:
```json
{
  "runtime": "WinX86",
  "defaultVariables": "TargetPath=bin\\x86\\Debug\\target.dll",
  "swaggerGenerator": {
    "webApiToSwagger": {
      ...
      "assemblyPaths": [
        "$(TargetPath)"
      ],
      "assemblyConfig": "",
      "referencePaths": []
      ...
    }
  }
  ...
```
MsBuild Script fragment:
```xml
<PostBuildEvent>$(NSwagExe_x86) run $(ProjectDir)MyProject.nswag /variables:OutDir="$(OutDir)"</PostBuildEvent>
```
Since this is a full path, this does not result in an invalid path exception, because the quotes are around the full path.
This is inconvenient for my use case, but I can live with it for the moment. It would still be really nice if I could specify a variable with space in it without quotes around it.

**Comment by RSuter** [comment]
See https://github.com/RSuter/NSwag/issues/1298

**Comment by RSuter** [comment]
I think this is currently not supported... see referenced issue

**Comment by dannymurphygfk** [comment]
Any update on this ? 
We too are hitting this issue due to a space in the project path.

Is it scheduled to be fixed ? or is the issue with the microsoft.extensions.apidescription.design package ?

**Comment by RSuter** [comment]
This has to be fixed in nswag, see linked issue above with link to source code

**Comment by StingyJack** [comment]
@dannymurphygfk  - a bit late but [this ](https://github.com/RicoSuter/NSwag/issues/1298#issuecomment-846565072)may be useful to you.
