### ISSUE TITLE
aspnetcore2swagger not allowing new Startup parameters

### ISSUE THREAD

**Issue by onelioubov** [RicoSuter/NSwag#2043]
Hi there! I'm building out a .NET Core 2.2 API and am attempting to use NSwagStudio / aspnetcore2swagger and the .dll to generate the client for it; however, it gives me this error when I try to use DI to add another parameter into Startup (besides IConfiguration):

> 

> System.InvalidOperationException: Unable to resolve service for type 'Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration' while attempting to activate 'TestWebApplication1.Startup'.
> 
> Runtime: NetCore22
>    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
>    at Microsoft.AspNetCore.Hosting.Internal.StartupLoader.LoadMethods(IServiceProvider hostingServiceProvider, Type startupType, String environmentName)
>    at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.<>c__DisplayClass1_0.<UseStartup>b__1(IServiceProvider sp)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureStartup()
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
>    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
>    at NSwag.Commands.SwaggerGeneration.SwaggerGeneratorCommandBase`1.CreateWebHostAsync(AssemblyLoader assemblyLoader) in C:\projects\nswag\src\NSwag.Commands\Commands\SwaggerGeneration\SwaggerGeneratorCommandBase.cs:line 280
>    at NSwag.Commands.SwaggerGeneration.AspNetCore.AspNetCoreToSwaggerCommand.RunIsolatedAsync(AssemblyLoader assemblyLoader) in C:\projects\nswag\src\NSwag.Commands\Commands\SwaggerGeneration\AspNetCore\AspNetCoreToSwaggerCommand.cs:line 289
>    at NSwag.Commands.IsolatedCommandBase`1.IsolatedCommandAssemblyLoader`1.Run(String commandType, String commandData, String[] assemblyPaths, String[] referencePaths) in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedCommandBase.cs:line 70
>    at NSwag.Commands.IsolatedCommandBase`1.<>c__DisplayClass17_0.<RunIsolatedAsync>b__0() in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedCommandBase.cs:line 60
>    at System.Threading.Tasks.Task`1.InnerInvoke()
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
> --- End of stack trace from previous location where exception was thrown ---
>    at NSwag.Commands.IsolatedCommandBase`1.RunIsolatedAsync(String configurationFile)
>    at NSwag.Commands.IsolatedSwaggerOutputCommandBase`1.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedSwaggerOutputCommandBase.cs:line 47
>    at NSwag.Commands.SwaggerGeneration.AspNetCore.AspNetCoreToSwaggerCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\SwaggerGeneration\AspNetCore\AspNetCoreToSwaggerCommand.cs:line 88
>    at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocumentBase.cs:line 268
>    at NSwag.Commands.NSwagDocument.ExecuteAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocument.cs:line 81
>    at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 77
>    at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 31
>    at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
>    at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
>    at NConsole.CommandLineProcessor.Process(String[] args, Object input)
>    at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 54

In this case, 'Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration' is what I'm trying to put into startup. I also use publishwithpreservercopy and use nuget cache.

I created a simple project here to show you what my setup looks like in Program.cs and Startup.cs: 

[https://github.com/onelioubov/testWebApplication1](https://github.com/onelioubov/testWebApplication1)

**Comment by onelioubov** [comment]
Also noting that this works fine if I pull '.UseConfiguration(_configuration)' outside of CreateWebHostBuilder and add it on after CreateWebHostBuilder gets called. This is what I'm currently using as a temporary workaround.

**Comment by onelioubov** [comment]
Between then and now, a newer version came out that resolved my issue. Marking as closed.
