### ISSUE TITLE
Swagger Generator (msbuild) fails on full .NET Framework with Microsoft.AspNetCore.Mvc 2.2

### ISSUE THREAD

**Issue by akamyshanov** [RicoSuter/NSwag#2091]
The failing combination is exactly `net462` + `Microsoft.AspNetCore.Mvc 2.2.0`. Works fine with `netcoreapp2.2` + `Microsoft.AspNetCore.Mvc 2.2.0` and `net462` + `Microsoft.AspNetCore.Mvc 2.1.3`.

[Repro](https://github.com/akamyshanov/nswag-issue-mvc22) & [Build](https://ci.appveyor.com/project/akamyshanov/nswag-issue-mvc22)

Installed packages:

* Microsoft.AspNetCore.Mvc 2.2.0
* NSwag.AspNetCore 12.1.0
* NSwag.MSBuild 12.1.0

Invoking after build target

```
$(NSwagExe) aspnetcore2swagger "/assembly:$(TargetPath)" "/output:$(OutputPath)swagger.json"
```

The command fails with the following exception:

```
NSwag command line tool for .NET 4.6.1+ WinX64, toolchain v12.1.0.0 (NJsonSchema v9.13.28.0 (Newtonsoft.Json v11.0.0.0))
  Visit http://NSwag.org for more information.
  NSwag bin directory: C:\Users\appveyor\.nuget\packages\nswag.msbuild\12.1.0\tools\Win
  System.InvalidOperationException: The ConfigureServices method must either be parameterless or take only one parameter of type IServiceCollection.
  
  Server stack trace: 
     at Microsoft.AspNetCore.Hosting.Internal.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
     at Microsoft.AspNetCore.Hosting.Internal.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services)
     at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
     at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
     at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
     at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
     at NSwag.Commands.SwaggerGeneration.SwaggerGeneratorCommandBase`1.<CreateWebHostAsync>d__110.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at NSwag.Commands.SwaggerGeneration.AspNetCore.AspNetCoreToSwaggerCommand.<RunIsolatedAsync>d__44.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at NSwag.Commands.IsolatedCommandBase`1.IsolatedCommandAssemblyLoader`1.Run(String commandType, String commandData, String[] assemblyPaths, String[] referencePaths)
     at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
     at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
  
  Exception rethrown at [0]: 
     at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
     at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
     at NSwag.Commands.IsolatedCommandBase`1.IsolatedCommandAssemblyLoader`1.Run(String commandType, String commandData, String[] assemblyPaths, String[] referencePaths)
     at NSwag.Commands.IsolatedCommandBase`1.<>c__DisplayClass17_0.<RunIsolatedAsync>b__0()
     at System.Threading.Tasks.Task`1.InnerInvoke()
     at System.Threading.Tasks.Task.Execute()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at NSwag.Commands.IsolatedCommandBase`1.<RunIsolatedAsync>d__17.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at NSwag.Commands.IsolatedSwaggerOutputCommandBase`1.<RunAsync>d__9.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at NSwag.Commands.SwaggerGeneration.AspNetCore.AspNetCoreToSwaggerCommand.<RunAsync>d__39.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at NConsole.CommandLineProcessor.<ProcessSingleAsync>d__12.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at NConsole.CommandLineProcessor.<ProcessAsync>d__11.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at NConsole.CommandLineProcessor.Process(String[] args, Object input)
     at NSwag.Commands.NSwagCommandProcessor.Process(String[] args)
C:\projects\nswag-issue-mvc22\net462-mvc21\nswag.targets(7,9): error MSB3073: The command ""C:\Users\appveyor\.nuget\packages\nswag.msbuild\12.1.0\build\../tools/Win/NSwag.exe" aspnetcore2swagger "/assembly:C:\projects\nswag-issue-mvc22\net462-mvc22\bin\Debug\net462\net462-mvc22.dll" "/output:bin\Debug\net462\swagger.json"" exited with code -1. [C:\projects\nswag-issue-mvc22\net462-mvc22\net462-mvc22.csproj]
```

I assume that this is related to assembly loading once again, probably the assembly that contains the `IServiceCollection` interface got loaded into a different load context or something like that. I did try to dig around NSwag sources but unfortunately failed to find a fix.

**Comment by RicoSuter** [comment]
The full .net binary is currently built against aspnetcore 2.1 - in the ideal world we’d have a binary per aspnetcore version and target framework - but that is an explosion of combinations and not really maintainable. Maybe we should just built the netfx version against 2.2 but that might break some users...

https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Console/NSwag.Console.csproj#L41

**Comment by akamyshanov** [comment]
I will give it a try soon and update the dependency to 2.2 but I don't think that's the issue, these packages are backwards compatible and the message suggests that the library sees a totally different interface in the parameters.

**Comment by akamyshanov** [comment]
But it seems you are right. It does work correctly with 2.2 packages when updated. On the other hand, now it fails for 2.1 apps. Do you have any suggestions on how this can be solved? Or the only option is to have separate binaries?

I was able to successfully generate swagger.json for a net462 app with 2.2 AspNetCore dependencies with the help of `NSwag.AspNetCore`:

```
var host = new WebHostBuilder().UseStartup<Startup>().Build();
var provider = host.Services.GetRequiredService<ISwaggerDocumentProvider>();
var registrations = host.Services.GetServices<SwaggerDocumentRegistration>();
var reg = host.Services.GetService<SwaggerDocumentRegistration>();
var schema = provider.GenerateAsync(reg.DocumentName).Result;
var json = schema.ToJson();
File.WriteAllText("swagger.json", json);
```

Why isn't the same approach working with CLI?

**Comment by RicoSuter** [comment]
Have you tried with /project instead of /assembly?

**Comment by akamyshanov** [comment]
Indeed, works with `/project` (and I now understand backwards compatibility of AspNetCore packages doesn't matter) but it's much less convenient to use with `NSwag.MSBuild`:

* You need a dummy project to trigger the command
* `Main(...)` and `BuildWebHost(...)` methods must exist which in my case requires another dummy project

**Comment by RicoSuter** [comment]
> why not find the startup type and build the host as it's built with /assembly?)

I think that is what we are doing but there are a lot of issues loading assemblies, using app domains, load contexts, etc. ... all this is really a pain in the *** - mainly because of incompatibilities, assembly lookups etc...

**Comment by akamyshanov** [comment]
I know your pain :) Struggled with domains and assembly lookups as well.
Anyway, what would be the process to support AspNetCore 2.2 via `/assembly`? Do you think the only option is to have a separate binary?

**Comment by RicoSuter** [comment]
I think that's not really feasible... why can't you just use /project? Or we just upgrade the netfx version to 2.2 - same as Microsoft who also only supports the latest and greatest version :-)

**Comment by akamyshanov** [comment]
I'd be happy to just upgrade to 2.2 :)
I think it's a good idea then to release v13 and add a compatibility table in the readme. Do you want a pull request for this?

**Comment by RicoSuter** [comment]
Created a PR to fix this: https://github.com/RicoSuter/NSwag/pull/2096

**Comment by akamyshanov** [comment]
@RicoSuter any timeframe when do you think this will be released?

**Comment by RicoSuter** [comment]
I’m a little hesitant as this might break many users. How hard is it to upgrade from 2.1 to 2.2?

**Comment by akamyshanov** [comment]
Just upgrading the package versions for my projects but there may be different situations. It’s a minor upgrade, doesn’t seem hard.
https://docs.microsoft.com/en-us/aspnet/core/migration/21-to-22?view=aspnetcore-2.2&tabs=visual-studio

**Comment by RicoSuter** [comment]
Ok i think its acceptable then, probably there are not many using aspnetcore and full netfx

**Comment by quails4Eva** [comment]
I've been getting this exception with .Net 4.7.2 and MVC 2.1.3, though I haven't tried with such a small repro yet so it's possible it could be caused by some other factor.
