### ISSUE TITLE
Nswag MS-Build error after sdk update to 2.2.202

### ISSUE THREAD

**Issue by christophezei** [RicoSuter/NSwag#2094]
Hello i am facing a problem after upgrading my dotnetcore sdk from 2.1 to 2.2 with Nswag build using NSwag.Msbuild the build still working fine with older sdk (2.1).
now i am having this error with the new sdk (2.2.202):

**System.MissingMethodException: Method not found: 'Microsoft.Extensions.DependencyInjection.IMvcCoreBuilder Microsoft.Extensions.DependencyInjection.MvcApiExplorerMvcCoreBuilderExtensions.AddApiExplorer(Microsoft.Extensions.DependencyInjection.IMvcCoreBuilder)'.
    at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services)
    at Api.Boss.Startup.ConfigureServices(IServiceCollection services) in C:\Users\Christophe\Desktop\solutions\OptikMW\OptikMW\src\main\Api.BOSS\Startup.cs:line 34
	End of stack trace from previous location where exception was thrown ---
    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
    at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
    at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
    at NSwag.Commands.SwaggerGeneration.SwaggerGeneratorCommandBase`1.CreateWebHostAsync(AssemblyLoader assemblyLoader) in C:\projects\nswag\src\NSwag.Commands\Commands\SwaggerGeneration\SwaggerGeneratorCommandBase.cs:line 288
    at NSwag.Commands.SwaggerGeneration.AspNetCore.AspNetCoreToSwaggerCommand.RunIsolatedAsync(AssemblyLoader assemblyLoader) in C:\projects\nswag\src\NSwag.Commands\Commands\SwaggerGeneration\AspNetCore\AspNetCoreToSwaggerCommand.cs:line 289
    at NSwag.Commands.IsolatedCommandBase`1.IsolatedCommandAssemblyLoader`1.Run(String commandType, String commandData, String[] assemblyPaths, String[] referencePaths) in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedCommandBase.cs:line 70
    at NSwag.Commands.IsolatedCommandBase`1.<>c__DisplayClass17_0.<RunIsolatedAsync>b__0() in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedCommandBase.cs:line 60
    at System.Threading.Tasks.Task`1.InnerInvoke()
    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   End of stack trace from previous location where exception was thrown ---
    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
  End of stack trace from previous location where exception was thrown ---
    at NSwag.Commands.IsolatedCommandBase`1.RunIsolatedAsync(String configurationFile)
    at NSwag.Commands.IsolatedSwaggerOutputCommandBase`1.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedSwaggerOutputCommandBase.cs:line 47
    at NSwag.Commands.SwaggerGeneration.AspNetCore.AspNetCoreToSwaggerCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\SwaggerGeneration\AspNetCore\AspNetCoreToSwaggerCommand.cs:line 88
    at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocumentBase.cs:line 268
    at NSwag.Commands.NSwagDocument.ExecuteAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocument.cs:line 81
    at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 77
    at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 31
    at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
    at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
    at NConsole.CommandLineProcessor.Process(String[] args, Object input)
    at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 54
 C:\Users\Christophe\Desktop\solutions\OptikMW\OptikMW\src\main\Api.BOSS\Api.BOSS.csproj(58,5): error MSB3073: The command "dotnet "C:\Users\Christophe\.nuget\packages\nswag.msbuild\12.1.0\build\../tools/NetCore22/dotnet-nswag.dll" run api.boss.nswag /variables:Configuration=Debug,ProjectOutputPath=bin\Debug\netcoreapp2.2\" exited with code -1.
 Done building project "Api.BOSS.csproj" -- FAILED.**

ps:
-dotnetcore sdk version 2.2.202
-NSwag.AspNetCore version 12.1.0
-NSwag.MSBuild  version 12.1.0
-This is the code i am using to use nswag.msbuild: 

```
 <Target Name="NSwag" AfterTargets="Build">
    <Copy SourceFiles="@(ReferencePath)" DestinationFolder="$(OutDir)References" />
    <Exec Command="$(NSwagExe_Core22) run api.boss.nswag /variables:Configuration=$(Configuration),ProjectOutputPath=$(OutputPath)" />
    <RemoveDir Directories="$(OutDir)References" />
  </Target>
```

**Comment by migzai** [comment]
Hi,

I confirm that I am facing the same issue.  It only happens when generating the C# client, and not the TypeScript one.

Could you please give that a high priority.

Thanks

**Comment by christophezei** [comment]
https://github.com/christophezei/HelloNswag/tree/master , this a sample project if you need any other information let me know .

**Comment by RicoSuter** [comment]
Created a PR to fix this: https://github.com/RicoSuter/NSwag/pull/2096

**Comment by christophezei** [comment]
@RicoSuter
 Hello same problem still occurring even after upgrading the following:
-NSwag.AspNetCore version 12.1.0 to 12.3.1
-NSwag.MSBuild version 12.1.0 to 12.3.1

Nb: problem with sdk 2.2 , however these new versions are working whith sdk 2.1.

**Comment by RicoSuter** [comment]
Try loading the csproj (/project) instead of assemblies (/assembly)
