### ISSUE TITLE
SwaggerTag throws error in MSBUILD

### ISSUE THREAD

**Issue by RuiCostafrg** [RicoSuter/NSwag#2120]
When i try to execute the MsBuild command:

`  <Target Name="NSwag" BeforeTargets="PrepareForBuild" Condition="'$(GenerateCode)'=='True' ">
    <Exec Command="$(NSwagExe_Core22) run nswag.json /variables:Configuration=$(Configuration)" />
  </Target>`

**I am getting:** 

`1>Executing file 'nswag.json'...
1>Launcher directory: C:\Users\USER-Admin\.nuget\packages\nswag.msbuild\12.1.0\tools\NetCore22
1>`**`System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'Swashbuckle.AspNetCore.Annotations.SwaggerTagAttribute' does not contain a definition for 'Name'`**`
1>   at CallSite.Target(Closure , CallSite , Object )
1>   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
1>   at NSwag.SwaggerGeneration.Processors.DocumentTagsProcessor.AddTagFromSwaggerTagAttribute(SwaggerDocument document, Object tagAttribute)
1>   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
1>   at NSwag.SwaggerGeneration.Processors.DocumentTagsProcessor.ProcessSwaggerTagAttributes(SwaggerDocument document, Type controllerType)
1>   at NSwag.SwaggerGeneration.Processors.DocumentTagsProcessor.ProcessAsync(DocumentProcessorContext context)
1>   at NSwag.SwaggerGeneration.AspNetCore.AspNetCoreToSwaggerGenerator.GenerateAsync(ApiDescriptionGroupCollection apiDescriptionGroups)
1>   at NSwag.Commands.SwaggerGeneration.AspNetCore.AspNetCoreToSwaggerCommand.GenerateDocumentWithApiDescriptionAsync(AssemblyLoader assemblyLoader, IWebHost host, String currentWorkingDirectory) in C:\projects\nswag\src\NSwag.Commands\Commands\SwaggerGeneration\AspNetCore\AspNetCoreToSwaggerCommand.cs:line 279
1>   at NSwag.Commands.SwaggerGeneration.AspNetCore.AspNetCoreToSwaggerCommand.GenerateDocumentAsync(AssemblyLoader assemblyLoader, IWebHost host, String currentWorkingDirectory) in C:\projects\nswag\src\NSwag.Commands\Commands\SwaggerGeneration\AspNetCore\AspNetCoreToSwaggerCommand.cs:line 259
1>   at NSwag.Commands.SwaggerGeneration.AspNetCore.AspNetCoreToSwaggerGeneratorCommandEntryPoint.<>c__DisplayClass0_0.<<Process>b__0>d.MoveNext() in C:\projects\nswag\src\NSwag.Commands\Commands\SwaggerGeneration\AspNetCore\AspNetCoreToSwaggerGeneratorCommandEntryPoint.cs:line 30
`**`1>--- End of stack trace from previous location where exception was thrown ---`**`
1>   at NSwag.Commands.SwaggerGeneration.AspNetCore.AspNetCoreToSwaggerGeneratorCommandEntryPoint.Process(String commandContent, String outputFile, String applicationName) in C:\projects\nswag\src\NSwag.Commands\Commands\SwaggerGeneration\AspNetCore\AspNetCoreToSwaggerGeneratorCommandEntryPoint.cs:line 29
`**`1>   --- End of inner exception stack trace ---`**`
1>   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
1>   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
1>   at NSwag.AspNetCore.Launcher.Program.Main(String[] args) in C:\projects\nswag\src\NSwag.AspNetCore.Launcher\Program.cs:line 161
**1>System.InvalidOperationException: Swagger generation failed with non-zero exit code '1'.**
1>   at NSwag.Commands.SwaggerGeneration.AspNetCore.AspNetCoreToSwaggerCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\SwaggerGeneration\AspNetCore\AspNetCoreToSwaggerCommand.cs:line 206
1>   at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocumentBase.cs:line 268
1>   at NSwag.Commands.NSwagDocument.ExecuteAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocument.cs:line 81
1>   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 77
1>   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 31
1>   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
1>   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
1>   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
1>   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 54
`**`1>C:\Anotations\Client\Client.csproj(17,5): error MSB3073: The command "dotnet "C:\Users\USER-Admin\.nuget\packages\nswag.msbuild\12.1.0\build\../tools/NetCore22/dotnet-nswag.dll" run nswag.json /variables:Configuration=Debug" exited with code -1.`**`
1>Done building project "Client.csproj" -- FAILED.`

Its only happens when i have a Swaggertag defined in the controller. ex;

`[SwaggerTag("Advanced", "Advanced usage notes")]`

I am using the Swashbuckle.AspNetCore.Annotations 5.0.0-rc2 nuget package.

If we compare [NSwag Repo](https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Core/SwaggerTag.cs) and [Swashbuckle Repo](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.Annotations/SwaggerTagAttribute.cs) we can see that there isn't a Name attribute in the last one.

**Comment by RicoSuter** [comment]
You cannot generate a spec with the nswag cli if the project uses swashbuckle and not nswag.aspnetcore

**Comment by RuiCostafrg** [comment]
But it seems to works with the swashbuckle 
![as you can see here](https://user-images.githubusercontent.com/35194998/56366841-ed6c0900-61eb-11e9-8bd4-706590154fe6.png). 

I only get error when using the swagger tag:

![image](https://user-images.githubusercontent.com/35194998/56367015-40de5700-61ec-11e9-9574-9587fca08a6c.png)

Am i doing something wrong?
Thank you for patience.

**Comment by RicoSuter** [comment]
can you post the nswag.json content?

**Comment by RuiCostafrg** [comment]
```json
{

  "runtime": "NetCore22",

  "defaultVariables": null,

  "swaggerGenerator": {

    "aspNetCoreToSwagger": {

      "project": "../Anno/Anno.csproj",

      "msBuildProjectExtensionsPath": null,

      "configuration": null,

      "runtime": "",

      "targetFramework": "netcoreapp2.2",

      "noBuild": false,

      "verbose": true,

      "workingDirectory": null,

      "requireParametersWithoutDefault": true,

      "apiGroupNames": null,

      "defaultPropertyNameHandling": "CamelCase",

      "defaultReferenceTypeNullHandling": "Null",

      "defaultEnumHandling": "Integer",

      "flattenInheritanceHierarchy": false,

      "generateKnownTypes": true,

      "generateXmlObjects": false,

      "generateAbstractProperties": true,

      "ignoreObsoleteProperties": false,

      "allowReferencesWithProperties": false,

      "excludedTypeNames": [],

      "serviceHost": null,

      "serviceBasePath": null,

      "serviceSchemes": [],

      "infoTitle": "NswagTestClient",

      "infoDescription": null,

      "infoVersion": "1.0.0",

      "documentTemplate": null,

      "documentProcessorTypes": [],

      "operationProcessorTypes": [],

      "typeNameGeneratorType": null,

      "schemaNameGeneratorType": null,

      "contractResolverType": null,

      "serializerSettingsType": null,

      "useDocumentProvider": false,

      "documentName": "v1",

      "aspNetCoreEnvironment": null,

      "createWebHostBuilderMethod": null,

      "startupType": null,

      "allowNullableBodyParameters": true,

      "output": null,

      "outputType": "OpenApi3",

      "assemblyPaths": [],

      "assemblyConfig": null,

      "referencePaths": [],

      "useNuGetCache": false

    }

  },

  "codeGenerators": {

    "swaggerToCSharpClient": {

      "clientBaseClass": null,

      "configurationClass": null,

      "generateClientClasses": true,

      "generateClientInterfaces": true,

      "generateDtoTypes": true,

      "injectHttpClient": true,

      "disposeHttpClient": true,

      "protectedMethods": [],

      "generateExceptionClasses": true,

      "exceptionClass": "SwaggerException",

      "wrapDtoExceptions": true,

      "useHttpClientCreationMethod": false,

      "httpClientType": "System.Net.Http.HttpClient",

      "useHttpRequestMessageCreationMethod": false,

      "useBaseUrl": true,

      "generateBaseUrlProperty": true,

      "generateSyncMethods": false,

      "exposeJsonSerializerSettings": false,

      "clientClassAccessModifier": "internal",

      "typeAccessModifier": "public",

      "generateContractsOutput": true,

      "contractsNamespace": "Example.Api.Client.Contracts",

      "contractsOutputFilePath": "Contracts.cs",

      "parameterDateTimeFormat": "s",

      "generateUpdateJsonSerializerSettingsMethod": true,

      "serializeTypeInformation": false,

      "queryNullValue": "",

      "className": "{controller}Client",

      "operationGenerationMode": "MultipleClientsFromOperationId",

      "additionalNamespaceUsages": [],

      "additionalContractNamespaceUsages": [],

      "generateOptionalParameters": false,

      "generateJsonMethods": true,

      "enforceFlagEnums": false,

      "parameterArrayType": "System.Collections.Generic.IEnumerable",

      "parameterDictionaryType": "System.Collections.Generic.IDictionary",

      "responseArrayType": "System.Collections.ObjectModel.ObservableCollection",

      "responseDictionaryType": "System.Collections.Generic.Dictionary",

      "wrapResponses": false,

      "wrapResponseMethods": [],

      "generateResponseClasses": true,

      "responseClass": "ExampleResponse",

      "namespace": "NswagTest.NswagTestClient",

      "requiredPropertiesMustBeDefined": true,

      "dateType": "System.DateTime",

      "jsonConverters": null,

      "dateTimeType": "System.DateTime",

      "timeType": "System.TimeSpan",

      "timeSpanType": "System.TimeSpan",

      "arrayType": "System.Collections.ObjectModel.ObservableCollection",

      "arrayInstanceType": "System.Collections.ObjectModel.Collection",

      "dictionaryType": "System.Collections.Generic.Dictionary",

      "dictionaryInstanceType": "System.Collections.Generic.Dictionary",

      "arrayBaseType": "System.Collections.ObjectModel.ObservableCollection",

      "dictionaryBaseType": "System.Collections.Generic.Dictionary",

      "classStyle": "Inpc",

      "generateDefaultValues": true,

      "generateDataAnnotations": false,

      "excludedTypeNames": [],

      "handleReferences": false,

      "generateImmutableArrayProperties": false,

      "generateImmutableDictionaryProperties": false,

      "jsonSerializerSettingsTransformationMethod": null,

      "inlineNamedDictionaries": false,

      "inlineNamedTuples": true,

      "templateDirectory": null,

      "typeNameGeneratorType": null,

      "propertyNameGeneratorType": null,

      "enumNameGeneratorType": null,

      "serviceHost": null,

      "serviceSchemes": null,

      "output": "Client.cs"

    }

  }

}
```

**Comment by RicoSuter** [comment]
The problem is that the aspNetCoreToSwagger requires you to use nswag in the web project (not swashbuckle). If you want to use swashbuckle to generate the spec then you need to generate the spec with the swashbuckle cli and load the spec file in the nswag config/cli
