### ISSUE TITLE
MissingMethodException on ASP.NET Core with .NET Framework

### ISSUE THREAD

**Issue by Gabriel-Espinoza** [RicoSuter/NSwag#2163]
NSwag version: 12.2.5
ASP.NET Core with .NET Framework 4.6.1
It works on ASP.NET Core with Core 2.2

Steps to reproduce: 

1. Open Visual Studio 2019
2. Create a new ASP.NET Core Web Application
3. Select .NET Framework
4. ConfigureServices in Startup with: `services.AddSwaggerDocument();`
5. Configure in Startup with `app.UseSwagger();            app.UseSwaggerUi3();`
6. Run the application

When I go to /swagger/index.html, it shows a blank screen, when I open dev-tools I can see the resources trying to be load, but all of them inform 500 error, when I double click any of them, it shows the ASP.NET Core Exception Page with the following stacktrace:

System.MissingMethodException: Method not found: 'Void Microsoft.Net.Http.Headers.EntityTagHeaderValue..ctor(System.String)'.
   at Microsoft.AspNetCore.StaticFiles.StaticFileContext.LookupFileInfo()
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.DefaultFilesMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.SwaggerUiIndexMiddleware`1.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.AspNetCore.Middlewares.RedirectToIndexMiddleware.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.AspNetCore.Middlewares.SwaggerDocumentMiddleware.<Invoke>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()

![image](https://user-images.githubusercontent.com/2473212/57565023-cbe1e580-7383-11e9-8819-1f2bd1d2680d.png)

**Comment by RicoSuter** [comment]
Can you retry with v12.3.1?

**Comment by Gabriel-Espinoza** [comment]
I haven't been able to test in yet, I will have some time this weekend, please wait a little longer for my reply.

**Comment by hoangnam123** [comment]
I tried to use the latest v12.3.1 with the same issue. I've noticed that NSwag.AspnetCore uses the Microsoft.AspNetCore.StaticFiles  v1.0.2. However, our project is AspnetCore 2.2 so all the dependencies are also upgraded to 2.2 which including the StaticFiles lib. 

I guess the diff in versions of the StaticFiles lib might cause incompatible issue since it's calling the old constructor which might get removed in v2.2 version.

**Comment by cruikshj** [comment]
FWIW I am having the same issue with the following versions:
NSwag.AspNetCore 13.0.4
.NET Framework 4.7.2

I was able to resolve by directly referencing the latest Microsoft.AspNetCore.StaticFiles package

```
<PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.2.0" />
<PackageReference Include="NSwag.AspNetCore" Version="13.0.4" />
```

**Comment by RicoSuter** [comment]
@hoangnam123 can you try cruikshj's solution? Is this working for you? Maybe we need to add StaticFiles as a direct dependency to NSwag.AspNetCore...

**Comment by stijnherreman** [comment]
Just ran into this when cleaning up dependencies in a project.

@hoangnam123 is right. `NSwag.AspNetCore` depends on these packages:
* Microsoft.AspNetCore.Mvc.Core (>= 1.0.3)
* Microsoft.AspNetCore.Mvc.Formatters.Json (>= 1.0.3)
* Microsoft.AspNetCore.StaticFiles (>= 1.0.2)

When the consuming project references a newer version of `Microsoft.AspNetCore.Mvc.Core`, the dependencies of NSwag are also upgraded, causing a version mismatch of `Microsoft.AspNetCore.StaticFiles`.
![image](https://user-images.githubusercontent.com/1618054/75872420-66794c80-5e0e-11ea-8a43-400f943fa5d6.png)

After depending on a new version of `Microsoft.AspNetCore.StaticFiles` in the consuming project:
![image](https://user-images.githubusercontent.com/1618054/75872442-74c76880-5e0e-11ea-9b4f-c991548c323b.png)

Digging deeper, we can see that `Microsoft.AspNetCore.StaticFiles` ends up consuming a version of `Microsoft.Net.Http.Headers` that it is not compatible with.
![image](https://user-images.githubusercontent.com/1618054/75872660-dc7db380-5e0e-11ea-8c74-c7b68c775395.png)

So this seems to be a defect in the Microsoft packages, in that they do not specify an upper version limit. Microsoft could have, for example, published a new 1.x version that fixes this.

I'm not sure if `NSwag.AspNetCore` can be fixed.

**Comment by RicoSuter** [comment]
/cc @pranavkm is it possible that MS is fixing this?

We try to keep this version as low as possible for max compatibility... if we upgrade this then people are forced upgrade. If it’s as is you can manually reference a higher version and it should work.

**Comment by pranavkm** [comment]
1.0 and 1.1 are out of support - https://dotnet.microsoft.com/platform/support/policy/dotnet-core. Changing them at this point is incredibly unlikely. 

In general, we'd like for the ecosystem of libraries to also rev with ASP.NET Core's major releases. Projects targeting earlier versions of the framework can continue to be supported using the corresponding version of the library. This is the same pattern we use for all of the OOB packages that we ship out of ASP.NET Core. Looping in @rynowak \ @davidfowl in case they'd like to chime in (or disagree with me 😸)

**Comment by davidfowl** [comment]
There were a few key breaking changes in early versions of ASP.NET Core in 2.0 and this was one of them.

> We try to keep this version as low as possible for max compatibility... if we upgrade this then people are forced upgrade. If it’s as is you can manually reference a higher version and it should work.

This can't be worked around, NSwag needs to re-compile targeting a newer version of this package or use reflection to handle this case (which I don't recommend 😄).

Unfortunately, before ASP.NET Core 3.0 there's no way to target multiple versions of the ASP.NET Core within the same package. This is where you have to decide on a new minimum version (which 2.1 is a safe bet at this point).

**Comment by RicoSuter** [comment]
Ok then we should probably drop support for .NET Core 1.0 and 1.1 and upgrade to the 2.0 packages
