### ISSUE TITLE
System.MissingMethodException: Method not found: 'NJsonSchema.CodeGeneration.CodeArtifactCollection NJsonSchema.CodeGeneration.GeneratorBase.GenerateTypes()'.

### ISSUE THREAD

**Issue by CumpsD** [RicoSuter/NSwag#2175]
I am using the following latest versions:

```
nuget NSwag.CodeGeneration.CSharp 12.2.5
nuget NJsonSchema.CodeGeneration.CSharp 9.14.1

nuget NSwag.CodeGeneration.TypeScript 12.2.5
nuget NJsonSchema.CodeGeneration.TypeScript 9.14.1
```
I am using the sample code to generate a client from a doc:

```csharp
var baseUrl = $"{context.Request.Scheme}://{context.Request.Host}";
var document = await SwaggerDocument.FromUrlAsync($"{baseUrl}/docs/{description}/docs.json");

var settings = new SwaggerToCSharpClientGeneratorSettings
{
    ClassName = $"{options.CSharpClient.ClassName}{description.FirstLetterToUpperCaseOrConvertNullToEmptyString()}",
    CSharpGeneratorSettings =
    {
        Namespace = options.CSharpClient.Namespace,
    }
};

var generator = new SwaggerToCSharpClientGenerator(document, settings);
var code = generator.GenerateFile();

await context.Response.WriteAsync(code);
```

for typescript:

```csharp
var baseUrl = $"{context.Request.Scheme}://{context.Request.Host}";
var document = await SwaggerDocument.FromUrlAsync($"{baseUrl}/docs/{description}/docs.json");

var settings = new SwaggerToTypeScriptClientGeneratorSettings
{
    ClassName = $"{options.TypeScriptClient.ClassName}{description.FirstLetterToUpperCaseOrConvertNullToEmptyString()}",
    Template = TypeScriptTemplate.Angular
};

var generator = new SwaggerToTypeScriptClientGenerator(document, settings);
var code = generator.GenerateFile();

await context.Response.WriteAsync(code);
```

However, at runtime there seems to be a problem:

```
System.MissingMethodException: Method not found: 'NJsonSchema.CodeGeneration.CodeArtifactCollection NJsonSchema.CodeGeneration.GeneratorBase.GenerateTypes()'.
   at NSwag.CodeGeneration.CSharp.Models.CSharpFileTemplateModel.GenerateDtoTypes()
   at NSwag.CodeGeneration.CSharp.SwaggerToCSharpGeneratorBase.GenerateFile(String clientCode, IEnumerable`1 clientClasses, ClientGeneratorOutputType outputType)
   at NSwag.CodeGeneration.ClientGeneratorBase`3.GenerateFile(SwaggerDocument document, ClientGeneratorOutputType type)
   at Be.Vlaanderen.Basisregisters.AspNetCore.Swagger.ReDoc.UseSwaggerDocumentationExtensions.<>c__DisplayClass2_1.<<MapCSharpClients>b__4>d.MoveNext() in D:\dotfiles\repos\gh-aiv\swagger\src\Be.Vlaanderen.Basisregisters.AspNetCore.Swagger.ReDoc\UseSwaggerDocumentationExtensions.cs:line 141
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

It looks like this commit https://github.com/RicoSuter/NJsonSchema/commit/521519b482a71a9bd70cf13ea46c4a77fea4f73b#diff-eab276ebd663b29dee9d96e640e00636 got rid of `NJsonSchema.CodeGeneration.CodeArtifactCollection NJsonSchema.CodeGeneration.GeneratorBase.GenerateTypes()` and changed it to `IEnumerable<CodeArtifact>` but somehow NSwag still expects the old one.

I have been playing with different version combinations trying to get one working, without any luck.

What is the current working version combination?

**Comment by RicoSuter** [comment]
You need to use an njsonschema version < 9.14 for now

**Comment by CumpsD** [comment]
When I do that, I get:

```
System.TypeLoadException: Method 'GenerateFile' in type 'NJsonSchema.CodeGeneration.CSharp.CSharpGenerator' from assembly 'NJsonSchema.CodeGeneration.CSharp, Version=9.13.37.0, Culture=neutral, PublicKeyToken=c2f9c3bdfae56102' does not have an implementation.
   at NSwag.CodeGeneration.CSharp.Models.CSharpFileTemplateModel.GenerateDtoTypes()
   at NSwag.CodeGeneration.CSharp.SwaggerToCSharpGeneratorBase.GenerateFile(String clientCode, IEnumerable`1 clientClasses, ClientGeneratorOutputType outputType)
   at NSwag.CodeGeneration.ClientGeneratorBase`3.GenerateFile(SwaggerDocument document, ClientGeneratorOutputType type)
   at Be.Vlaanderen.Basisregisters.AspNetCore.Swagger.ReDoc.UseSwaggerDocumentationExtensions.<>c__DisplayClass2_1.<<MapCSharpClients>b__4>d.MoveNext() in D:\dotfiles\repos\gh-aiv\swagger\src\Be.Vlaanderen.Basisregisters.AspNetCore.Swagger.ReDoc\UseSwaggerDocumentationExtensions.cs:line 141
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by CumpsD** [comment]
Solved. I had to take an explicit reference to `nuget NJsonSchema 9.13.37` as well, since the nuget dependencies of the others specify `>=`

**Comment by RicoSuter** [comment]
This is quite bad.. but we'll soon release NSwag v13 and NJS v10 - I'm just running the last integration tests etc...

**Comment by CumpsD** [comment]
👍
