### ISSUE TITLE
The JSON property 'item' is defined multiple times on type 'System.ComponentModel.ComponentCollection'.

### ISSUE THREAD

**Issue by littlesmilelove** [RicoSuter/NSwag#2188]
I'm use NSwag.AspNetCore in my asp.net core 2.2 project. But when I visit redoc url, I get a error message.
`The JSON property 'item' is defined multiple times on type 'System.ComponentModel.ComponentCollection'.`

The statktrace is 
```csharp
System.InvalidOperationException: The JSON property 'item' is defined multiple times on type 'System.ComponentModel.ComponentCollection'.
   at NJsonSchema.Generation.JsonSchemaGenerator.LoadPropertyOrFieldAsync(JsonProperty property, MemberInfo propertyInfo, Type parentType, JsonSchema4 parentSchema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GeneratePropertiesAsync(Type type, JsonSchema4 schema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateInheritanceAsync(Type type, JsonSchema4 schema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateObjectAsync(Type type, JsonTypeDescription typeDescription, JsonSchema4 schema, JsonSchemaResolver schemaResolver)
   at NSwag.SwaggerGeneration.SwaggerJsonSchemaGenerator.GenerateObjectAsync(Type type, JsonTypeDescription typeDescription, JsonSchema4 schema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateAsync[TSchemaType](Type type, IEnumerable`1 parentAttributes, TSchemaType schema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateAsync[TSchemaType](Type type, IEnumerable`1 parentAttributes, JsonSchemaResolver schemaResolver)
   at NSwag.SwaggerGeneration.SwaggerJsonSchemaGenerator.GenerateObjectAsync(Type type, JsonTypeDescription typeDescription, JsonSchema4 schema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateAsync[TSchemaType](Type type, IEnumerable`1 parentAttributes, TSchemaType schema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateAsync[TSchemaType](Type type, IEnumerable`1 parentAttributes, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateWithReferenceAndNullabilityAsync[TSchemaType](Type type, IEnumerable`1 parentAttributes, Boolean isNullable, JsonSchemaResolver schemaResolver, Func`3 transformation)
   at NSwag.SwaggerGeneration.SwaggerJsonSchemaGenerator.GenerateWithReferenceAndNullabilityAsync[TSchemaType](Type type, IEnumerable`1 parentAttributes, Boolean isNullable, JsonSchemaResolver schemaResolver, Func`3 transformation)
   at NJsonSchema.Generation.JsonSchemaGenerator.LoadPropertyOrFieldAsync(JsonProperty property, MemberInfo propertyInfo, Type parentType, JsonSchema4 parentSchema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GeneratePropertiesAsync(Type type, JsonSchema4 schema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateObjectAsync(Type type, JsonTypeDescription typeDescription, JsonSchema4 schema, JsonSchemaResolver schemaResolver)
   at NSwag.SwaggerGeneration.SwaggerJsonSchemaGenerator.GenerateObjectAsync(Type type, JsonTypeDescription typeDescription, JsonSchema4 schema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateAsync[TSchemaType](Type type, IEnumerable`1 parentAttributes, TSchemaType schema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateAsync[TSchemaType](Type type, IEnumerable`1 parentAttributes, JsonSchemaResolver schemaResolver)
   at NSwag.SwaggerGeneration.SwaggerJsonSchemaGenerator.GenerateObjectAsync(Type type, JsonTypeDescription typeDescription, JsonSchema4 schema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateAsync[TSchemaType](Type type, IEnumerable`1 parentAttributes, TSchemaType schema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateAsync[TSchemaType](Type type, IEnumerable`1 parentAttributes, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateWithReferenceAndNullabilityAsync[TSchemaType](Type type, IEnumerable`1 parentAttributes, Boolean isNullable, JsonSchemaResolver schemaResolver, Func`3 transformation)
   at NSwag.SwaggerGeneration.SwaggerJsonSchemaGenerator.GenerateWithReferenceAndNullabilityAsync[TSchemaType](Type type, IEnumerable`1 parentAttributes, Boolean isNullable, JsonSchemaResolver schemaResolver, Func`3 transformation)
   at NJsonSchema.Generation.JsonSchemaGenerator.LoadPropertyOrFieldAsync(JsonProperty property, MemberInfo propertyInfo, Type parentType, JsonSchema4 parentSchema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GeneratePropertiesAsync(Type type, JsonSchema4 schema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateObjectAsync(Type type, JsonTypeDescription typeDescription, JsonSchema4 schema, JsonSchemaResolver schemaResolver)
   at NSwag.SwaggerGeneration.SwaggerJsonSchemaGenerator.GenerateObjectAsync(Type type, JsonTypeDescription typeDescription, JsonSchema4 schema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateAsync[TSchemaType](Type type, IEnumerable`1 parentAttributes, TSchemaType schema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateAsync[TSchemaType](Type type, IEnumerable`1 parentAttributes, JsonSchemaResolver schemaResolver)
   at NSwag.SwaggerGeneration.SwaggerJsonSchemaGenerator.GenerateObjectAsync(Type type, JsonTypeDescription typeDescription, JsonSchema4 schema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateAsync[TSchemaType](Type type, IEnumerable`1 parentAttributes, TSchemaType schema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateAsync[TSchemaType](Type type, IEnumerable`1 parentAttributes, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateWithReferenceAndNullabilityAsync[TSchemaType](Type type, IEnumerable`1 parentAttributes, Boolean isNullable, JsonSchemaResolver schemaResolver, Func`3 transformation)
   at NSwag.SwaggerGeneration.SwaggerJsonSchemaGenerator.GenerateWithReferenceAndNullabilityAsync[TSchemaType](Type type, IEnumerable`1 parentAttributes, Boolean isNullable, JsonSchemaResolver schemaResolver, Func`3 transformation)
   at NJsonSchema.Generation.JsonSchemaGenerator.LoadPropertyOrFieldAsync(JsonProperty property, MemberInfo propertyInfo, Type parentType, JsonSchema4 parentSchema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GeneratePropertiesAsync(Type type, JsonSchema4 schema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateInheritanceAsync(Type type, JsonSchema4 schema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateObjectAsync(Type type, JsonTypeDescription typeDescription, JsonSchema4 schema, JsonSchemaResolver schemaResolver)
   at NSwag.SwaggerGeneration.SwaggerJsonSchemaGenerator.GenerateObjectAsync(Type type, JsonTypeDescription typeDescription, JsonSchema4 schema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateAsync[TSchemaType](Type type, IEnumerable`1 parentAttributes, TSchemaType schema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateAsync[TSchemaType](Type type, IEnumerable`1 parentAttributes, JsonSchemaResolver schemaResolver)
   at NSwag.SwaggerGeneration.SwaggerJsonSchemaGenerator.GenerateObjectAsync(Type type, JsonTypeDescription typeDescription, JsonSchema4 schema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateAsync[TSchemaType](Type type, IEnumerable`1 parentAttributes, TSchemaType schema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateAsync[TSchemaType](Type type, IEnumerable`1 parentAttributes, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateWithReferenceAndNullabilityAsync[TSchemaType](Type type, IEnumerable`1 parentAttributes, Boolean isNullable, JsonSchemaResolver schemaResolver, Func`3 transformation)
   at NSwag.SwaggerGeneration.SwaggerJsonSchemaGenerator.GenerateWithReferenceAndNullabilityAsync[TSchemaType](Type type, IEnumerable`1 parentAttributes, Boolean isNullable, JsonSchemaResolver schemaResolver, Func`3 transformation)
   at NJsonSchema.Generation.JsonSchemaGenerator.LoadPropertyOrFieldAsync(JsonProperty property, MemberInfo propertyInfo, Type parentType, JsonSchema4 parentSchema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GeneratePropertiesAsync(Type type, JsonSchema4 schema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateObjectAsync(Type type, JsonTypeDescription typeDescription, JsonSchema4 schema, JsonSchemaResolver schemaResolver)
   at NSwag.SwaggerGeneration.SwaggerJsonSchemaGenerator.GenerateObjectAsync(Type type, JsonTypeDescription typeDescription, JsonSchema4 schema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateAsync[TSchemaType](Type type, IEnumerable`1 parentAttributes, TSchemaType schema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateAsync[TSchemaType](Type type, IEnumerable`1 parentAttributes, JsonSchemaResolver schemaResolver)
   at NSwag.SwaggerGeneration.SwaggerJsonSchemaGenerator.GenerateObjectAsync(Type type, JsonTypeDescription typeDescription, JsonSchema4 schema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateAsync[TSchemaType](Type type, IEnumerable`1 parentAttributes, TSchemaType schema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateAsync[TSchemaType](Type type, IEnumerable`1 parentAttributes, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateWithReferenceAndNullabilityAsync[TSchemaType](Type type, IEnumerable`1 parentAttributes, Boolean isNullable, JsonSchemaResolver schemaResolver, Func`3 transformation)
   at NSwag.SwaggerGeneration.SwaggerJsonSchemaGenerator.GenerateWithReferenceAndNullabilityAsync[TSchemaType](Type type, IEnumerable`1 parentAttributes, Boolean isNullable, JsonSchemaResolver schemaResolver, Func`3 transformation)
   at NSwag.SwaggerGeneration.AspNetCore.Processors.OperationResponseProcessor.ProcessAsync(OperationProcessorContext operationProcessorContext)
   at NSwag.SwaggerGeneration.AspNetCore.AspNetCoreToSwaggerGenerator.RunOperationProcessorsAsync(SwaggerDocument document, ApiDescription apiDescription, Type controllerType, MethodInfo methodInfo, SwaggerOperationDescription operationDescription, List`1 allOperations, SwaggerGenerator swaggerGenerator, SwaggerSchemaResolver schemaResolver)
   at NSwag.SwaggerGeneration.AspNetCore.AspNetCoreToSwaggerGenerator.AddOperationDescriptionsToDocumentAsync(SwaggerDocument document, Type controllerType, List`1 operations, SwaggerGenerator swaggerGenerator, SwaggerSchemaResolver schemaResolver)
   at NSwag.SwaggerGeneration.AspNetCore.AspNetCoreToSwaggerGenerator.GenerateForControllersAsync(SwaggerDocument document, IGrouping`2[] apiGroups, SwaggerSchemaResolver schemaResolver)
   at NSwag.SwaggerGeneration.AspNetCore.AspNetCoreToSwaggerGenerator.GenerateAsync(ApiDescriptionGroupCollection apiDescriptionGroups)
   at NSwag.SwaggerGeneration.AspNetCore.AspNetCoreToSwaggerGenerator.GenerateAsync(Object serviceProvider)
   at NSwag.AspNetCore.SwaggerDocumentProvider.GenerateAsync(String documentName)
   at NSwag.AspNetCore.Middlewares.SwaggerDocumentMiddleware.GenerateDocumentAsync(HttpContext context)
   at NSwag.AspNetCore.Middlewares.SwaggerDocumentMiddleware.GetDocumentAsync(HttpContext context)
   at NSwag.AspNetCore.Middlewares.SwaggerDocumentMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events) in C:\local\identity\server4\IdentityServer4\src\Hosting\IdentityServerMiddleware.cs:line 72
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\Hosting\BaseUrlMiddleware.cs:line 36
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at DataExplorer.Server.Middleware.CustomExceptionHandlerMiddleware.Invoke(HttpContext context) in E:\Source\Repos\DataExplorer\server\DataExplorer.Server\Middleware\CustomExceptionHandlerMiddleware.cs:line 52
```

**Comment by RicoSuter** [comment]
Somewhere in your public API you expose System.ComponentModel.ComponentCollection which cannot be converted to a schema..

**Comment by littlesmilelove** [comment]
@RicoSuter  But I search for this type, can't find the match result.

**Comment by Jestar342** [comment]
The same error occurs for `System.Collections.Specialized.NameValueCollection`, too.

**Comment by nimasTT** [comment]
I get the same stacktrace in aspcore3.0 since updating to NSwag 13.1.5

**Comment by AleRoe** [comment]
Hi @RicoSuter   

I had the same issue using NSwag 13.1.6.
In my usecase, my ApiController returns a type which inherits from System.ComponentModel.Component (which implements IContainer->ComponentCollection)
The Controller and serialization of my type work fine, but Swagger crashes when trying to load the API definition. 
I tried using explicit MemberSerialization ([JsonObject(MemberSerialization.OptIn)]) and setting the JsonPropertyAttribut only on my own public properties, but it seems that this is ignored during SchemaGeneration (Is this the expected behaviour by the way? I would expect that members that are not meant to be serialized are excluded from SchemaGeneration?).

What eventually worked for me was setting the ExcludedTypeNames property, since I don't require any of the Component properties to be serialized anyway:

```
services.AddSwaggerDocument(configure =>
                {
                    configure.ExcludedTypeNames = new string[] {typeof(Component).FullName};
                });

```
Hope this is of value.

Regards
Alexander

**Comment by bishwasgautam** [comment]
I am facing exact issue with version 13.10.2 . Any update from the team?

**Comment by RicoSuter** [comment]
What might work is adding [JsonSchemaIgnore] or [OpenApiIgnore] on the class/property exposing the class.
