### ISSUE TITLE
NJsonSchema Object reference not set to an instance of an object in NSwag.AspNetCore 13.0.2

### ISSUE THREAD

**Issue by redplane** [RicoSuter/NSwag#2260]
Hi,

I have updated `NSwag.AspNetCore` to version `13.0.2`.
When I tried accessing to [http://localhost:62744/swagger/index.html](http://localhost:62744/swagger/index.html), I faced with an exception: **Object reference not set to an instance of an object**

This is my `Startup.cs` file:

```
public class Startup
{
	#region Properties

	public IConfiguration Configuration { get; }

	private readonly IHostingEnvironment _hostingEnvironment;

	#endregion

	#region Methods

	public Startup(IConfiguration configuration, IHostingEnvironment hostingEnvironment)
	{
		Configuration = configuration;
		_hostingEnvironment = hostingEnvironment;
	}

	/// <summary>
	///     This method gets called by the runtime. Use this method to add services to the container.
	/// </summary>
	/// <param name="services"></param>
	public void ConfigureServices(IServiceCollection services)
	{
		
		//...
	
		// Swagger document.
		services.AddOpenApiDocument(options =>
		{
			options.DocumentName = "my-app";
			options.Title = "my-app api";
			options.Description = "my-app description";

			options.GenerateEnumMappingDescription = true;

			var accessTokenSecurityScheme = new OpenApiSecurityScheme();
			accessTokenSecurityScheme.AuthorizationUrl = "http://localhost:62744";
			accessTokenSecurityScheme.Flow = OpenApiOAuth2Flow.Password;
			accessTokenSecurityScheme.Scheme = JwtBearerDefaults.AuthenticationScheme;
			accessTokenSecurityScheme.Type = OpenApiSecuritySchemeType.ApiKey;
			accessTokenSecurityScheme.In = OpenApiSecurityApiKeyLocation.Header;
			accessTokenSecurityScheme.Name = "Authorization";
			accessTokenSecurityScheme.Description = "Copy 'Bearer ' + valid JWT token into field";

			options.AddSecurity("my-app bearer token", new[] {"profile", "offline_access"},
				accessTokenSecurityScheme);
		});
		
		//...
		
		services
			.AddMvc(options =>
			{
				// only allow authenticated users
				var policy = new AuthorizationPolicyBuilder()
					.RequireAuthenticatedUser()
					.AddAuthenticationSchemes(IdentityServerAuthenticationDefaults.AuthenticationScheme)
#if !ALLOW_ANONYMOUS
					.AddRequirements(new SolidUserRequirement())
#endif
					.Build();

				options.Filters.Add(new AuthorizeFilter(policy));
			})
			.AddFluentValidation(x => x.RegisterValidatorsFromAssemblyContaining<RegisterUserCommandValidator>())
			.AddJsonOptions(options =>
			{
				var camelCasePropertyNamesContractResolver = new CamelCasePropertyNamesContractResolver();
				options.SerializerSettings.ContractResolver = camelCasePropertyNamesContractResolver;
				options.SerializerSettings.DefaultValueHandling = DefaultValueHandling.Ignore;
			})
			.SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
	}

	/// <summary>
	///     This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
	/// </summary>
	/// <param name="app"></param>
	/// <param name="env"></param>
	public void Configure(IApplicationBuilder app, IHostingEnvironment env)
	{
		if (env.IsDevelopment())
			app.UseDeveloperExceptionPage();
		else
			app.UseHsts();

//..
		//app.UseHangfireServer();
		//app.UseHangfireDashboard();

		// Enable mvc pipeline.
		app
			.UseMvcWithDefaultRoute();

		app.UseOpenApi(); // Serves the registered OpenAPI/Swagger documents by default on `/swagger/{documentName}/swagger.json`
		app.UseSwaggerUi3(); // Serves the Swagger UI 3 web ui to view the OpenAPI/Swagger documents by default on `/swagger`
	}

	#endregion
}
```

Anything wrong have I done ?

**Comment by RicoSuter** [comment]
Can you provide the full stack trave?

**Comment by redplane** [comment]
Sure, here my stack trace is:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at NJsonSchema.Generation.DefaultReflectionService.GetDescription(ContextualType contextualType, ReferenceTypeNullHandling defaultReferenceTypeNullHandling, JsonSchemaGeneratorSettings settings)
   at NJsonSchema.Generation.JsonSchemaGenerator.LoadPropertyOrField(JsonProperty jsonProperty, ContextualMemberInfo memberInfo, Type parentType, JsonSchema parentSchema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateProperties(Type type, JsonSchema schema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateObject(JsonSchema schema, JsonTypeDescription typeDescription, JsonSchemaResolver schemaResolver)
   at NSwag.Generation.OpenApiSchemaGenerator.GenerateObject(JsonSchema schema, JsonTypeDescription typeDescription, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.Generate[TSchemaType](TSchemaType schema, ContextualType contextualType, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.Generate[TSchemaType](ContextualType contextualType, JsonSchemaResolver schemaResolver)
   at NSwag.Generation.OpenApiSchemaGenerator.GenerateObject(JsonSchema schema, JsonTypeDescription typeDescription, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.Generate[TSchemaType](TSchemaType schema, ContextualType contextualType, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.Generate[TSchemaType](ContextualType contextualType, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateWithReferenceAndNullability[TSchemaType](ContextualType contextualType, Boolean isNullable, JsonSchemaResolver schemaResolver, Action`2 transformation)
   at NJsonSchema.Generation.JsonSchemaGenerator.LoadPropertyOrField(JsonProperty jsonProperty, ContextualMemberInfo memberInfo, Type parentType, JsonSchema parentSchema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateProperties(Type type, JsonSchema schema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateObject(JsonSchema schema, JsonTypeDescription typeDescription, JsonSchemaResolver schemaResolver)
   at NSwag.Generation.OpenApiSchemaGenerator.GenerateObject(JsonSchema schema, JsonTypeDescription typeDescription, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.Generate[TSchemaType](TSchemaType schema, ContextualType contextualType, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.Generate[TSchemaType](ContextualType contextualType, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateWithReferenceAndNullability[TSchemaType](ContextualType contextualType, Boolean isNullable, JsonSchemaResolver schemaResolver, Action`2 transformation)
   at NSwag.Generation.AspNetCore.Processors.OperationParameterProcessor.AddBodyParameter(OperationProcessorContext context, ExtendedApiParameterDescription extendedApiParameter)
   at NSwag.Generation.AspNetCore.Processors.OperationParameterProcessor.Process(OperationProcessorContext operationProcessorContext)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.RunOperationProcessors(OpenApiDocument document, ApiDescription apiDescription, Type controllerType, MethodInfo methodInfo, OpenApiOperationDescription operationDescription, List`1 allOperations, OpenApiDocumentGenerator swaggerGenerator, OpenApiSchemaResolver schemaResolver)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.AddOperationDescriptionsToDocument(OpenApiDocument document, Type controllerType, List`1 operations, OpenApiDocumentGenerator swaggerGenerator, OpenApiSchemaResolver schemaResolver)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateForControllers(OpenApiDocument document, IGrouping`2[] apiGroups, OpenApiSchemaResolver schemaResolver)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateAsync(ApiDescriptionGroupCollection apiDescriptionGroups)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateAsync(Object serviceProvider)
   at NSwag.AspNetCore.OpenApiDocumentProvider.GenerateAsync(String documentName)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GenerateDocumentAsync(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GetDocumentAsync(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\src\Hosting\IdentityServerMiddleware.cs:line 72
   at IdentityServer4.Hosting.MutualTlsTokenEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\src\Hosting\MtlsTokenEndpointMiddleware.cs:line 60
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\src\Hosting\BaseUrlMiddleware.cs:line 36
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)

```

**Comment by RicoSuter** [comment]
Can you provide the model classes to repro this?

**Comment by redplane** [comment]
> Can you provide the model classes to repro this?

What model class do you need ?
I dont understand :|

**Comment by RicoSuter** [comment]
One of the body request model classes cause this problem.

**Comment by redplane** [comment]
> One of the body request model classes cause this problem.

Using the configuration above, when I accessed to [http://localhost:9001/swagger](/swagger), the error happened. Using the older version, no error is thrown back.

I'll try reproduced this error on a new project, the current project belongs to my company.
