### ISSUE TITLE
Is there only one instance of the JsonExceptionFilterAttribute?

### ISSUE THREAD

**Issue by kwbonte** [RicoSuter/NSwag#2290]
"Collection was modified; enumeration operation may not execute."

https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.AspNet.WebApi/JsonExceptionFilterAttribute.cs#L108

Newtonsoft has seemed to have compatibility issues in other posts so here is my version of newtonsoft and dotnet:
- newtonsoft: 12.0.1
- Microsoft.AspNet.Core : 5.2.3

There seems to be a problem in the JsonExceptionFilterAttribute where when I use it to generate an exception message on the client side it is works, but generates the collection was modified error above.

Here is the console output:
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at NSwag.AspNet.WebApi.JsonExceptionFilterAttribute.CopySettings(JsonSerializerSettings settings)
   at NSwag.AspNet.WebApi.JsonExceptionFilterAttribute.OnActionExecuted(HttpActionExecutedContext context)
   at System.Web.Http.Filters.ActionFilterAttribute.OnActionExecutedAsync(HttpActionExecutedContext actionExecutedContext, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DaksWeb.Security.AddChallengeOnUnauthorizedResult.<ExecuteAsync>d__9.MoveNext() in D:\daks\Source\Daks\DaksWeb\Security\AddChallengeOnUnauthorizedResult.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.AuthenticationFilterResult.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()

**Comment by kwbonte** [comment]
Meant to say Microscoft.AspNet.MVC 5.2.3 this is not a dotnet core app

**Comment by RicoSuter** [comment]
This is quite strange, as we only modify the converters on a new instance... maybe the converters collection is modify of the input settings? How can this be?

We could add `.ToArray()` here 
https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.AspNet.WebApi/JsonExceptionFilterAttribute.cs#L117

But we should know why the input converters changes at the time of this method call...

**Comment by kwbonte** [comment]
https://github.com/kwbonte/nswag_JsonExceptionFilterAttributeProblem 

I have made a quick web api to recreate my problem, if you clone this and run it: go to {localhost:###}/api/documentation/get and you should get the exception with the desired text to show up, but on refresh the exception gets turned into the problem above. 

The desired functionality is for the exception message to stay the same on refresh, is this possible with the JsonExceptionFilter?

**Comment by RicoSuter** [comment]
Of course it doesnt just work: 

![image](https://user-images.githubusercontent.com/2603405/60610157-80681880-9dc3-11e9-9d8f-533019d92342.png)

Any idea? It's a long time since I used ASP.NET

**Comment by jfoshee** [comment]
@RicoSuter I have not personally debugged the code, but I noticed one thing that seems suspect...

In the first step each Property seems to be naively copied. So each reference property will hold a reference to the object on the source settings object.

In the second step the Converters are copied. Because the Converters of the destination is actually the same object as the Converters in the source, you are effectively copying the items into the same collection. Thus the collection is modified during enumeration.

As an aside I can verify this issue does repro in .NET Core as well.

**Comment by kwbonte** [comment]
@RicoSuter I believe the issue you have encountered is not running nuget restore, if you are using visual studio to run this, in the top right there is a search bar, type manage nuget packages, select the first option, there should be a list of packages and a popup option to restore. select restore and run the app. it should start on a 404 error and you have to manually change the url to the specified path above.

**Comment by RicoSuter** [comment]
Created a PR which fixes this for me: https://github.com/RicoSuter/NSwag/pull/2292
