### ISSUE TITLE
Exception after upgrading to v13

### ISSUE THREAD

**Issue by maxmantz** [RicoSuter/NSwag#2306]
After upgrading to version 13 I get the following exception on startup:

```
Autofac.Core.DependencyResolutionException
  HResult=0x80131500
  Nachricht = An exception was thrown while activating λ:Microsoft.AspNetCore.Routing.EndpointDataSource[] -> Microsoft.AspNetCore.Mvc.Internal.MvcEndpointDataSource.
  Quelle = Autofac
  Stapelüberwachung:
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder app, Action`1 configureRoutes)
   at Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvcWithDefaultRoute(IApplicationBuilder app)
   at GEORGCore.API.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, IClientService clientService) in C:\Users\USER\Documents\georgcore\GEORGCore.API\Startup.cs:line 257

Innere Ausnahme 1:
DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.AspNetCore.Mvc.Infrastructure.IActionDescriptorCollectionProvider, Microsoft.AspNetCore.Mvc.Internal.MvcEndpointInvokerFactory, Microsoft.AspNetCore.Routing.ParameterPolicyFactory)' on type 'MvcEndpointDataSource'.

Innere Ausnahme 2:
ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'GenerateAsync' in type 'NSwag.SwaggerGeneration.AspNetCore.AspNetCoreToSwaggerGenerator' from assembly 'NSwag.SwaggerGeneration.AspNetCore, Version=12.3.0.0, Culture=neutral, PublicKeyToken=c2d88086e098d109' does not have an implementation.
Could not load type 'NJsonSchema.ReferenceTypeNullHandling' from assembly 'NJsonSchema, Version=10.0.21.0, Culture=neutral, PublicKeyToken=c2f9c3bdfae56102'.
Could not load type 'NSwag.SwaggerDocument' from assembly 'NSwag.Core, Version=13.0.4.0, Culture=neutral, PublicKeyToken=c2d88086e098d109'.
Could not load type 'NSwag.SwaggerDocument' from assembly 'NSwag.Core, Version=13.0.4.0, Culture=neutral, PublicKeyToken=c2d88086e098d109'.
Could not load type 'NSwag.SwaggerOperationDescription' from assembly 'NSwag.Core, Version=13.0.4.0, Culture=neutral, PublicKeyToken=c2d88086e098d109'.
Could not load type 'NSwag.SwaggerOperationDescription' from assembly 'NSwag.Core, Version=13.0.4.0, Culture=neutral, PublicKeyToken=c2d88086e098d109'.
Could not load type 'NSwag.SwaggerDocument' from assembly 'NSwag.Core, Version=13.0.4.0, Culture=neutral, PublicKeyToken=c2d88086e098d109'.
Could not load type 'NSwag.SwaggerParameter' from assembly 'NSwag.Core, Version=13.0.4.0, Culture=neutral, PublicKeyToken=c2d88086e098d109'.
Could not load type 'NSwag.SwaggerParameter' from assembly 'NSwag.Core, Version=13.0.4.0, Culture=neutral, PublicKeyToken=c2d88086e098d109'.
Could not load type 'NSwag.SwaggerParameter' from assembly 'NSwag.Core, Version=13.0.4.0, Culture=neutral, PublicKeyToken=c2d88086e098d109'.
Could not load type 'NSwag.SwaggerParameter' from assembly 'NSwag.Core, Version=13.0.4.0, Culture=neutral, PublicKeyToken=c2d88086e098d109'.
Could not load type 'NJsonSchema.JsonSchema4' from assembly 'NJsonSchema, Version=10.0.21.0, Culture=neutral, PublicKeyToken=c2f9c3bdfae56102'.
```

My config:

```
// ConfigureServices
services.AddOpenApiDocument(doc =>
            {
                doc.Title = "My API";
                doc.AddSecurity("bearer", Enumerable.Empty<string>(), new OpenApiSecurityScheme
                {
                    Type = OpenApiSecuritySchemeType.OAuth2,
                    Description = "Authorization to my API",
                    Flow = OpenApiOAuth2Flow.Implicit,
                    Flows = new OpenApiOAuthFlows
                    {
                        Implicit = new OpenApiOAuthFlow
                        {
                            Scopes = new Dictionary<string, string>
                            {
                                {"my_scope", "Access to my API"}
                            },
                            AuthorizationUrl = $"{Configuration.GetValue<string>("BaseUrl")}/connect/authorize",
                            TokenUrl = $"{Configuration.GetValue<string>("BaseUrl")}/connect/token"
                        }
                    }
                });
                doc.OperationProcessors.Add(new AspNetCoreOperationSecurityScopeProcessor("bearer"));
            });
```
and
```
// Configure
            app.UseSwaggerUi3(cfg =>
            {
                cfg.OAuth2Client = new OAuth2ClientSettings
                {
                    AppName = "My API Swagger Documentation",
                    ClientId = "swagger_ui",
                    ClientSecret = "swagger_secret",
                    Realm = "swagger_realm",
                    AdditionalQueryStringParameters = { { "foo", "bar" }}
                };
            });
```

Any ideas what could cause this?

**Comment by RicoSuter** [comment]
> from assembly 'NSwag.SwaggerGeneration.AspNetCore, Version=12.3.0.0,

Maybe it's because you still have references to v12?

**Comment by maxmantz** [comment]
@RicoSuter Indeed - I still had references to `NSwag.SwaggerGeneration`, `NSwag.SwaggerGeneration.AspNetCore` & `NSwag.SwaggerGeneration.WebApi` referencing version 12.

I removed these packages and everything works again without issues. Thanks for the quick reply!
