### ISSUE TITLE
Missing NSwag.AspNetCore.Launcher.x86.exe in nuget package

### ISSUE THREAD

**Issue by terry-flowers** [RicoSuter/NSwag#2324]
Targeting x86, the client can't generate using an msbuild task because NSwag.AspNetCore.Launcher.x86.exe is missing from the nuget package. Everything works fine when running from NSwag Studio.
```
>"C:\Users\zzz\.nuget\packages\nswag.msbuild\13.0.4\build\../tools/Win/NSwag.x86.exe" run CloudApi.nswag /variables:Configuration=Debug /runtime:WinX86

NSwag command line tool for .NET 4.6.1+ WinX86, toolchain v13.0.4.0 (NJsonSchema v10.0.21.0 (Newtonsoft.Json v11.0.0.0))
Visit http://NSwag.org for more information.
NSwag bin directory: C:\Users\zzz\.nuget\packages\nswag.msbuild\13.0.4\tools\Win

Executing file 'CloudApi.nswag' with variables 'Configuration=Debug'...
System.InvalidOperationException: Unable to locate NSwag.AspNetCore.Launcher.x86.exe in C:\Users\zzz\.nuget\packages\nswag.msbuild\13.0.4\tools\Win\.
   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.<RunAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.NSwagDocumentBase.<GenerateSwaggerDocumentAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.NSwagDocument.<ExecuteAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.Document.ExecuteDocumentCommand.<ExecuteDocumentAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.Document.ExecuteDocumentCommand.<RunAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NConsole.CommandLineProcessor.<ProcessSingleAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NConsole.CommandLineProcessor.<ProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args)
```
```
C:\Users\zzz\.nuget\packages\nswag.msbuild\13.0.4\tools\Win>dir
 Volume in drive C is Windows
 Volume Serial Number is 1848-FA59

 Directory of C:\Users\zzz\.nuget\packages\nswag.msbuild\13.0.4\tools\Win

23/07/2019  15:06    <DIR>          .
23/07/2019  15:06    <DIR>          ..
...
05/07/2019  16:47            10,240 NSwag.Annotations.dll
05/07/2019  16:47             2,780 NSwag.Annotations.pdb
05/07/2019  16:47            15,566 NSwag.Annotations.xml
05/07/2019  16:47            12,288 NSwag.AspNetCore.Launcher.exe
05/07/2019  16:47               176 NSwag.AspNetCore.Launcher.exe.config
05/07/2019  16:47             1,292 NSwag.AspNetCore.Launcher.pdb
05/07/2019  16:47            20,480 NSwag.AssemblyLoader.dll
05/07/2019  16:44               988 NSwag.AssemblyLoader.dll.config
05/07/2019  16:47             3,484 NSwag.AssemblyLoader.pdb
05/07/2019  16:47             2,800 NSwag.AssemblyLoader.xml
05/07/2019  16:47            98,304 NSwag.CodeGeneration.CSharp.dll
05/07/2019  16:47             9,936 NSwag.CodeGeneration.CSharp.pdb
05/07/2019  16:47            49,857 NSwag.CodeGeneration.CSharp.xml
05/07/2019  16:47            40,448 NSwag.CodeGeneration.dll
05/07/2019  16:44               420 NSwag.CodeGeneration.dll.config
05/07/2019  16:47            10,336 NSwag.CodeGeneration.pdb
05/07/2019  16:47            88,576 NSwag.CodeGeneration.TypeScript.dll
05/07/2019  16:47             7,448 NSwag.CodeGeneration.TypeScript.pdb
05/07/2019  16:47            41,509 NSwag.CodeGeneration.TypeScript.xml
05/07/2019  16:47            54,289 NSwag.CodeGeneration.xml
05/07/2019  16:47           179,200 NSwag.Commands.dll
05/07/2019  16:47            38,568 NSwag.Commands.pdb
05/07/2019  16:47            21,162 NSwag.Commands.xml
05/07/2019  16:47            83,968 NSwag.Core.dll
05/07/2019  16:44               420 NSwag.Core.dll.config
05/07/2019  16:47            19,892 NSwag.Core.pdb
05/07/2019  16:47            60,292 NSwag.Core.xml
05/07/2019  16:47            10,240 NSwag.Core.Yaml.dll
05/07/2019  16:47             1,324 NSwag.Core.Yaml.pdb
05/07/2019  16:47             5,632 NSwag.exe
05/07/2019  16:47            22,736 NSwag.exe.config
05/07/2019  16:47            40,448 NSwag.Generation.AspNetCore.dll
05/07/2019  16:47             8,652 NSwag.Generation.AspNetCore.pdb
05/07/2019  16:47            10,201 NSwag.Generation.AspNetCore.xml
05/07/2019  16:47            47,104 NSwag.Generation.dll
05/07/2019  16:47            10,360 NSwag.Generation.pdb
05/07/2019  16:47            51,712 NSwag.Generation.WebApi.dll
05/07/2019  16:47             9,744 NSwag.Generation.WebApi.pdb
05/07/2019  16:47             8,153 NSwag.Generation.WebApi.xml
05/07/2019  16:47            30,301 NSwag.Generation.xml
05/07/2019  16:47               452 NSwag.pdb
05/07/2019  16:47             5,632 NSwag.x86.exe
05/07/2019  16:47            22,192 NSwag.x86.exe.config
...
             224 File(s)     10,597,850 bytes
               2 Dir(s)  133,613,330,432 bytes free
```

**Comment by RicoSuter** [comment]
Still a problem with v13.0.6?

**Comment by terry-flowers** [comment]
Yes, this is still a problem 13.0.6.

The NSwag.AspNetCore.Launcher.x86.exe file is still missing from the msbuild nuget package.

```
"C:\Users\zzz\.nuget\packages\nswag.msbuild\13.0.6\build\../tools/Win/NSwag.x86.exe" run CloudApi.nswag
NSwag command line tool for .NET 4.6.1+ WinX86, toolchain v13.0.6.0 (NJsonSchema v10.0.23.0 (Newtonsoft.Json v11.0.0.0))
Visit http://NSwag.org for more information.
NSwag bin directory: C:\Users\zzz\.nuget\packages\nswag.msbuild\13.0.6\tools\Win

Executing file 'CloudApi.nswag' with variables ''...
System.InvalidOperationException: Unable to locate NSwag.AspNetCore.Launcher.x86.exe in C:\Users\zzz\.nuget\packages\nswag.msbuild\13.0.6\tools\Win\.
   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.<RunAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.NSwagDocumentBase.<GenerateSwaggerDocumentAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.NSwagDocument.<ExecuteAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.Document.ExecuteDocumentCommand.<ExecuteDocumentAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.Document.ExecuteDocumentCommand.<RunAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NConsole.CommandLineProcessor.<ProcessSingleAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NConsole.CommandLineProcessor.<ProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args)
```
