### ISSUE TITLE
CancellationToken parameters in web apis appear as an expanded struct

### ISSUE THREAD

**Issue by blushingpenguin** [RicoSuter/NSwag#2347]
for example

```csharp
[HttpGet("SwaggerTest")]
public async Task SwaggerTest(CancellationToken cancellationToken)
```
is generated as
```csharp
System.Threading.Tasks.Task SwaggerTestAsync(bool? isCancellationRequested, bool? canBeCanceled, IntPtr waitHandle_Handle, bool? waitHandle_SafeWaitHandle_IsInvalid, bool? waitHandle_SafeWaitHandle_IsClosed);
```
whereas the CancellationToken should be ignored when generating the client (CancellationTokens in MVC controllers are automagically bound to a per request token that is cancelled if the client connection drops).

swagger seems to be treating the token as a complex query parameter and expanding it as per
https://github.com/RicoSuter/NSwag/issues/96

**Comment by blushingpenguin** [comment]
The following error might help, shows that it's using AspNetCoreOpenApiDocumentGenerator which appears to call into an MS library.  (I'm trying to trace through it at present).

```
1>------ Build started: Project: Vendeq.Apps.Api, Configuration: Debug Any CPU ------
1>Vendeq.Apps.Api -> C:\dev\Vendeq.Apps.Api\Vendeq.Apps.Api\bin\Debug\netcoreapp2.2\Vendeq.Apps.Api.dll
2>------ Build started: Project: Vendeq.Apps.Api.Client, Configuration: Debug Any CPU ------
3>------ Build started: Project: Vendeq.Apps.Api.Tests, Configuration: Debug Any CPU ------
3>Vendeq.Apps.Api.Tests -> C:\dev\Vendeq.Apps.Api\Vendeq.Apps.Api.Tests\bin\Debug\netcoreapp2.2\Vendeq.Apps.Api.Tests.dll
2>NSwag command line tool for .NET Core NetCore22, toolchain v13.0.4.0 (NJsonSchema v10.0.21.0 (Newtonsoft.Json v11.0.0.0))
2>Visit http://NSwag.org for more information.
2>NSwag bin directory: C:\Users\mark\.nuget\packages\nswag.msbuild\13.0.4\tools\NetCore22
2>
2>Executing file 'nswag.json' with variables 'Configuration=Debug,OutputPath=obj\Debug\netcoreapp2.2\'...
2>Launcher directory: C:\Users\mark\.nuget\packages\nswag.msbuild\13.0.4\tools\NetCore22
2>dbug: Microsoft.AspNetCore.Mvc.MvcJsonOptions[0]
2>      Compatibility switch AllowInputFormatterExceptionMessages in type MvcJsonOptions is using default value False
2>dbug: Microsoft.AspNetCore.Mvc.MvcOptions[0]
2>      Compatibility switch AllowCombiningAuthorizeFilters in type MvcOptions is using default value False
2>dbug: Microsoft.AspNetCore.Mvc.MvcOptions[0]
2>      Compatibility switch AllowBindingHeaderValuesToNonStringModelTypes in type MvcOptions is using default value False
2>dbug: Microsoft.AspNetCore.Mvc.MvcOptions[0]
2>      Compatibility switch AllowValidatingTopLevelNodes in type MvcOptions is using default value False
2>dbug: Microsoft.AspNetCore.Mvc.MvcOptions[0]
2>      Compatibility switch InputFormatterExceptionPolicy in type MvcOptions is using default value AllExceptions
2>dbug: Microsoft.AspNetCore.Mvc.MvcOptions[0]
2>      Compatibility switch SuppressBindingUndefinedValueToEnumType in type MvcOptions is using default value False
2>dbug: Microsoft.AspNetCore.Mvc.MvcOptions[0]
2>      Compatibility switch EnableEndpointRouting in type MvcOptions is using default value False
2>dbug: Microsoft.AspNetCore.Mvc.MvcOptions[0]
2>      Compatibility switch MaxValidationDepth in type MvcOptions is using default value (null)
2>dbug: Microsoft.AspNetCore.Mvc.MvcOptions[0]
2>      Compatibility switch AllowShortCircuitingValidationWhenNoValidatorsArePresent in type MvcOptions is using default value False
2>dbug: Microsoft.AspNetCore.Mvc.ApiBehaviorOptions[0]
2>      Compatibility switch SuppressMapClientErrors in type ApiBehaviorOptions is using compatibility value True for version Version_2_0
2>dbug: Microsoft.AspNetCore.Mvc.ApiBehaviorOptions[0]
2>      Compatibility switch SuppressUseValidationProblemDetailsForInvalidModelStateResponses in type ApiBehaviorOptions is using compatibility value True for version Version_2_0
2>dbug: Microsoft.AspNetCore.Mvc.ApiBehaviorOptions[0]
2>      Compatibility switch AllowInferringBindingSourceForCollectionTypesAsFromQuery in type ApiBehaviorOptions is using compatibility value True for version Version_2_0
2>System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Action 'Vendeq.Apps.Api.Controllers.GlobalAppController.UpdateBasicDetails (Vendeq.Apps.Api)' has more than one parameter that was specified or inferred as bound from request body. Only one parameter per action may be bound from body. Inspect the following parameters, and use 'FromQueryAttribute' to specify bound from query, 'FromRouteAttribute' to specify bound from route, and 'FromBodyAttribute' for parameters to be bound from body:
2>CancellationToken cancellationToken
2>BasicAppDetailsDto item
2>   at Microsoft.AspNetCore.Mvc.ApplicationModels.InferParameterBindingInfoConvention.InferParameterBindingSources(ActionModel action)
2>   at Microsoft.AspNetCore.Mvc.ApplicationModels.ApiBehaviorApplicationModelProvider.OnProvidersExecuting(ApplicationModelProviderContext context)
2>   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.BuildModel()
2>   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetDescriptors()
2>   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
2>   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.UpdateCollection()
2>   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.Initialize()
2>   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.get_ActionDescriptors()
2>   at Microsoft.AspNetCore.Mvc.ApiExplorer.ApiDescriptionGroupCollectionProvider.get_ApiDescriptionGroups()
2>   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateAsync(Object serviceProvider)
2>   at NSwag.AspNetCore.OpenApiDocumentProvider.GenerateAsync(String documentName)
2>   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.GenerateDocumentWithDocumentProviderAsync(IWebHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 286
2>   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.GenerateDocumentAsync(AssemblyLoader assemblyLoader, IWebHost host, String currentWorkingDirectory) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 275
2>   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToOpenApiGeneratorCommandEntryPoint.<>c__DisplayClass0_0.<<Process>b__0>d.MoveNext() in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiGeneratorCommandEntryPoint.cs:line 30
2>--- End of stack trace from previous location where exception was thrown ---
2>   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToOpenApiGeneratorCommandEntryPoint.Process(String commandContent, String outputFile, String applicationName) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiGeneratorCommandEntryPoint.cs:line 29
2>   --- End of inner exception stack trace ---
2>   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
2>   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2>   at NSwag.AspNetCore.Launcher.Program.Main(String[] args) in C:\projects\nswag\src\NSwag.AspNetCore.Launcher\Program.cs:line 170
2>System.InvalidOperationException: Swagger generation failed with non-zero exit code '1'.
2>   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 226
2>   at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocumentBase.cs:line 279
2>   at NSwag.Commands.NSwagDocument.ExecuteAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocument.cs:line 81
2>   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 85
2>   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 32
2>   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
2>   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
2>   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
2>   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 56
2>C:\dev\Vendeq.Apps.Api\Vendeq.Apps.Api.Client\Vendeq.Apps.Api.Client.csproj(31,5): error MSB3073: The command "dotnet "C:\Users\mark\.nuget\packages\nswag.msbuild\13.0.4\build\../tools/NetCore22/dotnet-nswag.dll" run nswag.json /variables:Configuration=Debug,OutputPath=obj\Debug\netcoreapp2.2\" exited with code -1.
2>Done building project "Vendeq.Apps.Api.Client.csproj" -- FAILED.
4>------ Build started: Project: Vendeq.Apps.Functions, Configuration: Debug Any CPU ------
5>------ Build started: Project: Vendeq.Apps.Api.Client.Tests, Configuration: Debug Any CPU ------
5>CSC : error CS0006: Metadata file 'C:\dev\Vendeq.Apps.Api\Vendeq.Apps.Api.Client\bin\Debug\netcoreapp2.2\Vendeq.Apps.Api.Client.dll' could not be found
5>Done building project "Vendeq.Apps.Api.Client.Tests.csproj" -- FAILED.
4>CSC : error CS0006: Metadata file 'C:\dev\Vendeq.Apps.Api\Vendeq.Apps.Api.Client\bin\Debug\netcoreapp2.2\Vendeq.Apps.Api.Client.dll' could not be found
4>Done building project "Vendeq.Apps.Functions.csproj" -- FAILED.
6>------ Build started: Project: Vendeq.Apps.Functions.Tests, Configuration: Debug Any CPU ------
6>CSC : error CS0006: Metadata file 'C:\dev\Vendeq.Apps.Api\Vendeq.Apps.Api.Client\bin\Debug\netcoreapp2.2\Vendeq.Apps.Api.Client.dll' could not be found
6>Done building project "Vendeq.Apps.Functions.Tests.csproj" -- FAILED.
========== Build: 2 succeeded, 4 failed, 0 up-to-date, 0 skipped ==========

```

**Comment by RicoSuter** [comment]
This is not aspnet core, right?
We need to exclude these params then

**Comment by blushingpenguin** [comment]
It's command line nswag on an dotnet core api via NSwag.MSBuild (v13.0.4.0) running the c# generator.

I think that the exception above is dotnet's api explorer blowing up on something tagged [ApiController], picking up the CancellationToken and assuming it should come from the request body, seeing another parameter that comes from the request body and deciding that something is amiss.  That looks like a separate bug in ApiExplorer to me -- I can work around that by suppressing the behaviour that infers binding sources and specifying them manually (services.Configure<ApiBehaviorOptions>(options => options.SuppressInferBindingSourcesForParameters = true);

However even when ApiExplorer is reporting the parameters correctly the CancellationToken token parameter is interpreted as a parameter by nswag.  There doesn't seem to be any way of ignoring the parameter (both [NSwag.Annotations.OpenApiIgnore] and [NSwag.Annotations.SwaggerIgnore] have no effect).  Looking at the code it seems the JSON api generator ignores both parameters of type CancellationToken and that are tagged with ignore attributes so it would seem reasonable for them to do the same -- I'm not sure if nswag isn't doing this since ApiExplorer should be doing the filtering though (that said I can't find a way to get ApiExplorer to ignore parameters -- just whole methods).

**Comment by RicoSuter** [comment]
It’s quite strange that api explorer reports cancellation tokens as params..

**Comment by blushingpenguin** [comment]
I think I've mixed up api explorer (being the ui) and Microsoft.AspNetCore.Mvc.ApplicationModels in what I said above.  I've done quite a bit more digging, and Microsoft.AspNetCore.Mvc.ApplicationModels is the thing that is reporting CancellationToken as an action parameter.  I'm not sure if that behaviour correct or not, but the nswag WebApi generator does contains an OperationProcessor that filters out cancellation tokens explicitly:

NSwag\src\NSwag.Generation.WebApi\Processors\OperationParameterProcessor.cs:
```csharp
        public bool Process(OperationProcessorContext context)
        {
            var httpPath = context.OperationDescription.Path;
            var parameters = context.MethodInfo.GetParameters();

            var position = 1;
            foreach (var contextualParameter in parameters.Select(p => p.ToContextualParameter())
                .Where(p => p.Type != typeof(CancellationToken) &&
                            !p.ContextAttributes.GetAssignableToTypeName("SwaggerIgnoreAttribute", TypeNameStyle.Name).Any() &&
                            !p.ContextAttributes.GetAssignableToTypeName("FromServicesAttribute", TypeNameStyle.Name).Any() &&
                            !p.ContextAttributes.GetAssignableToTypeName("BindNeverAttribute", TypeNameStyle.Name).Any()))
```

the AspNetCore generator doesn't appear to have an equivalent of this which explains why it expands them as structs.  I can work around this by implementing an IActionDescriptorProvider that strips off CancellationToken parameters so nswag never sees them:

```csharp
public class RemoveCancellationTokenActionDescriptorProvider : IActionDescriptorProvider
{
    public int Order => 1;

    public void OnProvidersExecuting(ActionDescriptorProviderContext context)
    {
        foreach (var descriptor in context.Results)
        {
            for (int i = 0; i < descriptor.Parameters.Count; ++i)
            {
                if (descriptor.Parameters[i].ParameterType == typeof(CancellationToken))
                {
                    descriptor.Parameters.RemoveAt(i);
                    --i;
                }
            }
        }
    }

    public void OnProvidersExecuted(ActionDescriptorProviderContext context)
    {
    }
}
...
services.AddTransient<IActionDescriptorProvider, RemoveCancellationTokenActionDescriptorProvider>();
```
However I think it's relatively easy to filter out cancellation tokens in the same way on the aspnet core side (if you think that's correct).  I had a bit of trouble reproducing this in the tests in the nswag codebase though (I was trying to add a test that would fail but couldn't figure out where exactly to put it to tickle this problem) -- if you would be so kind as to point me in the right direction I will happily have a go at implementing that.

I also encountered the issue with the exception above, which is simply a bug in  Microsoft.AspNetCore.Mvc.ApplicationModels.InferParameterBindingInfoConvention.InferBindingSourceForParameter that does not handle CancellationToken.  In other places in the same api  the binding source for CancellationToken is inferred correctly (as BindingSource.Special) 

(I worked around that by copy/pasting InferParameterBindingInfoConvention and ApiBehaviorApplicationModelProvider and adding the relevant check to InferBindingSourceForParameter to return BindingSource.Special for the CancellationToken parameter, which is how it is handled elsewhere).

**Comment by blushingpenguin** [comment]
It appears that this is because I had the compatibility version for Mvc set to 2.0.  With compatibility version set to >= 2.1 then cancellation token parameters are filtered out by the api (and thus both my problems are solved).

https://github.com/aspnet/AspNetCore/issues/13045

Sorry for the noise!
