### ISSUE TITLE
nswag run: 401 Unauthorized response

### ISSUE THREAD

**Issue by ConorLambert** [RicoSuter/NSwag#2352]
Executing `nswag run` from the command line gives me the following response:

```
NSwag NPM CLI
NSwag command line tool for .NET Core NetCore21, toolchain v12.0.20.0 (NJsonSchema v9.13.28.0 (Newtonsoft.Json v11.0.0.0))
Visit http://NSwag.org for more information.
NSwag bin directory: C:\Users\{{username}}\AppData\Roaming\npm\node_modules\nswag\bin\binaries\NetCore21

Executing file 'nswag.json'...
**System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).**
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid1[T0](CallSite site, T0 arg0)
   at NJsonSchema.Infrastructure.DynamicApis.HttpGetAsync(String url)
   at NSwag.SwaggerDocument.FromUrlAsync(String url) in C:\projects\nswag\src\NSwag.Core\SwaggerDocument.cs:line 216
   at NSwag.Commands.OutputCommandBase.ReadSwaggerDocumentAsync(String input) in C:\projects\nswag\src\NSwag.Commands\Commands\OutputCommandBase.cs:line 36
   at NSwag.Commands.SwaggerGeneration.FromSwaggerCommand.RunAsync() in C:\projects\nswag\src\NSwag.Commands\Commands\SwaggerGeneration\FromSwaggerCommand.cs:line 62
   at NSwag.Commands.SwaggerGeneration.FromSwaggerCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\SwaggerGeneration\FromSwaggerCommand.cs:line 53
   at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocumentBase.cs:line 268
   at NSwag.Commands.NSwagDocument.ExecuteAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocument.cs:line 81
   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 77
   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 36
   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 54
```

### Some background:
-Using swagger for .NET Core project (in-house platform)
-**We are using Windows authentication.**
-**When I disable "Windows Authentication" and enable "Anonymous Authentication", nswag run executes as normal.**

Thus the issue is with Windows authentication. 

Could you give me some insight as to a possible solution for this? Thanks in advance!

**Comment by RicoSuter** [comment]
Nswagstudio internally starts the cli which downloads the spec. I think you cannot easily run it with another user from studio. But you can load the spec from disc or maybe run the cli via cmd line directly with another user.

**Comment by adamjones1** [comment]
I'm getting the same issue - it seems like `DynamicApis.HttpGetAsync` in NJsonSchema doesn't pass in the user's credentials in a custom `HttpClientHandler`, so I can't update my NSwag client from a remote URL which is protected by WinAuth. Can I submit a PR to add this?
