### ISSUE TITLE
Exception: System.FormatException: Input string was not in a correct format.

### ISSUE THREAD

**Issue by ghost** [RicoSuter/NSwag#2402]
When I try to generate a C# client (`dotnet nswag run nswag.json`) on MacOS I get the following exception:

```
NSwag command line tool for .NET Core NetCore22, toolchain v13.0.6.0 (NJsonSchema v10.0.23.0 (Newtonsoft.Json v11.0.0.0))
Visit http://NSwag.org for more information.
NSwag bin directory: /Users/andreas.laghamn/.nuget/packages/nswag.consolecore/13.0.6/lib/netcoreapp2.2

Executing file 'nswag.json' with variables ''...
System.InvalidOperationException: Error while rendering Liquid template CSharp/Class:
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(ReadOnlySpan`1 str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(ReadOnlySpan`1 s, NumberStyles style, NumberFormatInfo info)
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.TemplateTag.Initialize(String tagName, String markup, List`1 tokens)
   at DotLiquid.Block.Parse(List`1 tokens)
   at DotLiquid.Template.ParseInternal(String source)
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.LiquidTemplate.Render() ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(ReadOnlySpan`1 str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(ReadOnlySpan`1 s, NumberStyles style, NumberFormatInfo info)
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.TemplateTag.Initialize(String tagName, String markup, List`1 tokens)
   at DotLiquid.Block.Parse(List`1 tokens)
   at DotLiquid.Template.ParseInternal(String source)
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.LiquidTemplate.Render()
   --- End of inner exception stack trace ---
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.LiquidTemplate.Render()
   at NJsonSchema.CodeGeneration.CSharp.CSharpGenerator.GenerateClass(JsonSchema schema, String typeName)
   at NJsonSchema.CodeGeneration.GeneratorBase.GenerateTypes()
   at NJsonSchema.CodeGeneration.CSharp.CSharpGenerator.GenerateTypes()
   at NSwag.CodeGeneration.ClientGeneratorBase`3.GenerateFile(ClientGeneratorOutputType outputType)
   at NSwag.Commands.CodeGeneration.SwaggerToCSharpClientCommand.<RunAsync>b__83_0()
   at NSwag.Commands.CodeGeneration.SwaggerToCSharpClientCommand.RunAsync()
   at NSwag.Commands.CodeGeneration.SwaggerToCSharpClientCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host)
   at NSwag.Commands.NSwagDocument.ExecuteAsync()
   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath)
   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host)
   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args)%
```

The nswag.json is default one generated (with only a changed path to input file and an output path to the generated C# client).
I've tried multiple input files but all get the same exception. Any ideas? I'm able to generate a clients with NSwag Studio on my Windows machine (input files fails on Mac).

**Comment by robertsundstrom** [comment]
Similar, running in macOS:

````
 dotnet "/Users/robert/.nuget/packages/nswag.msbuild/13.2.0/build/../tools/NetCore30/dotnet-nswag.dll" run nswag.json /variables:Configuration=Debug
    NSwag command line tool for .NET Core NetCore30, toolchain v13.2.0.0 (NJsonSchema v10.1.2.0 (Newtonsoft.Json v12.0.0.0))
    Visit http://NSwag.org for more information.
    NSwag bin directory: /Users/robert/.nuget/packages/nswag.msbuild/13.2.0/tools/NetCore30
    
    Executing file 'nswag.json' with variables 'Configuration=Debug'...
    /Users/robert/Library/Caches/VisualStudio/8.0/MSBuild/63633_1/Roslyn/Microsoft.CSharp.Core.targets(59,5): error MSB3883: Unexpected exception:  [/Users/robert/Projects/App1/App1/App1.MobileAppService/App1.MobileAppService.csproj]
    /Users/robert/Library/Caches/VisualStudio/8.0/MSBuild/63633_1/Roslyn/Microsoft.CSharp.Core.targets(59,5): error : System.ComponentModel.Win32Exception (8): Exec format error [/Users/robert/Projects/App1/App1/App1.MobileAppService/App1.MobileAppService.csproj]
    /Users/robert/Library/Caches/VisualStudio/8.0/MSBuild/63633_1/Roslyn/Microsoft.CSharp.Core.targets(59,5): error : at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec) [/Users/robert/Projects/App1/App1/App1.MobileAppService/App1.MobileAppService.csproj]
    /Users/robert/Library/Caches/VisualStudio/8.0/MSBuild/63633_1/Roslyn/Microsoft.CSharp.Core.targets(59,5): error : at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) [/Users/robert/Projects/App1/App1/App1.MobileAppService/App1.MobileAppService.csproj]
    /Users/robert/Library/Caches/VisualStudio/8.0/MSBuild/63633_1/Roslyn/Microsoft.CSharp.Core.targets(59,5): error : at System.Diagnostics.Process.Start() [/Users/robert/Projects/App1/App1/App1.MobileAppService/App1.MobileAppService.csproj]
    /Users/robert/Library/Caches/VisualStudio/8.0/MSBuild/63633_1/Roslyn/Microsoft.CSharp.Core.targets(59,5): error : at Microsoft.Build.Utilities.ToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [/Users/robert/Projects/App1/App1/App1.MobileAppService/App1.MobileAppService.csproj]
    /Users/robert/Library/Caches/VisualStudio/8.0/MSBuild/63633_1/Roslyn/Microsoft.CSharp.Core.targets(59,5): error : at Microsoft.CodeAnalysis.BuildTasks.ManagedCompiler.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [/Users/robert/Projects/App1/App1/App1.MobileAppService/App1.MobileAppService.csproj]
    System.InvalidOperationException: Unable to retrieve project metadata. Ensure it's an MSBuild-based .NET Core project.If you're using custom BaseIntermediateOutputPath or MSBuildProjectExtensionsPath values, Use the --msbuildprojectextensionspath option.
       at NSwag.Commands.Generation.AspNetCore.ProjectMetadata.GetProjectMetadata(String file, String buildExtensionsDir, String framework, String configuration, String runtime, Boolean noBuild, IConsoleHost console) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\ProjectMetadata.cs:line 150
       at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 103
       at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocumentBase.cs:line 279
       at NSwag.Commands.NSwagDocument.ExecuteAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocument.cs:line 81
       at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 86
       at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 32
       at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
       at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
       at NConsole.CommandLineProcessor.Process(String[] args, Object input)
       at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 56
    /Users/robert/Projects/App1/App1/App1.MobileAppService.Client/App1.MobileAppService.Client.csproj(21,5): error MSB3073: The command "dotnet "/Users/robert/.nuget/packages/nswag.
```
