### ISSUE TITLE
nswag.npm fails with dotnet core 3.0

### ISSUE THREAD

**Issue by paillave** [RicoSuter/NSwag#2467]
### Environment
System: ubuntu 19.04
Dotnet version: Core 3.0

### Step to reproduce
```bash
npx nswag new
```
### Error
```
npx: installed 1 in 7.678s
NSwag NPM CLI
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.0.0 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The .NET Core frameworks can be found at:
  - https://aka.ms/dotnet-download
child_process.js:660
    throw err;
    ^

Error: Command failed: dotnet "/home/stephane/.npm/_npx/26051/lib/node_modules/nswag/bin/binaries/NetCore21/dotnet-nswag.dll" new
    at checkExecSyncError (child_process.js:621:11)
    at Object.execSync (child_process.js:657:15)
    at /home/stephane/.npm/_npx/26051/lib/node_modules/nswag/bin/nswag.js:68:11
    at ChildProcess.exithandler (child_process.js:286:7)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  status: 150,
  signal: null,
  output: [ null, null, null ],
  pid: 26114,
  stdout: null,
  stderr: null
}
```

**Comment by RicoSuter** [comment]
I think you need to use `npx nswag new --runtime netcore30`

**Comment by paillave** [comment]
It makes the same :(

```bash
stephane@stephane-VC60:~/Documents/Sources/Blabla.Controllers$ npx nswag new --runtime netcore30
npx: installed 1 in 3.407s
NSwag NPM CLI
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.0.0 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The .NET Core frameworks can be found at:
  - https://aka.ms/dotnet-download
child_process.js:660
    throw err;
    ^

Error: Command failed: dotnet "/home/stephane/.npm/_npx/16744/lib/node_modules/nswag/bin/binaries/NetCore21/dotnet-nswag.dll" new --runtime netcore30
    at checkExecSyncError (child_process.js:621:11)
    at Object.execSync (child_process.js:657:15)
    at /home/stephane/.npm/_npx/16744/lib/node_modules/nswag/bin/nswag.js:68:11
    at ChildProcess.exithandler (child_process.js:286:7)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  status: 150,
  signal: null,
  output: [ null, null, null ],
  pid: 16798,
  stdout: null,
  stderr: null
}
```

**Comment by RicoSuter** [comment]
`nswag new /runtime:NetCore30`?

**Comment by RicoSuter** [comment]
Or `nswag new --core 3.0`

https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Npm/bin/nswag.js#L21

**Comment by paillave** [comment]
```npx nswag new /runtime:NetCore30``` does the trick indeed. Thanks for the help (it should be mentioned in the doc as it lot of people will deal with this issue as dotnet core switched to 3.0)
