### ISSUE TITLE
Format Exception calling a Post method with no body

### ISSUE THREAD

**Issue by harshaperera532** [RicoSuter/NSwag#2477]
I'm working on an api with a post method that has no body. It assigns an item with a particular identifier to the collection of another, so the route alone is sufficient. This works ok when calling it via the Swashbuckle Swagger page. However, calling it through the client generated by NSwag results in a format exception on the following line

request_.Content = new System.Net.Http.StringContent(string.Empty, System.Text.Encoding.UTF8, "text/plain;v=1.0");

If I remove the media type and let the runtime set it it all works ok.

request_.Content = new System.Net.Http.StringContent(string.Empty, System.Text.Encoding.UTF8); 

Is this a problem with the api or should the client specify a different media type in this scenario?

**Comment by RicoSuter** [comment]
What is the exception? How would we fix that?

**Comment by harshaperera532** [comment]
This is the exception that is raised

System.FormatException: The format of value 'text/plain;v=1.0' is invalid.
   at System.Net.Http.Headers.MediaTypeHeaderValue.CheckMediaTypeFormat(String mediaType, String parameterName)
   at System.Net.Http.Headers.MediaTypeHeaderValue..ctor(String mediaType)
   at System.Net.Http.StringContent..ctor(String content, Encoding encoding, String mediaType)

It is raised by the following line in the generated code

request_.Content = new System.Net.Http.StringContent(string.Empty, System.Text.Encoding.UTF8, "text/plain;v=1.0");

Manually editing the line to remove the type fixes the problem and the call works ok.

request_.Content = new System.Net.Http.StringContent(string.Empty, System.Text.Encoding.UTF8);

This is the API method signature on the web end.

      [HttpPost("{id}/role/{role}")]
      [SwaggerResponse(StatusCodes.Status200OK)]
      [SwaggerResponse(StatusCodes.Status400BadRequest, type: typeof(IDictionary<string, string[]>))]
      [SwaggerResponse(StatusCodes.Status500InternalServerError)]
      public async Task<IActionResult> AssignRole(Guid id, string role)

As stated earlier this particular post method does not require a body.

**Comment by RicoSuter** [comment]
Ok, but isnt it a "bug" in the Swagger/Open API spec then? i.e. it should not specify it as "text/plain;v=1.0" which is not allowed?

**Comment by devinlyons** [comment]
I'm having the same issue. I have a POST endpoint that does not take a body. My swagger specifies no `consume` property yet the client was generated to expect json. There is a `produces` property that specifies json but that should affect anything.

Here is the offending line:

```csharp
request_.Content = new System.Net.Http.StringContent(string.Empty, System.Text.Encoding.UTF8, "application/json;charset=utf-8");
```

**Comment by soroshsabz** [comment]
ITNOA

Any update?

**Comment by soroshsabz** [comment]
@Sepand96 please answer @RicoSuter below question

> What is the exception? How would we fix that?

**Comment by 0bethany0** [comment]
We are experiencing the same issue with a POST with no body.  Any update here?

**Comment by 0bethany0** [comment]
> We are experiencing the same issue with a POST with no body. Any update here?

This is a workaround we are using in our generating code:
`.SwaggerDocument(o =>
{
	o.DocumentSettings = s =>
	{
		s.ApiVersion(new(1.0, "beta"));
		s.SchemaSettings.SchemaType = NJsonSchema.SchemaType.OpenApi3;
		s.PostProcess = d =>
		{

			// this forces the code generators to use this empty body, otherwise it will try to generate a body
			// from an empty string which causes serialization errors.
			if (bool.TryParse(context.Configuration["WHEN.YOU.ARE.GENERATING.SDK"], out var generate) && generate)
			{
				var operation = d.Operations.Where(o => o.Method.ToLower() == "post" && o.Operation.RequestBody == null).ToList();
				foreach (var o in operation)
				{
					o.Operation.RequestBody = new NSwag.OpenApiRequestBody();
				}
			}
		};
	};
});`
