### ISSUE TITLE
nswag run version not working throwing "FileNotFoundException"

### ISSUE THREAD

**Issue by Bnjmn83** [RicoSuter/NSwag#2492]
The command 
`nswag run version /runtime:NetCore22`
produces the following output:

```
NSwag NPM CLI
NSwag command line tool for .NET Core NetCore21, toolchain v13.1.3.0 (NJsonSchema v10.0.27.0 (Newtonsoft.Json v11.0.0.0))
Visit http://NSwag.org for more information.
NSwag bin directory: C:\Users\user\AppData\Roaming\npm\node_modules\nswag\bin\binaries\NetCore21

Executing file 'version' with variables ''...
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not find file 'C:\projects\cp\Abus\Notifications\notifications-api\ABUS.Cloud.Notifications.Adapters\MailTemplate\Proxy\vers
ion'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path, Encoding encoding)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at NJsonSchema.Infrastructure.DynamicApis.FileReadAllText(String filePath)
   at NSwag.Commands.NSwagDocumentBase.<>c__DisplayClass35_0`1.<<LoadAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at NSwag.Commands.NSwagDocument.LoadWithTransformationsAsync(String filePath, String variables) in C:\projects\nswag\src\NSwag.Commands\NSwagDocument.cs:line 69
   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 63
   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 32
   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 56child_process.js:644
    throw err;
    ^

Error: Command failed: dotnet "C:\Users\benjamin.moll\AppData\Roaming\npm\node_modules\nswag\bin/binaries/NetCore21/dotnet-nswag.dll" run version /runtime:NetCore21
    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at c.exec (C:\Users\benjamin.moll\AppData\Roaming\npm\node_modules\nswag\bin\nswag.js:56:19)
    at ChildProcess.exithandler (child_process.js:267:7)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
```

Tried it on Win10 natively and also within a docker container using the base image _mcr.microsoft.com/dotnet/core/sdk:2.2_

Weirdest part is that when I do
`nswag version /runtime:NetCore22`
it seems to work fine but [here](https://www.npmjs.com/package/nswag#change-runtime) it clearly states to use run as argument as well...

**Comment by RicoSuter** [comment]
If you fo “nswag run version” it tries to run the config in the “version” file which probably is not what you want to do

**Comment by Bnjmn83** [comment]
I know, the command _nswag run version /runtime:NetCore22_ is taken from [here](https://www.npmjs.com/package/nswag#change-runtime)

**Comment by Cassidie** [comment]
Any updates on this? We're having the same issue.

**Comment by RicoSuter** [comment]
Its

    nswag version

**Comment by Cassidie** [comment]
I ran `nswag version /runtime:NetCore31` and got the following output:
```
NSwag NPM CLI
NSwag command line tool for .NET Core NetCore31, toolchain v13.2.0.0 (NJsonSchema v10.1.2.0 (Newtonsoft.Json v12.0.0.0))
Visit http://NSwag.org for more information.
NSwag bin directory: C:\Users\charrington\AppData\Roaming\npm\node_modules\nswag\bin\binaries\NetCore31

NSwag version: 13.2.0.0
NJsonSchema version: 10.1.2.0 (Newtonsoft.Json v12.0.0.0)

Duration: 00:00:00.0049246
```

I then ran `nswag version` to check the version, and it said the command line tool is NetCore21 again. It's like it didn't really change it:
```
NSwag NPM CLI
NSwag command line tool for .NET Core NetCore21, toolchain v13.2.0.0 (NJsonSchema v10.1.2.0 (Newtonsoft.Json v11.0.0.0))
Visit http://NSwag.org for more information.
NSwag bin directory: C:\Users\charrington\AppData\Roaming\npm\node_modules\nswag\bin\binaries\NetCore21

NSwag version: 13.2.0.0
NJsonSchema version: 10.1.2.0 (Newtonsoft.Json v11.0.0.0)

Duration: 00:00:00.0059748
```

I think I'm still missing something here.

**Comment by RicoSuter** [comment]
What do you want to accomplish?

**Comment by Cassidie** [comment]
I want to be able to use nswag with Netcore31.

**Comment by Cassidie** [comment]
Ok so I understand my confusion. The docs say `nswag run version /runtime:NetCore31` in order to run a specific version. But `version` here represents a file name, which makes no sense at all, b/c the file name would be nswag.json or *.nswag. I was thinking the word `version` was a flag to change the version and the `/runtime:NetCore31` was telling it what version you wanted to change it to, but the docs are misleading.

Therefore, you can't actually CHANGE the version. You always have to specify which version you want to run the nswag.json or *.nswag file in; and of course the runtime has to match the runtime setting specified in that file.

Finally, the proper way to run a file with a different runtime is:
`nswag run /runtime:NetCore31` // runs nswag.json and any *.nswag files

or 
`nswag run nswag.json /runtime:NetCore31` // runs just nswag.json file

**Comment by RicoSuter** [comment]
Thanks for the update, can you fix the npm info file?

**Comment by Cassidie** [comment]
Sorry, I'm confused. Are you wanting me to open a PR and update an npm file? You'll have to point me to where the file is.

**Comment by chrisands** [comment]
Here's where NPM package code
https://github.com/RicoSuter/NSwag/tree/master/src/NSwag.Npm

**Comment by RicoSuter** [comment]
Update npm readme
