### ISSUE TITLE
System.Reflection.ReflectionTypeLoadException using nswag on ASPNetCore-Dll referencing EF2.2.6

### ISSUE THREAD

**Issue by maxberghammer** [RicoSuter/NSwag#2518]
Hi!
I have an ASPNETCore-Project with some controllers in it. The project itsself uses EntityFrameworkCore v2.2.6. If I try to nswag aspnetcore2swagger on my built DLL, I get the following stacktrace:
```
1>NSwag bin directory: D:\Users\mbe.WHITEDUCK\.nuget\packages\nswag.msbuild\13.1.3\tools\NetCore22
1>System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
1>Method 'BuildModel' in type 'Orca.Ade.CatalogStatusApi.infrastructure.migrations.CatalogStatusContextModelSnapshot' from assembly 'Orca.Ade.CatalogStatusApi, Version=4.0.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
1>   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
1>   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
1>   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
1>   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
1>   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetControllerTypes()
1>   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.BuildModel()
1>   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetDescriptors()
1>   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
1>   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.UpdateCollection()
1>   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.Initialize()
1>   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.get_ActionDescriptors()
1>   at Microsoft.AspNetCore.Mvc.ApiExplorer.ApiDescriptionGroupCollectionProvider.get_ApiDescriptionGroups()
1>   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateAsync(Object serviceProvider) in C:\projects\nswag\src\NSwag.Generation.AspNetCore\AspNetCoreOpenApiDocumentGenerator.cs:line 50
1>   at NSwag.AspNetCore.OpenApiDocumentProvider.GenerateAsync(String documentName)
1>   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.GenerateDocumentWithDocumentProviderAsync(IServiceProvider serviceProvider) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 287
1>   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.GenerateDocumentAsync(AssemblyLoader assemblyLoader, IServiceProvider serviceProvider, String currentWorkingDirectory) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 276
1>   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.RunIsolatedAsync(AssemblyLoader assemblyLoader) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 312
1>   at NSwag.Commands.IsolatedCommandBase`1.IsolatedCommandAssemblyLoader`1.Run(String commandType, String commandData, String[] assemblyPaths, String[] referencePaths) in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedCommandBase.cs:line 71
1>   at NSwag.Commands.IsolatedCommandBase`1.<>c__DisplayClass17_0.<RunIsolatedAsync>b__0() in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedCommandBase.cs:line 61
1>   at System.Threading.Tasks.Task`1.InnerInvoke()
1>   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
1>--- End of stack trace from previous location where exception was thrown ---
1>   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
1>--- End of stack trace from previous location where exception was thrown ---
1>   at NSwag.Commands.IsolatedCommandBase`1.RunIsolatedAsync(String configurationFile)
1>   at NSwag.Commands.IsolatedSwaggerOutputCommandBase`1.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedSwaggerOutputCommandBase.cs:line 47
1>   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 95
1>   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
1>   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
1>   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
1>   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 56
1>System.TypeLoadException: Method 'BuildModel' in type 'Orca.Ade.CatalogStatusApi.infrastructure.migrations.CatalogStatusContextModelSnapshot' from assembly 'Orca.Ade.CatalogStatusApi, Version=4.0.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```
The problem seems to be, that my class CatalogStatusContextModelSnapshot implements an abstract method from an EFCore-BaseClass having a parameter of type ModelBuilder, which itsself is an EFCore-Class, too. Now, what I found out: I use EFCore 2.2.6 and nswag uses EFCore 2.2.4 - at least the EFCore-assembly having this version resides in the nuget-folder of the nswag.msbuild-package. If I downgrade my project to EFCore 2.2.4, everything works like a charm...but...I don't want to do that, really ;) What can be done else? I don't use nswag-studio. Only the nswag.-msbuild-package and nswag.aspnetcore (both v13.1.3).

thx in advance,

Max

**Comment by maxberghammer** [comment]
No hint on this? Is nswag not supposed to be used with projects using EF>2.2.4? I tried all the things you describe here to resolve ReflectionTypeLoadExceptions but none of them didn't work :/

**Comment by RicoSuter** [comment]
I use NSwag with EF without problems... so somehow you need to avoid loading the migrations when the client is generated...
