### ISSUE TITLE
Client code generation in NSwagStudio fails with NullReferenceException

### ISSUE THREAD

**Issue by BlackGad** [RicoSuter/NSwag#2530]
If specification contains response with defined content which has example but not have schema element code generation fails with an error
```
System.InvalidOperationException: Error while rendering Liquid template CSharp/Client.Class: 
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.

Runtime: NetCore20
   at NSwag.CodeGeneration.Models.OperationModelBase`2.get_UnwrappedResultType() in C:\projects\nswag\src\NSwag.CodeGeneration\Models\OperationModelBase.cs:line 120
   at NSwag.CodeGeneration.CSharp.Models.CSharpOperationModel.get_ResultType() in C:\projects\nswag\src\NSwag.CodeGeneration.CSharp\Models\CSharpOperationModel.cs:line 131
   --- End of inner exception stack trace ---
...
```

Here is sample of invalid configuration for studio
```YAML
openapi: 3.0.1
info:
  description: >-
    Test API's
  version: 1.1.2
  title: Test API
   
paths:
  /testPath:
    get:
      operationId: testId
      description: "42"
      responses:
        '200':
          description: Returns some object
          content:
            application/json:
                example: {}
```

And here is valid configuration (with added schema property)
```YAML
openapi: 3.0.1
info:
  description: >-
    Test API's
  version: 1.1.2
  title: Test API
   
paths:
  /testPath:
    get:
      operationId: testId
      description: "42"
      responses:
        '200':
          description: Returns some object
          content:
            application/json:
                schema:
                    type: object
                example: {}
```

**Comment by rpbeukes** [comment]
I also investigated this and 

[src/NSwag.CodeGeneration.CSharp/Models/CSharpOperationModel.cs](https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.CodeGeneration.CSharp/Models/CSharpOperationModel.cs)

threw `Object reference not set...` because  `Item` in ` schema.Item.IsBinary` is null. 

```csharp
...
if (schema.Type == JsonObjectType.Array && schema.Item.IsBinary)
{
    return "System.Collections.Generic.IEnumerable<FileParameter>";
}
...
```

My suggestion to help it tick along.

```csharp
...
if (schema.Type == JsonObjectType.Array && (schema.Item?.IsBinary ?? false))
{
    return "System.Collections.Generic.IEnumerable<FileParameter>";
}
...
```

I've tested it and the app does not blow up anymore - yes!
It also passed all the tests, also yes!

I still have to test if the output generated will work properly, but I guess it would as the actual parameter which failed for me is generated like this:
`System.Collections.Generic.IEnumerable<object> status`
and what it should be is
`System.Collections.Generic.IEnumerable<string> status `

```csharp
System.Threading.Tasks.Task<SomeResponse> GetYourFavMethodAsync(int? start = null, System.Collections.Generic.IEnumerable<object> status = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
```
