### ISSUE TITLE
Client generation in NSwagStudio exceptions

### ISSUE THREAD

**Issue by tndata** [RicoSuter/NSwag#2545]
When I try to generate a C# .NET Core3 client using the NSwagStudio (13.1.6.0) the following OpenAPI document generates exception

https://leksaker.starweb.se/api/v2/openapi.json

I have imported it into SwaggerHub without any errors.

I have also saved it as Yaml here: http://download.edument.se/openapi.yaml  (from swaggerhub and http://online.swagger.io/)

Any hint on how I can debug this?

The exception I get is:

System.InvalidOperationException: Error while rendering Liquid template CSharp/Client.Class: 
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Sequence contains more than one matching element

**Comment by haiduc32** [comment]
Same problem here. Traced the source of the exception to referencing the same response in multiple places, in your case that's: 400":{"$ref":"#\/components\/responses\/BadRequest"},
BadReqeuest is referenced multiple times. 
Doesn't make any sense why it behaves that way. Waiting for someone to look at this issue.

**Comment by RicoSuter** [comment]
Do we have a stacktrace or something?

**Comment by haiduc32** [comment]
Stack trace from running NSwagStudio (latest version) with the document provided in the first post:

System.InvalidOperationException: Error while rendering Liquid template CSharp/Client.Class: 
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Sequence contains more than one matching element

Runtime: Default
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at NSwag.OpenApiResponse.IsBinary(OpenApiOperation operation)
   at NSwag.CodeGeneration.Models.ResponseModelBase.get_CheckChunkedStatusCode()
   --- End of inner exception stack trace ---
   at DotLiquid.Context.HandleError(Exception ex)
   at DotLiquid.Block.RenderAll(List`1 list, Context context, TextWriter result)
   at DotLiquid.Document.Render(Context context, TextWriter result)
   at DotLiquid.Template.RenderInternal(TextWriter result, RenderParameters parameters)
   at DotLiquid.Template.Render(TextWriter writer, RenderParameters parameters)
   at DotLiquid.Template.Render(RenderParameters parameters)
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.LiquidTemplate.Render() ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at NSwag.OpenApiResponse.IsBinary(OpenApiOperation operation)
   at NSwag.CodeGeneration.Models.ResponseModelBase.get_CheckChunkedStatusCode()
   --- End of inner exception stack trace ---
   at DotLiquid.Context.HandleError(Exception ex)
   at DotLiquid.Block.RenderAll(List`1 list, Context context, TextWriter result)
   at DotLiquid.Document.Render(Context context, TextWriter result)
   at DotLiquid.Template.RenderInternal(TextWriter result, RenderParameters parameters)
   at DotLiquid.Template.Render(TextWriter writer, RenderParameters parameters)
   at DotLiquid.Template.Render(RenderParameters parameters)
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.LiquidTemplate.Render()
   --- End of inner exception stack trace ---
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.LiquidTemplate.Render()
   at NSwag.CodeGeneration.CSharp.CSharpClientGenerator.<GenerateClientTypes>d__8.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at NSwag.CodeGeneration.ClientGeneratorBase`3.GenerateAllClientTypes()
   at NSwag.CodeGeneration.ClientGeneratorBase`3.GenerateFile(ClientGeneratorOutputType outputType)
   at NSwag.Commands.CodeGeneration.SwaggerToCSharpClientCommand.<<RunAsync>b__83_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.CodeGeneration.SwaggerToCSharpClientCommand.<RunAsync>d__83.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.CodeGeneration.SwaggerToCSharpClientCommand.<RunAsync>d__82.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.NSwagDocument.<ExecuteAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.Document.ExecuteDocumentCommand.<ExecuteDocumentAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.Document.ExecuteDocumentCommand.<RunAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NConsole.CommandLineProcessor.<ProcessSingleAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NConsole.CommandLineProcessor.<ProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args)

**Comment by i-sinister** [comment]
NSwagStudio 13.2.2.0 fails to generate client for following spec:
```yaml
openapi: '3.0.0'
paths:
  /bugs:
    get:
      summary: Returns list on NSwagStudio bugs
      tags:
        - Algorithm
      responses:
        '200':
          $ref: '#/components/responses/NSwagStudioBug'
        '400':
          $ref: '#/components/responses/NSwagStudioBug'
components:
  responses:
    NSwagStudioBug:
      description: List of NSwagStudio bugs
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/NSwagStudioBug'
  schemas:
    NSwagStudioBug:
      description: Describes NSwagStudio bug
      type: object
      required:
        - description
      properties:
        description:
          description: Bug description
          type: string
      example:
        description: https://github.com/RicoSuter/NSwag/issues/2545
```
Error as in previous comment. The reason is using the same multiple response for different codes.

**Comment by haiduc32** [comment]
I've hit this bug again today (forgot about it) and I can see I already commented.. 

Is anyone working on it, or can I take a shot at fixing it?

**Comment by jeremyVignelles** [comment]
If there's no open PR, you can assume nobody is working on it.
Thanks 👍

**Comment by haiduc32** [comment]
Modified the failing example to make it work (making it a bit more obvious where the problem is):
```
openapi: '3.0.0'
paths:
  /bugs:
    get:
      summary: Returns list on NSwagStudio bugs
      responses:
        '200':
          $ref: '#/components/responses/NSwagStudioBug'
        '400':
          $ref: '#/components/responses/NSwagStudioBug1'
components:
  responses:
    NSwagStudioBug:
      description: List of NSwagStudio bugs
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/NSwagStudioBug'
    NSwagStudioBug1:
      description: List of NSwagStudio bugs
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/NSwagStudioBug'
  schemas:
    NSwagStudioBug:
      description: Describes NSwagStudio bug
      type: object
      required:
        - description
      properties:
        description:
          description: Bug description
          type: string
      example:
        description: https://github.com/RicoSuter/NSwag/issues/2545
```
Will look into the code later.

**Comment by RicoSuter** [comment]
![image](https://user-images.githubusercontent.com/2603405/102371578-9caf4380-3fbe-11eb-9632-5ed21c4355be.png)

So the same response object is in resolved multiple times in the ActualResponses?

**Comment by haiduc32** [comment]
Apologies for the late reply.
Just for the record - yes, that is correct, Operation.ActualResponses will contain one item for each response (different http codes) but with the same r.Value if your responses have the same "$ref". Which is correct (IMHO). So the solution was to change the code to use the "Any" Linq method, as to the best of my understanding this bit of code just checks that the current response is not 204. I changed it to check that there is at least one response that is not 204, so that the response can be binary.
