### ISSUE TITLE
Error throws when multiple route is define on controller

### ISSUE THREAD

**Issue by prachh** [RicoSuter/NSwag#2547]
I'm currently working with .Net Core WebAPI, there is one controller which having a multiple route like
[Route("api/cache")]
[Route("datacatalog/cache")]

When I try to create a Swagger spec. document from the NSwag console it gives me an error saying:
System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at NSwag.Generation.WebApi.WebApiOpenApiDocumentGenerator.GetRouteAttribute(Type type) in C:\App\NSwag\src\NSwag.Generation.WebApi\WebApiOpenApiDocumentGenerator.cs:line 433

When I changed the code from SingleOrDefault to FirstOrDefault it is working fine, it takes the first route from the code and generates a swagger doc.
i.e. It takes [Route("api/cache")]

Can you please validate.

If you have any suggestions to fix the above, please let me know.

**Comment by RicoSuter** [comment]
Why are you using `NSwag.Generation.WebApi.WebApiOpenApiDocumentGenerator` for asp.net CORE?

**Comment by guffy1234** [comment]
> Why are you using `NSwag.Generation.WebApi.WebApiOpenApiDocumentGenerator` for asp.net CORE?

there could be a case when you need to check contract of an application without run it. in other words load the assembly, get controllers and generate a document.

**Comment by prachh** [comment]
> Why are you using `NSwag.Generation.WebApi.WebApiOpenApiDocumentGenerator` for asp.net CORE?

I included the swagger.json generation step on build process.
And as per the documentation I ran nswag-dll with the webapi configuration as mentioned at https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Sample.NetCoreAngular/nswag.json

And its execute the above mentioned code.

**Comment by prachh** [comment]
> > Why are you using `NSwag.Generation.WebApi.WebApiOpenApiDocumentGenerator` for asp.net CORE?
> 
> there could be a case when you need to check contract of an application without run it. in other words load the assembly, get controllers and generate a document.

Agreed, I wants the same
