### ISSUE TITLE
NSwag Response Headers

### ISSUE THREAD

**Issue by mirsaeedi** [RicoSuter/NSwag#2574]
I tried to use OpenApiResponse.Headers to define the response headers but it seems this functionality does not work as expected. 

Actual:

```
responses:
        '200':
          description: OK
          headers:
            200: {
                "type": "integer",
                "description": "Request limit per hour"
              }
``` 
Expected:

```
responses:
        '200':
          description: OK
          headers:
            X-RateLimit-Limit:
              schema:
                type: integer
              description: Request limit per hour.
``` 

On top of that, NSwag has the following limitations in regard to response headers:

1. Cannot set header name
2. Cannot set header description

**Comment by RicoSuter** [comment]
So nswag does not expose the model required by openapi?

**Comment by mirsaeedi** [comment]
No, it doesn't. If you accept PR's, I'll submit a fix.

**Comment by RicoSuter** [comment]
Yes please. Not sure if we are talking about the same thing

**Comment by cjlotz** [comment]
Any further progress on this issue?

**Comment by cjlotz** [comment]
I think I figured it out.  Adding the response header as an `OpenApiParameter` seems to generate the correct schema for a response header: 

```c#
            var header = new OpenApiParameter
                            {
                                Schema = new JsonSchema { Type = JsonObjectType.Integer },
                                Example = 100,
                                Description = "Id of the resource created"
                            };         
            context.Document.Components.Headers.Add("ResourceId", header);
```

**Comment by cjlotz** [comment]
Another question perhaps, given that I've added it to the shared Components headers, how do I add a reference to it when adding it to the individual `OpenApiResponse.Headers` collections for the different operations?

**Comment by RicoSuter** [comment]
new JsonSchema { Reference = header }

header is the autom. resolved to a path into the components

**Comment by cjlotz** [comment]
Thanks @RicoSuter - following the approach I get this exception when calling `ToJson` on the `OpenApiDocument`  

```
 Could not find the JSON path of a referenced schema: Manually referenced schemas must be added to the 'Definitions' of a parent schema.
  at at NJsonSchema.JsonPathUtilities.GetJsonPaths(Object rootObject, IEnumerable`1 searchedObjects, IContractResolver contractResolver)
  at at NJsonSchema.JsonSchemaReferenceUtilities.UpdateSchemaReferencePaths(Object rootObject, Boolean removeExternalReferences, IContractResolver contractResolver)
  at at NJsonSchema.Infrastructure.JsonSchemaSerialization.ToJson(Object obj, SchemaType schemaType, IContractResolver contractResolver, Formatting formatting)
  at at NSwag.OpenApiDocument.ToJson(SchemaType schemaType, Formatting formatting)
  at at NSwag.OpenApiDocument.ToJson(SchemaType schemaType)
  at at NSwag.OpenApiDocument.ToJson()
  at Pragma.OnKey.Core.Specs.Spec.ToJson() in C:\PragmaDev\OKSource\Git\onkey-plus-server\src\Pragma.OnKey.Infrastructure\Core\Specs\Entities\Spec.cs:43
  at Pragma.OnKey.Core.Specs.Spec.ToContent() in C:\PragmaDev\OKSource\Git\onkey-plus-server\src\Pragma.OnKey.Infrastructure\Core\Specs\Entities\Spec.cs:38
  at Pragma.OnKey.Http.Formatters.SpecOutputBuilder.Execute(Object obj, IReadOnlyNotification notification) in C:\PragmaDev\OKSource\Git\onkey-plus-server\src\Pragma.OnKey.Infrastructure\Http\Formatters\SpecOutputBuilder.cs:16
  at Pragma.OnKey.Http.Formatters.OnKeyOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding) in C:\PragmaDev\OKSource\Git\onkey-plus-server\src\Pragma.OnKey.Infrastructure\Http\Formatters\OnKeyOutputFormatter.cs:50
```

**Comment by RicoSuter** [comment]
You also need to add the header schema to the "components/schemas" or "schemas".

**Comment by davidkeaveny** [comment]
Thanks @cjlotz, your solution fixed my issue.
