### ISSUE TITLE
BadImageFormatException when using NSwag CLI

### ISSUE THREAD

**Issue by petarpetrovt** [RicoSuter/NSwag#2589]
Running NSwag CLI for dotnet core 3.1 ASP.NET project outputs `BadImageFormatException`.

* Example project - [example-nswag](https://github.com/petarpetrovt/example-nswag)

* Stack trace
```
System.BadImageFormatException: Bad IL format.
1>   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
1>   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
1>   at NSwag.Commands.IsolatedSwaggerOutputCommandBase`1.<>c__DisplayClass10_0.<LoadAssemblies>b__0(String path) in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedSwaggerOutputCommandBase.cs:line 61
1>   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
1>   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
1>   at NSwag.Commands.IsolatedSwaggerOutputCommandBase`1.LoadAssemblies(IEnumerable`1 assemblyPaths, AssemblyLoader assemblyLoader) in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedSwaggerOutputCommandBase.cs:line 60
1>   at NSwag.Commands.Generation.WebApi.WebApiToSwaggerCommand.GetControllerTypesAsync(IEnumerable`1 controllerNames, AssemblyLoader assemblyLoader)
1>   at NSwag.Commands.Generation.WebApi.WebApiToSwaggerCommand.RunIsolatedAsync(AssemblyLoader assemblyLoader) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\WebApi\WebApiToOpenApiCommand.cs:line 92
1>   at NSwag.Commands.IsolatedCommandBase`1.IsolatedCommandAssemblyLoader`1.Run(String commandType, String commandData, String[] assemblyPaths, String[] referencePaths) in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedCommandBase.cs:line 76
1>   at NSwag.Commands.IsolatedCommandBase`1.<>c__DisplayClass17_0.<RunIsolatedAsync>b__0() in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedCommandBase.cs:line 61
1>   at System.Threading.Tasks.Task`1.InnerInvoke()
1>   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
1>   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
1>--- End of stack trace from previous location where exception was thrown ---
1>   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
1>   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
1>--- End of stack trace from previous location where exception was thrown ---
1>   at NSwag.Commands.IsolatedCommandBase`1.RunIsolatedAsync(String configurationFile) in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedCommandBase.cs:line 61
1>   at NSwag.Commands.IsolatedSwaggerOutputCommandBase`1.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedSwaggerOutputCommandBase.cs:line 47
1>   at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocumentBase.cs:line 279
1>   at NSwag.Commands.NSwagDocument.ExecuteAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocument.cs:line 81
1>   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 86
1>   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 32
1>   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
1>   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
1>   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
1>   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 56
```

**Comment by RicoSuter** [comment]
For asp.net CORE you should not use WebApiToSwaggerCommand (deprecated) - use the AspNetCoreToSwaggerCommand instead
