### ISSUE TITLE
Cannot generate openapi on mac

### ISSUE THREAD

**Issue by onionhammer** [RicoSuter/NSwag#2714]
I use this in my csproj file which works beautifully to re-generate typescript client on Windows, but when I run the same msbuild on my mac; both with dotnet core 3.1, I get an error

```xml  
  <Target Name="NSwag" AfterTargets="Build" Condition="'$(Configuration)' != 'Release'">
    <Exec EnvironmentVariables="ASPNETCORE_ENVIRONMENT=Development" Command="$(NSwagExe_Core31) aspnetcore2openapi /assembly:$(TargetDir)$(AssemblyName).dll /output:$(OutDir)openapi.json" />
    <Exec Command="$(NSwagExe_Core31) openapi2tsclient /input:$(OutDir)openapi.json /name:API /ClientBaseClass:RootApi /TypeStyle:Interface /UseGetBaseUrlMethod:true /ExtensionCode:ClientApp/src/api.extensions.d.ts /output:ClientApp/src/api.generated.ts" />
  </Target>
```

Error:

```
  System.MissingMethodException: Method not found: 'Microsoft.Extensions.Configuration.IConfigurationBuilder Microsoft.Extensions.Configuration.JsonConfigurationExtensions.AddJsonFile(Microsoft.Extensions.Configuration.IConfigurationBuilder, System.String, Boolean, Boolean)'.
     at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
     at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
     at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider provider, Type type)
     at Microsoft.AspNetCore.Hosting.StartupLoader.LoadMethods(IServiceProvider hostingServiceProvider, Type startupType, String environmentName)
     at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.<>c__DisplayClass3_0.<UseStartup>b__1(IServiceProvider sp)
     at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context
```

**Comment by RicoSuter** [comment]
Try to use /project instead of /assembly

**Comment by onionhammer** [comment]
^ This works, thanks!

Leaving this open since it's still a bug, but switching to /project preferable in most cases

**Comment by onionhammer** [comment]
@marbletravis 

```xml
  <Target Name="NSwag" AfterTargets="Build" Condition="'$(Configuration)' != 'Release'">
    <Message Text="$(NSwagExe_Core31)" />
    <Exec EnvironmentVariables="GenerateNSwag=1" Command="$(NSwagExe_Core31) aspnetcore2openapi /AspNetCoreEnvironment:Development /noBuild:true /project:. /output:$(OutDir)openapi.json" />
    <Exec Command="$(NSwagExe_Core31) openapi2tsclient /input:$(OutDir)openapi.json /TemplateDirectory:./Templates /GenerateOptionalParameters:true /TypeStyle:Interface /output:ClientApp/src/api.generated.ts" />
  </Target>
```

**Comment by marbletravis** [comment]
Something that I discovered in my testing, which I am not 100% sure is right, but seems to work for now.

The only things that need to be called in startup for nswag to work are 

`
services.AddMvc()...
services.AddSwaggerDocument();
`
I set an environment variable on exec as follows:
`
<Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Copy SourceFiles="@(Reference)" DestinationFolder="$(OutDir)References" />
    <Exec EnvironmentVariables="ASPNETCORE_ENVIRONMENT=Development;NSWAG=Build" Command="$(NSwagExe_Core31) run nswag.json /variables:Configuration=$(Configuration),TargetFramework=$(TargetFrameworkVersion),Runtime=$(Runtime)" />
    <RemoveDir Directories="$(OutDir)References" />
  </Target>
`

and then in Startup constructor 
`
public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
            IsNswag = !string.IsNullOrWhiteSpace(Environment.GetEnvironmentVariable("NSWAG"));
        }
`

ConfigureServices
`
public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().AddJsonOptions(options =>
            {
                options.JsonSerializerOptions.PropertyNameCaseInsensitive = true;
                options.JsonSerializerOptions.PropertyNamingPolicy = null;
            });

            if (IsNswag)
            {
                services.AddSwaggerDocument();
                return;
            }
`

and Configure
`
public void Configure(IApplicationBuilder app, IHostEnvironment env)
        {
            if (IsNswag)
            {
                return;
            }
`

This made the difference in build time between project and assembly negligible.
