### ISSUE TITLE
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Configuration.IConfiguration' while attempting to activate 'Startup'

### ISSUE THREAD

**Issue by muradkhateeb78** [RicoSuter/NSwag#2963]
Hi NSwag team,

Before this issue is marked as duplicate, I want to tell that I have already gone through [2641](https://github.com/RicoSuter/NSwag/issues/2641) and [1920](https://github.com/RicoSuter/NSwag/issues/1920) and nothing mentioned there worked for me.
Also **please note** that I had to add all of the following files which is why the question looks so big in itself. Sorry about that.

I am using NSwagStudio to generate the client for my API.
NSwag version: 13.6.2.0
Runtime: .Net Core 3.1

I tried both methods i.e using the assembly and using the .csproj but both didn't work.

Here are the project details.

**.csproj**
`<PropertyGroup>
        <TargetFramework>netcoreapp3.1</TargetFramework>
        <AssemblyName>MyProject.Comm.Api</AssemblyName>
        <RootNamespace>MyProject.Comm.Api</RootNamespace>
        <LangVersion>latest</LangVersion>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <ServerGarbageCollection>false</ServerGarbageCollection>
        <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
        <PreserveCompilationContext>true</PreserveCompilationContext>
        <MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>
        <StartupObject>MyProject.Comm.Api.Program</StartupObject>
    </PropertyGroup>`

**.NSwag**
```
{
  "runtime": "NetCore31",
  "defaultVariables": null,
  "documentGenerator": {
    "aspNetCoreToOpenApi": {
      "project": "",
      "msBuildProjectExtensionsPath": null,
      "configuration": null,
      "runtime": null,
      "targetFramework": null,
      "noBuild": true,
      "verbose": false,
      "workingDirectory": null,
      "requireParametersWithoutDefault": false,
      "apiGroupNames": null,
      "defaultPropertyNameHandling": "Default",
      "defaultReferenceTypeNullHandling": "Null",
      "defaultDictionaryValueReferenceTypeNullHandling": "NotNull",
      "defaultResponseReferenceTypeNullHandling": "NotNull",
      "defaultEnumHandling": "Integer",
      "flattenInheritanceHierarchy": false,
      "generateKnownTypes": true,
      "generateEnumMappingDescription": false,
      "generateXmlObjects": false,
      "generateAbstractProperties": false,
      "generateAbstractSchemas": true,
      "ignoreObsoleteProperties": false,
      "allowReferencesWithProperties": false,
      "excludedTypeNames": [],
      "serviceHost": null,
      "serviceBasePath": null,
      "serviceSchemes": [],
      "infoTitle": "My Title",
      "infoDescription": null,
      "infoVersion": "1.0.0",
      "documentTemplate": null,
      "documentProcessorTypes": [],
      "operationProcessorTypes": [],
      "typeNameGeneratorType": null,
      "schemaNameGeneratorType": null,
      "contractResolverType": null,
      "serializerSettingsType": null,
      "useDocumentProvider": false,
      "documentName": "v1",
      "aspNetCoreEnvironment": null,
      "createWebHostBuilderMethod": null,
      "startupType": null,
      "allowNullableBodyParameters": true,
      "output": null,
      "outputType": "Swagger2",
      "newLineBehavior": "Auto",
      "assemblyPaths": [
        "../bin/Debug/netcoreapp3.1/MyProject.Comm.Api.dll"
      ],
      "assemblyConfig": null,
      "referencePaths": [],
      "useNuGetCache": false
    }
  },
  "codeGenerators": {
    "openApiToCSharpClient": {
      "clientBaseClass": null,
      "configurationClass": null,
      "generateClientClasses": true,
      "generateClientInterfaces": true,
      "clientBaseInterface": null,
      "injectHttpClient": true,
      "disposeHttpClient": true,
      "protectedMethods": [],
      "generateExceptionClasses": true,
      "exceptionClass": "ApiException",
      "wrapDtoExceptions": true,
      "useHttpClientCreationMethod": false,
      "httpClientType": "System.Net.Http.HttpClient",
      "useHttpRequestMessageCreationMethod": false,
      "useBaseUrl": false,
      "generateBaseUrlProperty": true,
      "generateSyncMethods": false,
      "exposeJsonSerializerSettings": false,
      "clientClassAccessModifier": "public",
      "typeAccessModifier": "public",
      "generateContractsOutput": false,
      "contractsNamespace": null,
      "contractsOutputFilePath": null,
      "parameterDateTimeFormat": "s",
      "parameterDateFormat": "yyyy-MM-dd",
      "generateUpdateJsonSerializerSettingsMethod": true,
      "useRequestAndResponseSerializationSettings": false,
      "serializeTypeInformation": false,
      "queryNullValue": "",
      "className": "{controller}ApiClient",
      "operationGenerationMode": "MultipleClientsFromOperationId",
      "additionalNamespaceUsages": [],
      "additionalContractNamespaceUsages": [],
      "generateOptionalParameters": false,
      "generateJsonMethods": false,
      "enforceFlagEnums": false,
      "parameterArrayType": "System.Collections.Generic.IEnumerable",
      "parameterDictionaryType": "System.Collections.Generic.IDictionary",
      "responseArrayType": "System.Collections.Generic.ICollection",
      "responseDictionaryType": "System.Collections.Generic.IDictionary",
      "wrapResponses": false,
      "wrapResponseMethods": [],
      "generateResponseClasses": true,
      "responseClass": "SwaggerResponse",
      "namespace": "MyProject.Gateway.Api.Clients.CommApi",
      "requiredPropertiesMustBeDefined": true,
      "dateType": "System.DateTimeOffset",
      "jsonConverters": null,
      "anyType": "object",
      "dateTimeType": "System.DateTimeOffset",
      "timeType": "System.TimeSpan",
      "timeSpanType": "System.TimeSpan",
      "arrayType": "System.Collections.Generic.ICollection",
      "arrayInstanceType": "System.Collections.ObjectModel.Collection",
      "dictionaryType": "System.Collections.Generic.IDictionary",
      "dictionaryInstanceType": "System.Collections.Generic.Dictionary",
      "arrayBaseType": "System.Collections.ObjectModel.Collection",
      "dictionaryBaseType": "System.Collections.Generic.Dictionary",
      "classStyle": "Poco",
      "generateDefaultValues": true,
      "generateDataAnnotations": true,
      "excludedTypeNames": [],
      "excludedParameterNames": [],
      "handleReferences": false,
      "generateImmutableArrayProperties": false,
      "generateImmutableDictionaryProperties": false,
      "jsonSerializerSettingsTransformationMethod": null,
      "inlineNamedArrays": false,
      "inlineNamedDictionaries": false,
      "inlineNamedTuples": true,
      "inlineNamedAny": false,
      "generateDtoTypes": true,
      "generateOptionalPropertiesAsNullable": false,
      "generateNullableReferenceTypes": false,
      "templateDirectory": null,
      "typeNameGeneratorType": null,
      "propertyNameGeneratorType": null,
      "enumNameGeneratorType": null,
      "serviceHost": null,
      "serviceSchemes": null,
      "output": null,
      "newLineBehavior": "Auto"
    }
  }
}
```

When I now try to generate client for my API I get the following issue.

```
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Configuration.IConfiguration' while attempting to activate 'MyProject.Comm.Api.Startup'.

Runtime: NetCore31
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider provider, Type type)
   at Microsoft.AspNetCore.Hosting.StartupLoader.LoadMethods(IServiceProvider hostingServiceProvider, Type startupType, String environmentName)
   at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.<>c__DisplayClass3_0.<UseStartup>b__1(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureStartup()
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at NSwag.Commands.Generation.OpenApiGeneratorCommandBase`1.CreateWebHostAsync(AssemblyLoader assemblyLoader) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\OpenApiGeneratorCommandBase.cs:line 342
   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.RunIsolatedAsync(AssemblyLoader assemblyLoader) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 310
   at NSwag.Commands.IsolatedCommandBase`1.IsolatedCommandAssemblyLoader`1.Run(String commandType, String commandData, String[] assemblyPaths, String[] referencePaths) in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedCommandBase.cs:line 76
   at NSwag.Commands.IsolatedCommandBase`1.<>c__DisplayClass17_0.<RunIsolatedAsync>b__0() in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedCommandBase.cs:line 61
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at NSwag.Commands.IsolatedCommandBase`1.RunIsolatedAsync(String configurationFile) in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedCommandBase.cs:line 61
   at NSwag.Commands.IsolatedSwaggerOutputCommandBase`1.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedSwaggerOutputCommandBase.cs:line 51
   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 95
   at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocumentBase.cs:line 280
   at NSwag.Commands.NSwagDocument.ExecuteAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocument.cs:line 81
   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 86
   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 32
   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 56
```

And when I try generating the client using the .csproj file with Nobuild= true, I get the following error

```
Launcher directory: C:\Program Files (x86)\Rico Suter\NSwagStudio\NetCore31
System.InvalidOperationException: Swagger generation failed with non-zero exit code '1'.

Runtime: NetCore31
   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 221
   at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocumentBase.cs:line 280
   at NSwag.Commands.NSwagDocument.ExecuteAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocument.cs:line 81
   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 86
   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 32
   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 56

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: aspnet2swaggercommand requires the entry point type.MyProject.Comm.Api.Program to have either an BuildWebHost or CreateWebHostBuilder/CreateHostBuilder method. See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/hosting?tabs=aspnetcore2x for suggestions on ways to refactor your startup type.
   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToOpenApiGeneratorCommandEntryPoint.GetServiceProvider(String applicationName) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiGeneratorCommandEntryPoint.cs:line 93
   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToOpenApiGeneratorCommandEntryPoint.Process(String commandContent, String outputFile, String applicationName) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiGeneratorCommandEntryPoint.cs:line 26
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at NSwag.AspNetCore.Launcher.Program.Main(String[] args) in C:\projects\nswag\src\NSwag.AspNetCore.Launcher\Program.cs:line 170
```

These errors refer to the Startup.cs and Program.cs files so here are those two files.

**Program.cs**
```
using System;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Hosting;
using MyProject.Logging;

namespace MyProject.Comm.Api
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Console.Title = "MyProject.CommApi";
            BuildWebHost(args).RunWithLogging();
          
        }

        private static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseMyProjectLogging<Startup>("MyProject.CommApi", Environment.GetEnvironmentVariable("ApplicationInsights__InstrumentationKey"))
                .Build();
    }
}
```
**Startup.cs**
```
using Data.LinqToDb;
using MyProject.BaseApi;
using MyProject.Comm.Api.Constants;
using MyProject.Comm.Api.Extensions;
using MyProject.Configurations;
using MyProject.EmailService;
using MyProject.EmailService.Configuration;
using MyProject.Twilio;
using JetBrains.Annotations;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.ApiExplorer;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using System;
using System.Reflection;

namespace MyProject.Comm.Api
{
    public class Startup
    {
        private readonly ILogger<Startup> _logger;
        private readonly ILoggerFactory _loggerFactory;

        [UsedImplicitly]
        public Startup(
            [NotNull] IConfiguration configuration,
            [NotNull] IWebHostEnvironment env, 
            [NotNull] ILoggerFactory loggerFactory,
            [NotNull] ILogger<Startup> logger)
        {
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
            _loggerFactory = loggerFactory ?? throw new ArgumentNullException(nameof(loggerFactory));
            Configuration = configuration ?? throw new ArgumentNullException(nameof(configuration));
            Environment = env ?? throw new ArgumentNullException(nameof(env));
        }

        private IConfiguration Configuration { get; }
        private IWebHostEnvironment Environment { get; }

        public void ConfigureServices(IServiceCollection services)
        {
            var subsystemName = typeof(Startup).GetTypeInfo().Assembly.GetName().Name;

            services.AddAppSettings(Configuration);
            var serviceBusSettings = new ServiceBus.ServiceBusSettings();
            Configuration.GetSection("ServiceBus").Bind(serviceBusSettings);

            services.AddMyProjectSecureApi(subsystemName, Configuration, serviceBusSettings, _logger, _loggerFactory, Environment);

            var emailSettings = new EmailSettings();
            Configuration.GetSection("SmtpSettings").Bind(emailSettings);
            emailSettings.DefaultFromAddress = Configuration["EmailAddresses:DefaultFromAddress"];
            services.AddEmailService(emailSettings);

            services.AddRazorTemplateParser("\\MessageTemplates", Configuration);

            var twilioSettings = new Twilio.Configuration.Twilio();
            Configuration.GetSection("Twilio").Bind(twilioSettings);
            services.AddTwilio(twilioSettings);

            var dbConnectionString = Configuration.GetSection("Linq2DbConnectionSettings:ConnectionString").Value;
            services.ConfigureDbUp(dbConnectionString, Environment);
            services.ConfigureLinqToDb<IDataContext, DatabaseContext>(Configuration, Environment);
            services.RegisterRepositories();

        }

        

        [UsedImplicitly]
        public void Configure(IApplicationBuilder app, IServiceProvider serviceProvider, IApiVersionDescriptionProvider provider)
        {
            app.UseCors(AppConstants.AllowedOrigins);
            app.UseMyProjectSecureApi(Environment, Configuration, serviceProvider, true, provider);
        }
    }
}
```
Any help in this would be highly appreciated. Thanks a lot!
Regards

**Comment by jeremyVignelles** [comment]
I think that the canonical way to create an app since aspnetcore 3.0 (or maybe 2.2?) is to use a CreatWebHostBuilder instead of the BuildWebHost method. I'm not sure, but it's possible that NSwag follows these guidelines strictly. Would you like to have a look?
Follow the migration guide for aspnetcore on microsoft docs

**Comment by muradkhateeb78** [comment]
@jeremyVignelles Thank you. I actually have another service where I am using the **BuildWebHost** method and its client gets generated properly by NSwag so I think this issue might not be related to this.

**Comment by jeremyVignelles** [comment]
With the same netcoreapp version?

Anyway the .csproj way is the recommended way instead of the assembly one, if I understood correctly.

**Comment by muradkhateeb78** [comment]
Yes with **.netcoreapp 3.1**. Yeah I tried using both the methods but neither of the two worked. Though the app itself builds successfully and it is functioning properly.

**Comment by muradkhateeb78** [comment]
This was really a .Net Core's version issue. Updating .NetCore's version from **3.1.300** to **3.1.302** fixed it for me.

**Comment by RytisLT** [comment]
Had the same issue with `3.1.402` switching to `3.1.403` fixed it, strange...

**Comment by aureole82** [comment]
Didn't work with .NET Core `3.1.403` and still won't work with latest `.NET SDK 5.0.100`!

**Comment by RicoSuter** [comment]
Have you tried using csproj instead of assembly?

**Comment by aureole82** [comment]
@RicoSuter Where's the _csproj_ way documented?

**Comment by aureole82** [comment]
I could drill down the issue to a single update of the  [Microsoft.Extensions.Options.ConfigurationExtensions](https://www.nuget.org/packages/Microsoft.Extensions.Options.ConfigurationExtensions/) NuGet package:
* Version="3.1.9" still works
* with Version="3.1.10" this error occurs:
```
>Xyz.WebApp -> C:\Users\me\Projects\Xyz\Xyz.WebApp\bin\Debug\netcoreapp3.1\Xyz.WebApp.dll
>NSwag command line tool for .NET Core NetCore31, toolchain v13.9.4.0 (NJsonSchema v10.3.1.0 (Newtonsoft.Json v12.0.0.0))
>Visit http://NSwag.org for more information.
>NSwag bin directory: C:\Users\me\.nuget\packages\nswag.msbuild\13.9.4\tools\NetCore31
>System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Configuration.IConfiguration' while attempting to activate 'Xyz.WebApp.Startup'.
>   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
```

**Comment by older** [comment]
This still happens with NSwag 13.9.4 and ASP.NET Core 2.1 on .NET Framework 4. ASP.NET Core 2.1 is the only supported version on .NET 4 so it is not possible to fix it by switching to newer version when you have .NET 4 dependencies. Downgrading NSwag to 12.3.1 or ASP.NET Core references to 2.1.0 doesn't help. I can easily reproduce it with the following steps:

1. In Visual Studio create new ASP.NET Core Web Api project using default template (select .NET Framework 4 and ASP.NET Core 2.1 will be the only version available)
2. [Add NSwag AspNetCore middleware](https://github.com/RicoSuter/NSwag/wiki/AspNetCore-Middleware)
3. [Add NSwag.MSBuild](https://github.com/RicoSuter/NSwag/wiki/NSwag.MSBuild)
4. Observe InvalidOperationException exception when building

Here's [repro solution](https://github.com/RicoSuter/NSwag/files/5814366/AspNetCore21OnNet4.zip).

Or should I create separate issue for this?

**Comment by RicoSuter** [comment]
Are we referencing a too recent version of the config abstraction library?

**Comment by older** [comment]
@RicoSuter Possibly that is the reason. It uses NSwag.exe from directory `nswag.msbuild\13.9.4\tools\Win` and all Microsoft.AspNetCore.* and Microsoft.Extensions.* assemblies in that directory is of version 2.2

All references to ASP.NET Core 2.2.x should be downgraded to 2.1.latest anyway, as version 2.2 was not LTS and reached end of life in 2018. ASP.NET Core 2.1 is the only supported version on .NET 4 as of today

**Comment by older** [comment]
@RicoSuter should I open separate issue for this?

**Comment by RicoSuter** [comment]
Hmm can you create a PR?

**Comment by older** [comment]
> Hmm can you create a PR?

@RicoSuter You mean PR with downgrade to 2.1? I will do it, but I'm not sure it fixes the issue. Could you reproduce it with [this solution](https://github.com/RicoSuter/NSwag/files/5814366/AspNetCore21OnNet4.zip)?
