### ISSUE TITLE
Nswag dotnet-nswag.dll run /variables:Configuration=Debug" exited with code 255.

### ISSUE THREAD

**Issue by himaanshugoyal** [RicoSuter/NSwag#3023]
I am facing this issue for my .netcore project with NSWag in my Mac system. However, this issue. is not coming in windows for the same project. 

WebUI.csproj(67, 5): [MSB3073] The command "dotnet "/Users/himanshugoyal/.nuget/packages/nswag.msbuild/13.3.0/build/../tools/NetCore31/dotnet-nswag.dll" run /variables:Configuration=Debug" exited with code 255.

Any help what could be going wrong.

**Comment by jeremyVignelles** [comment]
Please share a minimal project that shows the issue, otherwise we won't be able to reproduce with that few info

**Comment by himaanshugoyal** [comment]
**Here is what that happens after pressing dotnet build**
himanshugoyal$ dotnet build
Microsoft (R) Build Engine version 16.7.0-preview-20360-03+188921e2f for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  Domain -> /Users/himanshugoyal/Documents/My Works/siloPG.com/Development/silopg/src/Domain/bin/Debug/netcoreapp3.1/SiloPG.Domain.dll
  Application -> /Users/himanshugoyal/Documents/My Works/siloPG.com/Development/silopg/src/Application/bin/Debug/netcoreapp3.1/SiloPG.Application.dll
  Infrastructure -> /Users/himanshugoyal/Documents/My Works/siloPG.com/Development/silopg/src/Infrastructure/bin/Debug/netcoreapp3.1/SiloPG.Infrastructure.dll
Program.cs(44,34): warning CS0168: The variable 'ex' is declared but never used [/Users/himanshugoyal/Documents/My Works/siloPG.com/Development/silopg/src/WebUI/WebUI.csproj]
  WebUI -> /Users/himanshugoyal/Documents/My Works/siloPG.com/Development/silopg/src/WebUI/bin/Debug/netcoreapp3.1/SiloPG.WebUI.dll
  WebUI -> /Users/himanshugoyal/Documents/My Works/siloPG.com/Development/silopg/src/WebUI/bin/Debug/netcoreapp3.1/SiloPG.WebUI.Views.dll
  NSwag command line tool for .NET Core NetCore31, toolchain v13.3.0.0 (NJsonSchema v10.1.11.0 (Newtonsoft.Json v12.0.0.0))
  Visit http://NSwag.org for more information.
  NSwag bin directory: /Users/himanshugoyal/.nuget/packages/nswag.msbuild/13.3.0/tools/NetCore31
  
  Executing file 'nswag.json' with variables 'Configuration=Debug'...
  System.InvalidOperationException: Process dotnet timed out.
     at NSwag.Commands.Generation.AspNetCore.Exe.RunAsync(String executable, IReadOnlyList`1 args, IConsoleHost console, Nullable`1 timeout) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\Exe.cs:line 70
     at NSwag.Commands.Generation.AspNetCore.ProjectMetadata.GetProjectMetadata(String file, String buildExtensionsDir, String framework, String configuration, String runtime, Boolean noBuild, IConsoleHost console) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\ProjectMetadata.cs:line 143
     at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 103
     at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocumentBase.cs:line 279
     at NSwag.Commands.NSwagDocument.ExecuteAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocument.cs:line 81
     at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 86
     at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 39
     at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
     at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
     at NConsole.CommandLineProcessor.Process(String[] args, Object input)
     at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 56
/Users/himanshugoyal/Documents/My Works/siloPG.com/Development/silopg/src/WebUI/WebUI.csproj(67,5): error MSB3073: The command "dotnet "/Users/himanshugoyal/.nuget/packages/nswag.msbuild/13.3.0/build/../tools/NetCore31/dotnet-nswag.dll" run /variables:Configuration=Debug" exited with code 255.

Build FAILED.

Program.cs(44,34): warning CS0168: The variable 'ex' is declared but never used [/Users/himanshugoyal/Documents/My Works/siloPG.com/Development/silopg/src/WebUI/WebUI.csproj]
/Users/himanshugoyal/Documents/My Works/siloPG.com/Development/silopg/src/WebUI/WebUI.csproj(67,5): error MSB3073: The command "dotnet "/Users/himanshugoyal/.nuget/packages/nswag.msbuild/13.3.0/build/../tools/NetCore31/dotnet-nswag.dll" run /variables:Configuration=Debug" exited with code 255.
    1 Warning(s)
    1 Error(s)

**Comment by RicoSuter** [comment]
Can it be that you didnt specify /nobuild:true and you go into an infinite build loop?

**Comment by himaanshugoyal** [comment]
I already have noBuild:true in the nswag json. I think It's something else.

**Comment by RicoSuter** [comment]
The nswag run command essentially loads and runs the application but only the ConfigureServices() and not Configure() - if you have some code in ConfigureServices() which is blocking with the "default config" then the process will time out...
