### ISSUE TITLE
NSwagStudio throws an System.ArgumentNullException

### ISSUE THREAD

**Issue by IngFie** [RicoSuter/NSwag#3067]
When I try to create a CSharp Client output from this [Here Routing API](https://developer.here.com/documentation/routing-api/8.8.0/swagger/v8.yaml) OpenAPI specification, a System.ArgumentNullException is thrown, when I press the button 'Generate Outputs' or 'Gererate Files'.

Attached you find my NSwagStudio file.
[Routing.zip](https://github.com/RicoSuter/NSwag/files/5252092/Routing.zip)

**Comment by RicoSuter** [comment]
Can you provide a stacktrace?

**Comment by IngFie** [comment]
No problem, here is the stacktrace. Created with NSwagStudio 13.8.1.0

System.ArgumentNullException: Value cannot be null. (Parameter 'key')

Runtime: NetCore31
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at NJsonSchema.JsonPathUtilities.GetJsonPaths(Object rootObject, IEnumerable`1 searchedObjects, IContractResolver contractResolver)
   at NJsonSchema.JsonSchemaReferenceUtilities.UpdateSchemaReferencePaths(Object rootObject, Boolean removeExternalReferences, IContractResolver contractResolver)
   at NJsonSchema.Infrastructure.JsonSchemaSerialization.ToJson(Object obj, SchemaType schemaType, IContractResolver contractResolver, Formatting formatting)
   at NSwag.OpenApiDocument.ToJson(SchemaType schemaType, Formatting formatting) in C:\projects\nswag\src\NSwag.Core\OpenApiDocument.cs:line 127
   at NSwag.OpenApiDocument.ToJson(SchemaType schemaType) in C:\projects\nswag\src\NSwag.Core\OpenApiDocument.cs:line 115
   at NSwag.OpenApiDocument.ToJson() in C:\projects\nswag\src\NSwag.Core\OpenApiDocument.cs:line 106
   at NSwag.Commands.OutputCommandExtensions.<>c__DisplayClass1_0.<TryWriteDocumentOutputAsync>b__0() in C:\projects\nswag\src\NSwag.Commands\Commands\OutputCommandExtensions.cs:line 28
   at NSwag.Commands.OutputCommandExtensions.TryWriteFileOutputAsync(IOutputCommand command, String path, IConsoleHost host, NewLineBehavior newLineBehavior, Func`1 generator) in C:\projects\nswag\src\NSwag.Commands\Commands\OutputCommandExtensions.cs:line 41
   at NSwag.Commands.Generation.FromDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\FromDocumentCommand.cs:line 55
   at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocumentBase.cs:line 280
   at NSwag.Commands.NSwagDocument.ExecuteAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocument.cs:line 81
   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 86
   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 32
   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 56

**Comment by RicoSuter** [comment]
We need to repro/fix this in NJS

**Comment by arturomonge** [comment]
I'm getting this error too. It has to do with referencing examples in the components section. If I remove the references to the examples (while leaving the actual examples in the component sections) the error goes away. For example,

```yaml
paths:
  /contacts:
    get:
      summary: List all contacts
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactList'
              examples:
                Contact List:
                  $ref: '#/components/examples/ContactList'
        '400':
          $ref: '#/components/responses/BadRequest'
```
This causes the error. If I simply remove this:

```yaml
              examples:
                Contact List:
                  $ref: '#/components/examples/ContactList'
```

the error is gone.

I'm attaching a simple test case where this can be reproduced. Not sure if this helps. 
[test-case.zip](https://github.com/RicoSuter/NSwag/files/5374247/test-case.zip)
