### ISSUE TITLE
Issue with NSwag.MSBuild and .NET 5

### ISSUE THREAD

**Issue by aquasonic** [RicoSuter/NSwag#3070]
We are using `NSWag.MSBuild` (v 13.7.4) to generate a TypeScript client from our ASP.NET Core Api. When I build the .NET Core app with .NET 5 RC 1, I get the following exception when executing NSWag:

```
System.InvalidOperationException: No service for type 'Microsoft.AspNetCore.Mvc.ApiExplorer.IApiDescriptionGroupCollectionProvider' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.GenerateDocumentWithApiDescriptionAsync(AssemblyLoader assemblyLoader, IServiceProvider serviceProvider, String currentWorkingDirectory) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 296
   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.GenerateDocumentAsync(AssemblyLoader assemblyLoader, IServiceProvider serviceProvider, String currentWorkingDirectory) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 280
   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.RunIsolatedAsync(AssemblyLoader assemblyLoader) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 312
   at NSwag.Commands.IsolatedCommandBase`1.IsolatedCommandAssemblyLoader`1.Run(String commandType, String commandData, String[] assemblyPaths, String[] referencePaths) in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedCommandBase.cs:line 76
   at NSwag.Commands.IsolatedCommandBase`1.<>c__DisplayClass17_0.<RunIsolatedAsync>b__0() in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedCommandBase.cs:line 61
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at NSwag.Commands.IsolatedCommandBase`1.RunIsolatedAsync(String configurationFile) in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedCommandBase.cs:line 61
   at NSwag.Commands.IsolatedSwaggerOutputCommandBase`1.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedSwaggerOutputCommandBase.cs:line 51
   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 95
   at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocumentBase.cs:line 280
   at NSwag.Commands.NSwagDocument.ExecuteAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocument.cs:line 81
   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 86
   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 32
   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 56
```

I first use the `aspNetCoreToOpenApi` document generator, and based on that the `openApiToTypeScriptClient` code generator. This is my `nswag.json` file:

```
{
    "runtime": "$(runtime)",
    "defaultVariables": null,
    "documentGenerator": {
      "aspNetCoreToOpenApi": {
        "project": null,
        "msBuildProjectExtensionsPath": null,
        "configuration": null,
        "runtime": null,
        "targetFramework": null,
        "noBuild": false,
        "verbose": true,
        "workingDirectory": null,
        "requireParametersWithoutDefault": false,
        "apiGroupNames": null,
        "defaultPropertyNameHandling": "Default",
        "defaultReferenceTypeNullHandling": "NotNull",
        "defaultDictionaryValueReferenceTypeNullHandling": "NotNull",
        "defaultResponseReferenceTypeNullHandling": "NotNull",
        "defaultEnumHandling": "Integer",
        "flattenInheritanceHierarchy": false,
        "generateKnownTypes": true,
        "generateEnumMappingDescription": false,
        "generateXmlObjects": false,
        "generateAbstractProperties": false,
        "generateAbstractSchemas": true,
        "ignoreObsoleteProperties": false,
        "allowReferencesWithProperties": false,
        "excludedTypeNames": [],
        "serviceHost": null,
        "serviceBasePath": null,
        "serviceSchemes": [],
        "infoTitle": "Title",
        "infoDescription": null,
        "infoVersion": "1.0.0",
        "documentTemplate": null,
        "documentProcessorTypes": [],
        "operationProcessorTypes": [],
        "typeNameGeneratorType": null,
        "schemaNameGeneratorType": null,
        "contractResolverType": null,
        "serializerSettingsType": null,
        "useDocumentProvider": false,
        "documentName": "v1",
        "aspNetCoreEnvironment": null,
        "createWebHostBuilderMethod": null,
        "startupType": null,
        "allowNullableBodyParameters": true,
        "output": "swagger.json",
        "outputType": "Swagger2",
        "assemblyPaths": ["myAssembly.dll"],
        "assemblyConfig": null,
        "referencePaths": [],
        "useNuGetCache": false
      }
    },
    "codeGenerators": {
      "openApiToTypeScriptClient": {
        "className": "{controller}ApiProxy",
        "moduleName": "",
        "namespace": "",
        "typeScriptVersion": 4.0,
        "template": "Angular",
        "promiseType": "Promise",
        "httpClass": "HttpClient",
        "withCredentials": false,
        "useSingletonProvider": true,
        "injectionTokenType": "InjectionToken",
        "rxJsVersion": 6.6,
        "dateTimeType": "Date",
        "nullValue": "Undefined",
        "generateClientClasses": true,
        "generateClientInterfaces": false,
        "generateOptionalParameters": true,
        "exportTypes": true,
        "wrapDtoExceptions": false,
        "exceptionClass": "SwaggerException",
        "clientBaseClass": "ApiProxyBase",
        "wrapResponses": false,
        "wrapResponseMethods": [],
        "generateResponseClasses": true,
        "responseClass": "SwaggerResponse",
        "protectedMethods": [],
        "configurationClass": null,
        "useTransformOptionsMethod": true,
        "useTransformResultMethod": true,
        "generateDtoTypes": true,
        "operationGenerationMode": "MultipleClientsFromOperationId",
        "markOptionalProperties": true,
        "generateCloneMethod": false,
        "typeStyle": "Class",
        "classTypes": [],
        "extendedClasses": [],
        "extensionCode": "nswag.extensions.ts",
        "generateDefaultValues": true,
        "excludedTypeNames": [],
        "excludedParameterNames": [],
        "handleReferences": false,
        "generateConstructorInterface": true,
        "convertConstructorInterfaceData": false,
        "importRequiredTypes": true,
        "useGetBaseUrlMethod": false,
        "baseUrlTokenName": "API_BASE_URL",
        "queryNullValue": "",
        "inlineNamedDictionaries": false,
        "inlineNamedAny": false,
        "templateDirectory": null,
        "typeNameGeneratorType": null,
        "propertyNameGeneratorType": null,
        "enumNameGeneratorType": null,
        "serviceHost": null,
        "serviceSchemes": null,
        "output": "api.ts"
      }
    }
  }
```

The command to execute the generation is as follow:

```
dotnet ./packages/NSwag.MSBuild/tools/NetCore31/dotnet-nswag.dll run nswag.json "/variables:runtime=NetCore31"
```

I saw that there is a related issue #3026, but the workaround with NSwag.AspNetCore doesn't work for us, as our Api doesn't know anything about Swagger and the client generation. The client generation is fully part of a build script.

If I generate the `swagger.json` file with NSwag.AspNetCore and only execute the `openApiToTypeScriptClient` based on the file, it works, so the issue seems to be in `aspNetCoreToOpenApi`. We use the same setup in multiple projects targeting .NET Core 3.1 without any issues.

Is there a problem with my setup or is this an issue with NSwag.MSBuild and .NET 5?

Thanks for looking into it :-)

**Comment by RicoSuter** [comment]
Probably not supported yet, as we only have a .NET Core 3.1 host, see https://github.com/RicoSuter/NSwag/issues/3026

**Comment by RicoSuter** [comment]
NSwag v13.9.0 released with .NET 5.0 support - please try again with this version.

**Comment by aquasonic** [comment]
Seems that it requires .NET 5 RC 2. We have planned to upgrade to the stable version of .NET 5 in the next couple of days, so I will test this directly on this version as soon as our upgrade is done.

**Comment by RicoSuter** [comment]
> Seems that it requires .NET 5 RC 2

I had to build with RC 2 but against .NET 5.0 libraries because the SDK is not yet on Chocolatey... is this a problem?

**Comment by aquasonic** [comment]
> is this a problem?

Does that mean it won't work with the .NET 5 GA release?

In my opinion it's not a problem if it doesn't work with RC 1, but it should with the GA release.

**Comment by RicoSuter** [comment]
I would expect that it works with the GA release...
What error do you see?

**Comment by aquasonic** [comment]
Actually I get this:

```
C:\Development\Build> "C:\Program Files\dotnet\dotnet.EXE"  ./packages/core/NSwag.MSBuild/tools/Net50/dotnet-nswag.dll run nswag.json
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '5.0.0-rc.2.20475.17' was not found.
  - The following frameworks were found:
      2.1.5 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      ........
      3.1.8 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      5.0.0-rc.1.20451.17 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=5.0.0-rc.2.20475.17&arch=x64&rid=win10-x64
```

But I haven't installed RC 2 nor GA, so I think it's expected. i will try it with the GA release as soon as possible and will report my results here.

**Comment by jeremyVignelles** [comment]
It seems that the chocolatey package is out now :
https://chocolatey.org/packages/dotnet-sdk

Wouldn't it be better to upgrade the CI instead?

**Comment by RicoSuter** [comment]
I already updated the CI, next release will be with 5.0

**Comment by RicoSuter** [comment]
@aquasonic you need to install the 5.0.100 sdk

**Comment by aquasonic** [comment]
I tested it and it's works perfectly with the 5.0.100 sdk. Thanks for the update 👍

**Comment by jamalkaksouri** [comment]
Try setting 

> "noBuild": true
