### ISSUE TITLE
System.InvalidOperationException: Process dotnet timed out.

### ISSUE THREAD

**Issue by grant77** [RicoSuter/NSwag#3096]
Our API is rather massive and takes around 1 minute to complete.  If I run nswag over and over again, eventually it will work but it usually fails with "Process dotnet timed out".  From looking at the source code, I see that it is essentially hard-coded to 60 seconds inside of "NSwag.Commands.Generation.AspNetCore.Exe.RunAsync".  

Can you increase this number or make it a parameter?

I see https://github.com/RicoSuter/NSwag/issues/2590, but it is closed so I created this bug.

Here is command line:

```
>> nswag run api.nswag /runtime:netcore31
NSwag NPM CLI
NSwag command line tool for .NET Core NetCore31, toolchain v13.8.2.0 (NJsonSchema v10.2.1.0 (Newtonsoft.Json v12.0.0.0))Visit http://NSwag.org for more information.
NSwag bin directory: C:\Users\grant\AppData\Roaming\npm\node_modules\nswag\bin\binaries\NetCore31

Executing file 'api.nswag' with variables ''...
Launcher directory: C:\Users\grant\AppData\Roaming\npm\node_modules\nswag\bin\binaries\NetCore31
System.InvalidOperationException: Process dotnet timed out.
   at NSwag.Commands.Generation.AspNetCore.Exe.RunAsync(String executable, IReadOnlyList`1 args, IConsoleHost console, Nullable`1 timeout) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\Exe.cs:line 70
   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 215
   at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocumentBase.cs:line 280
```

**Comment by IronSean** [comment]
Why was this closed with no response @RicoSuter ?

**Comment by jeremyVignelles** [comment]
It was closed by a commit (linked above) that increases the timeout.
