### ISSUE TITLE
NSwagStudio exception using input 'ASP.NET core via API Explorer'

### ISSUE THREAD

**Issue by rinkeb** [RicoSuter/NSwag#3100]
Hi,

I'm getting an exception when trying to generate a ts client using 'ASP.NET core via API Explorer' as input:

```
Launcher directory: C:\Program Files (x86)\Rico Suter\NSwagStudio\NetCore31
System.InvalidOperationException: Swagger generation failed with non-zero exit code '1'.

Runtime: NetCore31
   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 221
   at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocumentBase.cs:line 280
   at NSwag.Commands.NSwagDocument.ExecuteAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocument.cs:line 81
   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 86
   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 32
   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 56

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.RunOperationProcessors(OpenApiDocument document, ApiDescription apiDescription, Type controllerType, MethodInfo methodInfo, OpenApiOperationDescription operationDescription, List`1 allOperations, OpenApiDocumentGenerator swaggerGenerator, OpenApiSchemaResolver schemaResolver)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.AddOperationDescriptionsToDocument(OpenApiDocument document, Type controllerType, List`1 operations, OpenApiDocumentGenerator swaggerGenerator, OpenApiSchemaResolver schemaResolver)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateForControllers(OpenApiDocument document, IGrouping`2[] apiGroups, OpenApiSchemaResolver schemaResolver)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateAsync(ApiDescriptionGroupCollection apiDescriptionGroups)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateAsync(Object serviceProvider)
   at NSwag.AspNetCore.OpenApiDocumentProvider.GenerateAsync(String documentName)
   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.GenerateDocumentWithDocumentProviderAsync(IServiceProvider serviceProvider) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 287
   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.GenerateDocumentAsync(AssemblyLoader assemblyLoader, IServiceProvider serviceProvider, String currentWorkingDirectory) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 276
   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToOpenApiGeneratorCommandEntryPoint.<>c__DisplayClass0_0.<<Process>b__0>d.MoveNext() in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiGeneratorCommandEntryPoint.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToOpenApiGeneratorCommandEntryPoint.Process(String commandContent, String outputFile, String applicationName) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiGeneratorCommandEntryPoint.cs:line 29
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at NSwag.AspNetCore.Launcher.Program.Main(String[] args) in C:\projects\nswag\src\NSwag.AspNetCore.Launcher\Program.cs:line 170

```

Looks like some problem with the operation processors, because after commenting the security processor from my web api code it starts working:
`// settings.OperationProcessors.Add(new OperationSecurityScopeProcessor("bearer"));`

btw It also works fine when using input 'OpenAPI/Swagger specification'.

Any ideas?

NSwagStudio v13.8.2.0
NSwag.AspNetCore v13.8.2
asp.net core 3.1.8
asp.net core sdk 3.1.402

**Comment by rinkeb** [comment]
Never mind, found out why. 

For anyone interested: this is actually an async/await concurrency issue caused by adding the OpenApiDocument async:

```
services.AddOpenApiDocument(**async** settings =>
{
}

```
Apparently this is not awaited, causing the security processor to be added to the processors while they are already iterated by subsequent code.

**Comment by jeremyVignelles** [comment]
When you put `async` in a void returning functions, you're basically creating a fire-and-forget method. The code will execute synchronously until the await code, but then will then let the caller continue its work.

Don't do this.

The VS team came up with a nice set of analyzers to check about those kind of issues  : https://github.com/microsoft/vs-threading

**Comment by rinkeb** [comment]
@jeremyVignelles Didn't know that one, thanks! 

I was trying to achieve something similar as https://github.com/RicoSuter/NSwag/issues/1539#issuecomment-643237775, requiring some awaiting there. But it looks like thats not supported yet anyway.

**Comment by jeremyVignelles** [comment]
Maybe you could try to do your async processing outside ?
I don't think there is a way for NSwag to make that method async, because under the hood, it uses synchronous functions...

**Comment by rinkeb** [comment]
Yep, i tried that, but it tends to get a little messy, because this is needed in the ConfigureServices startup method of the application. It doesn't feel right to await http requests there. This would suit better in a later startup phase, like in the Configure method or a hosted initializer service.

Anyway, thanks for thinking along, but i'll leave it for now and just use some hardcoded definitions for now.
