### ISSUE TITLE
Could not resolve the JSON path ...

### ISSUE THREAD

**Issue by MZar2019** [RicoSuter/NSwag#3148]
Good day,

I'm trying to use NSwag Studio (x64 v13.8.2.0 on Windows 10) to generate C# objects from .yaml, but I run into an error.

Starting with file swagger.yaml, which has a reference to ../../common/classes.yaml
...
  $ref: '../../common/classes.yaml/#/components/schemas/c_errorResp'
...

common/classes.yaml contains:

openapi: 3.0.1
components:
  schemas:
 c_errorResp:
      type: object
      description: Standard success/failure response.
      required:
        - code
        - desc
      properties:
        code:
          $ref: '../types.yaml/#/components/schemas/t_errorCode'
        desc:
          $ref: '../types.yaml/#/components/schemas/t_errorDesc'

And that's where processing seems to break, in common/classes.yaml, on c_errorResp, with this error:

System.InvalidOperationException: Could not resolve the JSON path '../../common/classes.yaml/#/components/schemas/c_errorResp' within the file path 'C:\GIT\rest\accountmgmt\1\../../common/classes.yaml/'. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.IOException: The filename, directory name, or volume label syntax is incorrect : 'C:\GIT\rest\common\classes.yaml\'

I'm new to NSwag and I'm not sure how to diagnose this.

**Comment by RicoSuter** [comment]
Can you provide the specs to investigate (zip file)?

**Comment by jyoung** [comment]
I am running into the same issue. v13.9.4.0
However my ref is $ref: './Models/ValidationProblemDetail.v1.yaml'

Attached is a zip containing the spec (users.v1.yaml) and the models folder that contains the references.

[Specs.zip](https://github.com/RicoSuter/NSwag/files/5624817/Specs.zip)

**Comment by zdarovka** [comment]
I am getting same problem with the specification for Onfido 

https://github.com/onfido/onfido-openapi-spec/tree/master

**Comment by davidkethel** [comment]
I'm getting the same issue with this spec from felix.
[FelixOpenApi.zip](https://github.com/RicoSuter/NSwag/files/11348739/FelixOpenApi.zip)

**Comment by MaximillianC** [comment]
Was this issue ever resolved?  I am having it as well.

**Comment by garymon16** [comment]
I'm seeing this issue on nSwagStudio 13.20.0.0. 

Here is one of the references in my main file i3-Polic-Store.yaml. 
$ref: 'i3-common.yaml#/components/schemas/Jws'

File i3-common.yaml is sitting in the same folder as i3-Policy-Store.yaml on the local disk. 

I even tried moving both yaml files to be adjacent to the nswag file with no luck. 

Are references not supported? 

I also tried using the full path in the reference and it still says cannot find the file. 

System.NotSupportedException: Could not resolve the JSON path 'C:\Users\user42\Desktop\I3-PolicyStore-YAML\i3-common.yaml#/components/schemas/Jws' because no document path is available.

Example of error with relative path:
System.NotSupportedException: Could not resolve the JSON path 'i3-common.yaml#/components/schemas/Jws' because no document path is available.

Runtime: Net60
   at NJsonSchema.JsonReferenceResolver.ResolveReferenceAsync(Object rootObject, String jsonPath, Type targetType, IContractResolver contractResolver, Boolean append, CancellationToken cancellationToken)
   at NJsonSchema.JsonReferenceResolver.ResolveReferenceAsync(Object rootObject, String jsonPath, Type targetType, IContractResolver contractResolver, CancellationToken cancellationToken)
   at NJsonSchema.JsonSchemaReferenceUtilities.JsonReferenceUpdater.VisitJsonReferenceAsync(IJsonReference reference, String path, String typeNameHint, CancellationToken cancellationToken)
   at NJsonSchema.Visitors.AsyncJsonReferenceVisitorBase.VisitAsync(Object obj, String path, String typeNameHint, ISet`1 checkedObjects, Action`1 replacer, CancellationToken cancellationToken)
   at NJsonSchema.Visitors.AsyncJsonReferenceVisitorBase.VisitAsync(Object obj, String path, String typeNameHint, ISet`1 checkedObjects, Action`1 replacer, CancellationToken cancellationToken)
   at NJsonSchema.Visitors.AsyncJsonReferenceVisitorBase.VisitAsync(Object obj, String path, String typeNameHint, ISet`1 checkedObjects, Action`1 replacer, CancellationToken cancellationToken)
   at NJsonSchema.Visitors.AsyncJsonReferenceVisitorBase.VisitAsync(Object obj, String path, String typeNameHint, ISet`1 checkedObjects, Action`1 replacer, CancellationToken cancellationToken)
   at NJsonSchema.Visitors.AsyncJsonReferenceVisitorBase.VisitAsync(Object obj, String path, String typeNameHint, ISet`1 checkedObjects, Action`1 replacer, CancellationToken cancellationToken)
   at NJsonSchema.Visitors.AsyncJsonReferenceVisitorBase.VisitAsync(Object obj, String path, String typeNameHint, ISet`1 checkedObjects, Action`1 replacer, CancellationToken cancellationToken)
   at NJsonSchema.Visitors.AsyncJsonReferenceVisitorBase.VisitAsync(Object obj, String path, String typeNameHint, ISet`1 checkedObjects, Action`1 replacer, CancellationToken cancellationToken)
   at NJsonSchema.Visitors.AsyncJsonReferenceVisitorBase.VisitAsync(Object obj, CancellationToken cancellationToken)
   at NJsonSchema.JsonSchemaReferenceUtilities.JsonReferenceUpdater.VisitAsync(Object obj, CancellationToken cancellationToken)
   at NJsonSchema.JsonSchemaReferenceUtilities.UpdateSchemaReferencesAsync(Object rootObject, JsonReferenceResolver referenceResolver, IContractResolver contractResolver, CancellationToken cancellationToken)
   at NJsonSchema.Infrastructure.JsonSchemaSerialization.FromJsonWithLoaderAsync[T](Func`1 loader, SchemaType schemaType, String documentPath, Func`2 referenceResolverFactory, IContractResolver contractResolver, CancellationToken cancellationToken)
   at NSwag.OpenApiDocument.FromJsonAsync(String data, String documentPath, SchemaType expectedSchemaType, Func`2 referenceResolverFactory, CancellationToken cancellationToken) in /_/src/NSwag.Core/OpenApiDocument.cs:line 203
   at NSwag.OpenApiYamlDocument.FromYamlAsync(String data, String documentPath, SchemaType expectedSchemaType, Func`2 referenceResolverFactory, CancellationToken cancellationToken) in /_/src/NSwag.Core.Yaml/OpenApiYamlDocument.cs:line 76
   at NSwag.Commands.Generation.FromDocumentCommand.RunAsync() in /_/src/NSwag.Commands/Commands/Generation/FromDocumentCommand.cs:line 62
   at NSwag.Commands.Generation.FromDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in /_/src/NSwag.Commands/Commands/Generation/FromDocumentCommand.cs:line 53
   at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in /_/src/NSwag.Commands/NSwagDocumentBase.cs:line 275
   at NSwag.Commands.NSwagDocument.ExecuteAsync() in /_/src/NSwag.Commands/NSwagDocument.cs:line 81
   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in /_/src/NSwag.Commands/Commands/Document/ExecuteDocumentCommand.cs:line 85
   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in /_/src/NSwag.Commands/Commands/Document/ExecuteDocumentCommand.cs:line 32
   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.ProcessAsync(String[] args) in /_/src/NSwag.Commands/NSwagCommandProcessor.cs:line 61
