### ISSUE TITLE
consolecore not working with .NET Core 3.1 anymore

### ISSUE THREAD

**Issue by thinkOfaNumber** [RicoSuter/NSwag#3228]
Greetings!

Not sure if this is just a compatibility issue but I couldn't find docs on consolecore 13.9.4 support wrt dotnet 3.1.

I recently had a build server issue with `dotnet tool restore` not able to restore `nswag.consolecore` 13.6.1 so I thought I would update to the latest 13.9.4. (dotnet tool restore error for 13.6.1 is here for completeness):
```
[09:13:04]Package "nswag.consolecore" failed to restore, due to Microsoft.DotNet.ToolPackage.ToolPackageException: The tool package could not be restored.
[09:13:04]   at Microsoft.DotNet.Tools.Tool.Install.ProjectRestorer.Restore(FilePath project, PackageLocation packageLocation, String verbosity)
[09:13:04]   at Microsoft.DotNet.ToolPackage.ToolPackageInstaller.InstallPackageToExternalManagedLocation(PackageLocation packageLocation, PackageId packageId, VersionRange versionRange, String targetFramework, String verbosity)
[09:13:04]   at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.InstallPackages(ToolManifestPackage package, Nullable`1 configFile)
```

I am running consolecore like this on a .NET Core 3.1 web app:
`dotnet nswag aspnetcore2openapi /project:MyApp.Api.csproj /Configuration:OpenApi /documentName:v1 /output:..\..\OpenApi\MyApp.json`

with 13.9.4 I get the following output. In this run I tried `/TargetFramework:netcoreapp3.1` but it fails with or without it:
```
NSwag command line tool for .NET Core Net50, toolchain v13.9.4.0 (NJsonSchema v10.3.1.0 (Newtonsoft.Json v12.0.0.0))
Visit http://NSwag.org for more information.
NSwag bin directory: C:\Users\Iain\.nuget\packages\nswag.consolecore\13.9.4\tools\net5.0\any
Executing dotnet msbuild /nologo /verbosity:quiet /p:NSwagOutputMetadataFile=C:\Users\Iain\AppData\Local\Temp\tmpD71E.tmp /t:Build /t:__GetNSwagProjectMetadata /p:TargetFramework=netcoreapp3.1 /p:Configuration=OpenApi MyApp.Api.csproj


Done executing command. Exit Code: 0.
Done executing command
Output:
AssemblyName: MyApp.Api
OutputPath: bin\OpenApi\netcoreapp3.1\
PlatformTarget:
Platform: AnyCPU
ProjectDepsFilePath: C:\Users\Iain\projects\MyApp\src\MyApp.Api\bin\OpenApi\netcoreapp3.1\MyApp.Api.deps.json
ProjectDir: C:\Users\Iain\projects\MyApp\src\MyApp.Api\
ProjectRuntimeConfigFilePath: C:\Users\Iain\projects\MyApp\src\MyApp.Api\bin\OpenApi\netcoreapp3.1\MyApp.Api.runtimeconfig.json
TargetFileName: MyApp.Api.dll
TargetFrameworkIdentifier: .NETCoreApp
Executing dotnet exec --depsfile C:\Users\Iain\projects\MyApp\src\MyApp.Api\bin\OpenApi\netcoreapp3.1\MyApp.Api.deps.json --runtimeconfig C:\Users\Iain\projects\MyApp\src\MyApp.Api\bin\OpenApi\netcoreapp3.1\MyApp.Api.runtimeconfig.json C:\Users\Iain\.nuget\packages\nswag.consolecore\13.9.4\tools\net5.0\any\NSwag.AspNetCore.Launcher.dll C:\Users\Iain\AppData\Local\Temp\tmpE70D.tmp C:\Users\Iain\AppData\Local\Temp\tmpE70E.tmp MyApp.Api C:\Users\Iain\.nuget\packages\nswag.consolecore\13.9.4\tools\net5.0\any\
Launcher directory: C:\Users\Iain\.nuget\packages\nswag.consolecore\13.9.4\tools\net5.0\any
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Reflection.RuntimeAssembly.GetType(QCallAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type, ObjectHandleOnStack keepAlive, ObjectHandleOnStack assemblyLoadContext)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at System.Reflection.Assembly.GetType(String name, Boolean throwOnError)
   at NSwag.AspNetCore.Launcher.Program.Main(String[] args) in C:\projects\nswag\src\NSwag.AspNetCore.Launcher\Program.cs:line 126


Done executing command. Exit Code: -532462766.
System.InvalidOperationException: Swagger generation failed with non-zero exit code '-532462766'.
   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 219
   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 55
```

consolecore works with .NET 3.1 up to 13.8.2 (but I haven't tried 13.9 versions other than 13.9.4).

thanks

**Comment by bd-robert-gaede** [comment]
The issue has something to do with net5.0 since that was introduced in 13.9+ which is being used by default.  I was able to workaround this issue by specifying the framework when installing the tool, it works with the latest version today (13.9.4).

`dotnet tool install nswag.consolecore -g --framework netcoreapp3.1`

**Comment by bohbra** [comment]
The issue has something to do with net5.0 since that was introduced in 13.9+ which is being used by default.  I was able to workaround this issue by specifying the framework when installing the tool, it works with the latest version today (13.9.4).

`dotnet tool install nswag.consolecore -g --framework netcoreapp3.1`

**Comment by RicoSuter** [comment]
@bohbra maybe we should update the wiki explaining this required parameter. Can you do that?

**Comment by bohbra** [comment]
@RicoSuter This parameter only works with the global parameter.  I don't have a solution/workaround for installing it [locally](https://docs.microsoft.com/en-us/dotnet/core/tools/local-tools-how-to-use) since that parameter is not an option.  We should probably have a solution or workaround for both options.

**Comment by RicoSuter** [comment]
nswag.consolecore has multiple target frameworks but locally you probably cannot define which one to use and it will use the highest installed runtime even if the given project requires a lower one, right?

**Comment by qwertie** [comment]
In case it helps anyone, NSwagStudio gave the error "System.InvalidOperationException: Swagger generation failed with non-zero exit code '-532462766'" (in NSwagDocumentBase.cs:line 275) for a new C# .NET 6.0 project, when NSwagStudio was set to runtime Net70. The error disappeared when the Runtime option (top left) was changed to Net60.
