### ISSUE TITLE
NSwag.AspNetCore 13.10.4 fails due to NSwag.Core.Yaml dependency missing

### ISSUE THREAD

**Issue by GeorgDangl** [RicoSuter/NSwag#3318]
Basically, using `NSwag.AspNetCore` version `13.10.4` fails with the following exception once the Swagger endpoint is accessed:

    info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
          Request starting HTTP/1.1 GET http://localhost:44356/swagger/swagger.json
    fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
          An unhandled exception has occurred while executing the request.
    System.IO.FileNotFoundException: Could not load file or assembly 'NSwag.Core.Yaml, Version=13.10.4.0, Culture=neutral, PublicKeyToken=c2d88086e098d109'. Das System kann die angegebene Datei nicht finden.
    File name: 'NSwag.Core.Yaml, Version=13.10.4.0, Culture=neutral, PublicKeyToken=c2d88086e098d109'
       at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GetDocumentAsync(HttpContext context)
       at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
       at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GetDocumentAsync(HttpContext context)
       at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
       at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

To resolve, these two methods worked for me:
* Downgrade NSwag to `13.10.3`
* Manually add a reference to `NSwag.Core.Yaml`

Doesn't look to be too critical, but probably something that's very easy to resolve. I guess there's code calling to NSwag.Core.Yaml without having it listed as a dependency in the NuGet package with the latest version.

**Comment by RicoSuter** [comment]
Fixed in v13.10.5
https://github.com/RicoSuter/NSwag/pull/3319
