### ISSUE TITLE
Support discriminator with options that point to the same reference

### ISSUE THREAD

**Issue by JoostvdB94** [RicoSuter/NSwag#3356]
Today when I was trying to generate a C# client using NSwagStudio I came across the following error:

```
System.InvalidOperationException: Error while rendering Liquid template CSharp/Class: 
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Sequence contains more than one matching element

Runtime: NetCore31
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at NJsonSchema.CodeGeneration.Models.ClassTemplateModelBase.DerivedClassModel..ctor(String typeName, JsonSchema schema, OpenApiDiscriminator discriminator, TypeResolverBase resolver)
   at NJsonSchema.CodeGeneration.Models.ClassTemplateModelBase.<get_DerivedClasses>b__16_0(KeyValuePair`2 p)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NJsonSchema.CodeGeneration.Models.ClassTemplateModelBase.get_DerivedClasses()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Reflection.PropertyInfo.GetValue(Object obj)
   at NJsonSchema.CodeGeneration.LiquidProxyHash.GetValue(String key)
   at DotLiquid.Hash.System.Collections.IDictionary.get_Item(Object key)
   at DotLiquid.Context.LookupAndEvaluate(Object obj, Object key)
   at DotLiquid.Context.FindVariable(String key)
   at DotLiquid.Context.Variable(String markup, Boolean notifyNotFound)
   at DotLiquid.Context.Resolve(String key, Boolean notifyNotFound)
   at DotLiquid.Context.get_Item(String key, Boolean notifyNotFound)
   at DotLiquid.Tags.For.Render(Context context, TextWriter result)
   at DotLiquid.Block.RenderAll(List`1 list, Context context, TextWriter result)
--- End of stack trace from previous location where exception was thrown ---
   at DotLiquid.Context.HandleError(Exception ex)
   at DotLiquid.Block.RenderAll(List`1 list, Context context, TextWriter result)
   at DotLiquid.Tags.If.<>c__DisplayClass11_0.<Render>b__0()
   at DotLiquid.Context.Stack(Hash newScope, Action callback)
   at DotLiquid.Context.Stack(Action callback)
   at DotLiquid.Tags.If.Render(Context context, TextWriter result)
   at DotLiquid.Block.RenderAll(List`1 list, Context context, TextWriter result)
--- End of stack trace from previous location where exception was thrown ---
   at DotLiquid.Context.HandleError(Exception ex)
   at DotLiquid.Block.RenderAll(List`1 list, Context context, TextWriter result)
   at DotLiquid.Block.Render(Context context, TextWriter result)
   at DotLiquid.Document.Render(Context context, TextWriter result)
   at DotLiquid.Template.RenderInternal(TextWriter result, RenderParameters parameters)
   at DotLiquid.Template.Render(TextWriter writer, RenderParameters parameters)
   at DotLiquid.Template.Render(RenderParameters parameters)
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.LiquidTemplate.Render()
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at NJsonSchema.CodeGeneration.Models.ClassTemplateModelBase.DerivedClassModel..ctor(String typeName, JsonSchema schema, OpenApiDiscriminator discriminator, TypeResolverBase resolver)
   at NJsonSchema.CodeGeneration.Models.ClassTemplateModelBase.<get_DerivedClasses>b__16_0(KeyValuePair`2 p)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NJsonSchema.CodeGeneration.Models.ClassTemplateModelBase.get_DerivedClasses()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Reflection.PropertyInfo.GetValue(Object obj)
   at NJsonSchema.CodeGeneration.LiquidProxyHash.GetValue(String key)
   at DotLiquid.Hash.System.Collections.IDictionary.get_Item(Object key)
   at DotLiquid.Context.LookupAndEvaluate(Object obj, Object key)
   at DotLiquid.Context.FindVariable(String key)
   at DotLiquid.Context.Variable(String markup, Boolean notifyNotFound)
   at DotLiquid.Context.Resolve(String key, Boolean notifyNotFound)
   at DotLiquid.Context.get_Item(String key, Boolean notifyNotFound)
   at DotLiquid.Tags.For.Render(Context context, TextWriter result)
   at DotLiquid.Block.RenderAll(List`1 list, Context context, TextWriter result)
--- End of stack trace from previous location where exception was thrown ---
   at DotLiquid.Context.HandleError(Exception ex)
   at DotLiquid.Block.RenderAll(List`1 list, Context context, TextWriter result)
   at DotLiquid.Tags.If.<>c__DisplayClass11_0.<Render>b__0()
   at DotLiquid.Context.Stack(Hash newScope, Action callback)
   at DotLiquid.Context.Stack(Action callback)
   at DotLiquid.Tags.If.Render(Context context, TextWriter result)
   at DotLiquid.Block.RenderAll(List`1 list, Context context, TextWriter result)
--- End of stack trace from previous location where exception was thrown ---
   at DotLiquid.Context.HandleError(Exception ex)
   at DotLiquid.Block.RenderAll(List`1 list, Context context, TextWriter result)
   at DotLiquid.Block.Render(Context context, TextWriter result)
   at DotLiquid.Document.Render(Context context, TextWriter result)
   at DotLiquid.Template.RenderInternal(TextWriter result, RenderParameters parameters)
   at DotLiquid.Template.Render(TextWriter writer, RenderParameters parameters)
   at DotLiquid.Template.Render(RenderParameters parameters)
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.LiquidTemplate.Render()
   --- End of inner exception stack trace ---
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.LiquidTemplate.Render()
   at NJsonSchema.CodeGeneration.CodeArtifact..ctor(String typeName, String baseTypeName, CodeArtifactType type, CodeArtifactLanguage language, CodeArtifactCategory category, ITemplate template)
   at NJsonSchema.CodeGeneration.CSharp.CSharpGenerator.GenerateClass(JsonSchema schema, String typeName)
   at NJsonSchema.CodeGeneration.CSharp.CSharpGenerator.GenerateType(JsonSchema schema, String typeNameHint)
   at NJsonSchema.CodeGeneration.GeneratorBase.GenerateTypes()
   at NJsonSchema.CodeGeneration.CSharp.CSharpGenerator.GenerateTypes()
   at NSwag.CodeGeneration.CSharp.CSharpGeneratorBase.GenerateDtoTypes() in C:\projects\nswag\src\NSwag.CodeGeneration.CSharp\CSharpGeneratorBase.cs:line 106
   at NSwag.CodeGeneration.ClientGeneratorBase`3.GenerateFile(ClientGeneratorOutputType outputType) in C:\projects\nswag\src\NSwag.CodeGeneration\ClientGeneratorBase.cs:line 75
   at NSwag.Commands.CodeGeneration.SwaggerToCSharpClientCommand.<RunAsync>b__95_0() in C:\projects\nswag\src\NSwag.Commands\Commands\CodeGeneration\OpenApiToCSharpClientCommand.cs:line 273
   at NSwag.Commands.CodeGeneration.SwaggerToCSharpClientCommand.RunAsync() in C:\projects\nswag\src\NSwag.Commands\Commands\CodeGeneration\OpenApiToCSharpClientCommand.cs:line 259
   at NSwag.Commands.CodeGeneration.SwaggerToCSharpClientCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\CodeGeneration\OpenApiToCSharpClientCommand.cs:line 248
   at NSwag.Commands.NSwagDocument.ExecuteAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocument.cs:line 85
   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 86
   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 32
   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 56
```

After a lot of attempts I found that the following snippet was causing an issue:

```yaml
components:
  schemas:
    Vehicle:
      type: object
    PassengerVehicle:
      allOf:
        - $ref: "#/components/schemas/Vehicle"
        - type: object
          required: 
             - numberOfSeats
          properties:
            numberOfSeats:
              type: integer
          discriminator:
            propertyName: numberOfSeats
            mapping:
              "1": "#/components/schemas/Bike"
              "2": "#/components/schemas/SportsCar"
              "3": "#/components/schemas/Car"
              "5": "#/components/schemas/Car"
              "6": "#/components/schemas/MiniVan"
              "10": "#/components/schemas/Bus"
              "18": "#/components/schemas/Bus"
              "20": "#/components/schemas/Bus"
```

after I removed duplicatie values in the mapping, the generation succeeded without errors. (snippet below)

```yaml
components:
  schemas:
    Vehicle:
      type: object
    PassengerVehicle:
      allOf:
        - $ref: "#/components/schemas/Vehicle"
        - type: object
          required: 
             - numberOfSeats
          properties:
            numberOfSeats:
              type: integer
          discriminator:
            propertyName: numberOfSeats
            mapping:
              "1": "#/components/schemas/Bike"
              "2": "#/components/schemas/SportsCar"
              "5": "#/components/schemas/Car"
              "6": "#/components/schemas/MiniVan"
              "18": "#/components/schemas/Bus"
```

I do not remember reading that duplicate values cannot exist in the OAS3 specification. That's why I think it is a bug.

> Note: the examples above are truncated. The referenced schemas do exist

**Comment by JoostvdB94** [comment]
Another error must have occured. 
I stripped down the spec to everything but the schema's and it worked fine. 

Unfortunately I cannot (yet) share the complete spec as it contains classified information.

**Comment by JoostvdB94** [comment]
Closing it for now as I assume the problem is elsewhere, and cannot be identified without the spec itself.

**Comment by JoostvdB94** [comment]
I managed to reproduce the issue using the following configuration:

```
openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
components:
  schemas:
    Vehicle:
      type: object
    PassengerVehicle:
      allOf:
        - $ref: "#/components/schemas/Vehicle"
        - type: object
          required: 
             - numberOfSeats
          properties:
            numberOfSeats:
              type: integer
          discriminator:
            propertyName: numberOfSeats
            mapping:
              "1": "#/components/schemas/Bike"
              "2": "#/components/schemas/SportsCar"
              "3": "#/components/schemas/Car"
              "5": "#/components/schemas/Car"
              "6": "#/components/schemas/MiniVan"
              "10": "#/components/schemas/Bus"
              "18": "#/components/schemas/Bus"
              "20": "#/components/schemas/Bus"
    Bus:
      allOf:
        - $ref: "#/components/schemas/PassengerVehicle"
        - type: object
    Car:
      allOf:
        - $ref: "#/components/schemas/PassengerVehicle"
        - type: object
    SportsCar:
      allOf:
        - $ref: "#/components/schemas/PassengerVehicle"
        - type: object
    MiniVan:
      allOf:
        - $ref: "#/components/schemas/PassengerVehicle"
        - type: object
    Bike:
      allOf:
        - $ref: "#/components/schemas/PassengerVehicle"
        - type: object
  ```

When I use the sample spec above, the result is the error posted in my first message.
If it is altered to only use a single mapping entry per type as illustrated in the following snippet, the error dissapears.

```
openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
components:
  schemas:
    Vehicle:
      type: object
    PassengerVehicle:
      allOf:
        - $ref: "#/components/schemas/Vehicle"
        - type: object
          required: 
             - numberOfSeats
          properties:
            numberOfSeats:
              type: integer
          discriminator:
            propertyName: numberOfSeats
            mapping:
              "1": "#/components/schemas/Bike"
              "2": "#/components/schemas/SportsCar"
              "3": "#/components/schemas/Car"
              "6": "#/components/schemas/MiniVan"
              "10": "#/components/schemas/Bus"
    Bus:
      allOf:
        - $ref: "#/components/schemas/PassengerVehicle"
        - type: object
    Car:
      allOf:
        - $ref: "#/components/schemas/PassengerVehicle"
        - type: object
    SportsCar:
      allOf:
        - $ref: "#/components/schemas/PassengerVehicle"
        - type: object
    MiniVan:
      allOf:
        - $ref: "#/components/schemas/PassengerVehicle"
        - type: object
    Bike:
      allOf:
        - $ref: "#/components/schemas/PassengerVehicle"
        - type: object
```

Any ideas on how to fix this?

**Comment by TSteschulat** [comment]
Same Problem here. Any news on it?

**Comment by JoostvdB94** [comment]
@RicoSuter Do you perhaps have any idea where this issue may originate?
If so, i'm happy to investigate further and provide a fix

**Comment by alainbryden** [comment]
+1 for this issue. Encountered while trying to generate a C# client for [https://developer.rms.com/platform/openapi/64bf6dc3de5edc0052ef8c91](https://developer.rms.com/platform/openapi/64bf6dc3de5edc0052ef8c91), which claims to be following `"openapi": "3.0.2"` specs

The Exception is being thrown in the `NJsonSchema.CodeGeneration.Models.DerivedClassModel` constructor (decompiled):

<img width="1202" height="324" alt="Image" src="https://github.com/user-attachments/assets/f020b28b-669c-4426-ba6d-a2de8a44d7df" />

```c#
KeyValuePair<string, JsonSchema> keyValuePair = discriminator.Mapping.SingleOrDefault<KeyValuePair<string, JsonSchema>>((KeyValuePair<string, JsonSchema> m) => m.Value.ActualTypeSchema == schema2.ActualTypeSchema);
```

It seems to be parsing this piece of the specification:

<img width="457" height="256" alt="Image" src="https://github.com/user-attachments/assets/1e037af9-f7d2-472f-9631-aebd2a149a81" />

Having multiple types map to the same "actual type" (schema) doesn't seem to cause issues in general - seemingly only when one of those types is a derived type (inherits properties from some other type)?

**Comment by alainbryden** [comment]
Here's my workaround, which pre-processes the JSON document and any mappings which point to the same schema, but ***only*** if the schema they point to uses inheritance, since that's the only time this bug is triggered:

```csharp
private static async Task InterceptOpenApiSpecification(NSwagDocument document)
{
    string openApiUrl = document.SwaggerGenerators.FromDocumentCommand.Url;

    // Download the original JSON document from the internet (NSwag has a library to help with that)
    string json = await NJsonSchema.Infrastructure.DynamicApis.HttpGetAsync(openApiUrl, CancellationToken.None);
    
    // The above JSON comes as one long string. Parse it
    JsonNode parsed = JsonNode.Parse(json);

    // Pre-process the json to alter parts that would break NSwag code generation
    FixJsonIssues(parsed.Root);

    // Render the JSON to a string (in memory)
    await using MemoryStream memoryStream = new();
    await using Utf8JsonWriter jsonWriter = new(memoryStream, new JsonWriterOptions { Indented = true });
    parsed.WriteTo(jsonWriter);
    await jsonWriter.FlushAsync();
    string updatedJson = Encoding.UTF8.GetString(memoryStream.ToArray());

    // Update the document settings to use our updated file on disk rather than the source URL
    document.SwaggerGenerators.FromDocumentCommand.Url = null;
    document.SwaggerGenerators.FromDocumentCommand.Json = updatedJson;

    // (Optional) write the updated JSON to disk
    // string openApiOutputPath = Path.ChangeExtension(
    //     document.CodeGenerators.OpenApiToCSharpClientCommand.OutputFilePath, "json");
    // CreateParentDirectory(openApiOutputPath);
    // await AutoRetry(() => File.WriteAllTextAsync(openApiOutputPath, updatedJson, Encoding.UTF8));
}

private static void FixJsonIssues(JsonNode openApiSpec)
{
    if (element == null) return;
    switch (element.GetValueKind())
    {
        case JsonValueKind.Array:
            foreach (JsonNode? child in element.AsArray())
                FixJsonIssues(child);
            break;

        case JsonValueKind.Object:
            JsonObject parent = element.AsObject();
            foreach (KeyValuePair<string, JsonNode?> property in parent)
            {
                // Work Around BUG: https://github.com/RicoSuter/NSwag/issues/3356
                // Wherein the re-use of a single schema for multiple types is handled incorrectly if one of those types uses inheritance.
                if (property.Key == "mapping" && parent.GetPropertyName() == "discriminator")
                {
                    // Check for multiple mappings targeting the same type
                    JsonObject mappings = property.Value?.AsObject() ?? throw new Exception("Encountered unexpected null discriminator.mapping value.");
                    List<KeyValuePair<string, JsonNode?>> updatedMappings = new();
                    foreach (KeyValuePair<string, JsonNode?> mapping in mappings)
                    {
                        string schema = mapping.Value?.GetValue<string>() ?? throw new Exception($"Missing schema for discriminator mapping {mapping.Key}");
                        if (updatedMappings.Any(kvp => kvp.Value?.GetValue<string>() == schema))
                        {
                            // We only need to avoid this duplicate if it inherits from some other type
                            List<string> path = schema[2..].Split('/').ToList();
                            JsonNode referencedSchema = element.Root;
                            foreach (string segment in path)
                                referencedSchema = referencedSchema[segment] ?? $"Could not navigate to the property \"{segment}\" in the path \"{schema}\"";
                            if (referencedSchema["allOf"] != null || referencedSchema["anyOf"] != null || referencedSchema["oneOf"] != null)
                                continue; // Skip this duplicate mapping
                            // TODO: Consider instead of deleting the duplicate type name, make a copy of the referenced schema and give it a new name
                        }
                        // Otherwise, keep this mapping
                        updatedMappings.Add(mapping);
                    }
                    // Overwrite the original discriminator mappings with the de-duplicated list (only if we removed any)
                    if (updatedMappings.Count < mappings.Count)
                        mappings.ReplaceWith(new JsonObject(updatedMappings.Select(kvp => KeyValuePair.Create(kvp.Key, kvp.Value?.DeepClone()))));
                }
                else
                    FixJsonIssues(property.Value);
            }
            break;
    }
}
```
It's a hack, but it lets me generate the client and doesn't appear to cause any runtime errors.

**Comment by AnxietyAttack** [comment]
Same problem here.  Mapping multiple values to the same schema is valid according to the OpenAPI spec, but it throws an exception when generating code via NSwag.
