### ISSUE TITLE
NSwag.MSBuild  No service for type 'Microsoft.Extensions.DependencyInjection.IServiceProviderFactory`1[Autofac.ContainerBuilder]' has been registered.

### ISSUE THREAD

**Issue by aim-for-better** [RicoSuter/NSwag#3424]
When I use NSwag.MSBuild, I got the bellow error during build phase.

```
NSwag bin directory: C:\Users\.nuget\packages\nswag.msbuild\13.10.9\tools\NetCore31
1>System.InvalidOperationException: No service for type 'Microsoft.Extensions.DependencyInjection.IServiceProviderFactory`1[Autofac.ContainerBuilder]' has been registered.
1>   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
1>   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
1>   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services)
1>   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
1>   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
1>   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
1>   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
1>   at NSwag.Commands.Generation.OpenApiGeneratorCommandBase`1.CreateWebHostAsync(AssemblyLoader assemblyLoader) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\OpenApiGeneratorCommandBase.cs:line 334
1>   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.RunIsolatedAsync(AssemblyLoader assemblyLoader) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 315
1>   at NSwag.Commands.IsolatedCommandBase`1.IsolatedCommandAssemblyLoader`1.Run(String commandType, String commandData, String[] assemblyPaths, String[] referencePaths) in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedCommandBase.cs:line 76
1>   at NSwag.Commands.IsolatedCommandBase`1.<>c__DisplayClass17_0.<RunIsolatedAsync>b__0() in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedCommandBase.cs:line 61
1>   at System.Threading.Tasks.Task`1.InnerInvoke()
1>   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
1>   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
1>--- End of stack trace from previous location where exception was thrown ---
1>   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
1>   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
1>--- End of stack trace from previous location where exception was thrown ---
1>   at NSwag.Commands.IsolatedCommandBase`1.RunIsolatedAsync(String configurationFile) in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedCommandBase.cs:line 61
```

The csproj config is as bellow
```
  <Target Name="NSwag" AfterTargets="Build">
    <Exec Command="$(NSwagExe_Core31) aspnetcore2openapi /variables:NoBuild=true /assembly:$(TargetDir)app.dll /output:_swagger.json"></Exec>
  </Target>
```

The startup.cs is as bellow:
```
service.AddSwaggerDocument()
```
And I have register 'Microsoft.Extensions.DependencyInjection.IServiceProviderFactory`1[Autofac.ContainerBuilder] by run
```
WebHost..ConfigureServices(
                                        services => services
                                            .AddSingleton(serviceContext)
                                            .AddSingleton<IServiceProviderFactory<ContainerBuilder>>(new AutofacServiceProviderFactory()))
```
in Program.cs

**But** when I remove the csproj config, try to generate use web by run `app.UseOpenApi()` there is not error.

Could you please help answer why there is still No register error when I try to use NSwag.MSBuild but there is not error when using swag web service? And how to resolve no service type has been registered error when using the NSwag.MSbuild ?
Thanks

**Comment by jeremyVignelles** [comment]
Make sure you are using the ASP.net core patterns corectly : https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-5.0#set-up-a-host

NSwag only calls `CreateHostBuilder` and all your service configuration must happen inside (or within the ConfigureServices of the Startup.cs file

**Comment by aim-for-better** [comment]
> Make sure you are using the ASP.net core patterns corectly : https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-5.0#set-up-a-host
> 
> NSwag only calls `CreateHostBuilder` and all your service configuration must happen inside (or within the ConfigureServices of the Startup.cs file

Hi @jeremyVignelles  Thanks for your reply. I am using the WebHostBuilder to create IWebHost instance. It is not Host.
The others are the same, I configured in ConfigureServices method of StartUp.cs.  Do you have further suggestion or solution? Thank you~.  Does Nswag.MSbuild support WebHost? It seems Asp.net core 3+ is using IWebHost instead of IHost. And tIWebHost is not the son class of IHost.

**Comment by jeremyVignelles** [comment]
Send us your Program.cs. WebHost should be supported

**Comment by aim-for-better** [comment]
My Program.cs is as bellow:
```
internal static class Program
    {
        private static void Main()
        {
            
                CreateNswagHost().Run();
        }

        private static IWebHost CreateNswagHost()
        {
            return new WebHostBuilder()
                .ConfigureServices(
                    services => services.AddSingleton<IServiceProviderFactory<ContainerBuilder>>(new AutofacServiceProviderFactory()))
                .UseStartup<Startup>().Build();

        }
    }
```
I configured service.AddOpenApiDocument in Startup.cs please see above.
Thanks~

**Comment by aim-for-better** [comment]
As you see, I have registered the service provider factory by running ` services => services.AddSingleton<IServiceProviderFactory<ContainerBuilder>>(new AutofacServiceProviderFactory())`
But I still got the error when I build.

**Comment by jeremyVignelles** [comment]
Please do that in your Startup.cs or use a standard method name. I don't remember which ones NSwag is looking for, have a look at this repository code.

**Comment by jeremyVignelles** [comment]
https://github.com/RicoSuter/NSwag/blob/4f345e1adc9c49d8498d4018250760aa69dd8dd2/src/NSwag.Commands/Commands/Generation/OpenApiGeneratorCommandBase.cs#L247

CreateWebHostBuilder is the standard name, and you should return the builder, i.e. call .Build().Run() in the Main() method. This standard has changed between .net core 2.0 and .net core 3.1, I don't exactly recall when.

**Comment by aim-for-better** [comment]
Hi @jeremyVignelles 
Do you mean change to the bellow code?
```

internal static class Program
    {
        private static void Main()
        {
            
               CreateWebHostBuilder().Build().Run();
        }

       private static IWebHostBuilder CreateWebHostBuilder() => new WebHostBuilder().ConfigureServices(
                    services => services.AddSingleton<IServiceProviderFactory<ContainerBuilder>>(new AutofacServiceProviderFactory()));
    
    }

```

**Comment by jeremyVignelles** [comment]
yes, but where is your `.UseStartup<Startup>()`?

**Comment by aim-for-better** [comment]
> UseStartup

Hi thanks, I forget to add it. I still have the same error when I build the project with the new code is 
```
internal static class Program
    {
        private static void Main()
        {
            
               CreateWebHostBuilder().Build().Run();
        }

       private static IWebHostBuilder CreateWebHostBuilder() => new WebHostBuilder().ConfigureServices(
                    services => services.AddSingleton<IServiceProviderFactory<ContainerBuilder>>(new AutofacServiceProviderFactory())).UserStartup<Startup>();
    
    }
```

**Comment by jeremyVignelles** [comment]
I guess the CreateWebHostBuilder should be public so that NSwag can call it

**Comment by aim-for-better** [comment]
> I guess the CreateWebHostBuilder should be public so that NSwag can call it

Hi @jeremyVignelles, So sad... I changed it to public but still failed. Does Nswag.MSBuild has some limitation? If I remove  use
<Target Name="NSwag" AfterTargets="Build">
    <Exec Command="$(NSwagExe_Core31) aspnetcore2openapi /variables:NoBuild=true /assembly:$(TargetDir)app.dll /output:_swagger.json"></Exec>
  </Target>
and use `app.UseOpenApi() ` and access the web page https://localhost/swagger/v1/swagger.json it works well.

Thanks for your help!

**Comment by jeremyVignelles** [comment]
Have a look at the code I linked above if you see any reason it could fail.
The next step would be to clone this repository, configure it to run your code using the NSwag CLI and debug the CLI project to see what's wrong.
