### ISSUE TITLE
Newtonsoft.Json.JsonSerializationException: 

### ISSUE THREAD

**Issue by rswetnam** [RicoSuter/NSwag#3492]
I have an endpoint with which I am trying to use nswag to generate classes for a c# .net 5 project.  I get the following error:

Newtonsoft.Json.JsonSerializationException: Error setting value to 'ItemsRaw' on 'NJsonSchema.JsonSchemaProperty'. ---> Newtonsoft.Json.JsonSerializationException: Error converting value "2021-02-01" to type 'System.Collections.Generic.ICollection`1[System.Object]'. Path 'properties.qualification.properties.expiration_date_from.enum', line 1, position 1743. ---> System.ArgumentException: Could not cast or convert from System.String to System.Collections.Generic.ICollection`1[System.Object].

 at NSwag.OpenApiDocument.FromJsonAsync(String data, String documentPath, SchemaType expectedSchemaType, Func`2 referenceResolverFactory, CancellationToken cancellationToken) in C:\projects\nswag\src\NSwag.Core\OpenApiDocument.cs:line 199
   at NSwag.Commands.Generation.FromDocumentCommand.RunAsync() in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\FromDocumentCommand.cs:line 62
   at NSwag.Commands.Generation.FromDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\FromDocumentCommand.cs:line 53
   at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocumentBase.cs:line 280
   at NSwag.Commands.NSwagDocument.ExecuteAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocument.cs:line 81
   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 85
   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 32
   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 56

Is this a problem with the swagger document?  Is there something that I can suggest to the owner of that document?

**Comment by RicoSuter** [comment]
Seems that "enum" must be an array of string but in your spec it's just a string...
See
https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-validation-00#section-6.1.2
