### ISSUE TITLE
.NET Core 3.1 / JsonSerializerOptions with System.Text.Json

### ISSUE THREAD

**Issue by tobindh** [RicoSuter/NSwag#3509]
Trying to use NSwag with an API written using System.Text.Json, and the tool chain to generate the client is failing with an error due to the JsonSerializerOptions.

**2>System.MissingMethodException: Method not found: 'System.Text.Json.JsonSerializerOptions Microsoft.AspNetCore.Mvc.JsonOptions.get_JsonSerializerOptions()'.**

The API is configured with the following:

            services.AddControllers().AddJsonOptions(options =>
            {
                options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter());
            });

It's failing trying to get the JsonSerializerOptions - the error appears to be in GetSystemTextJsonSettings (in AspNetCoreOpenApiDocumentGenerator.cs), but it looks like the tests that check are passing.  Any suggestions?

Stack trace:

2>NSwag command line tool for .NET Core NetCore31, toolchain v13.11.3.0 (NJsonSchema v10.4.4.0 (Newtonsoft.Json v12.0.0.0))
2>Visit http://NSwag.org for more information.
2>NSwag bin directory: C:\Users\<username>\.nuget\packages\nswag.msbuild\13.11.3\tools\NetCore31
**2>System.MissingMethodException: Method not found: 'System.Text.Json.JsonSerializerOptions Microsoft.AspNetCore.Mvc.JsonOptions.get_JsonSerializerOptions()'.**

2>   at Api.Startup.<>c.<ConfigureServices>b__4_0(JsonOptions options)
2>   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
2>   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
2>   at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0()
2>   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
2>   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
2>   at System.Lazy`1.CreateValue()
2>   at System.Lazy`1.get_Value()
2>   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
2>   at Microsoft.Extensions.Options.OptionsManager`1.Get(String name)
2>   at Microsoft.Extensions.Options.OptionsManager`1.get_Value()
2>   at Microsoft.AspNetCore.Mvc.MvcCoreMvcOptionsSetup.Configure(MvcOptions options)
2>   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
2>   at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0()
2>   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
2>   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
2>   at System.Lazy`1.CreateValue()
2>   at System.Lazy`1.get_Value()
2>   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
2>   at Microsoft.Extensions.Options.OptionsManager`1.Get(String name)
2>   at Microsoft.Extensions.Options.OptionsManager`1.get_Value()
2>   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateAsync(Object serviceProvider) in C:\projects\nswag\src\NSwag.Generation.AspNetCore\AspNetCoreOpenApiDocumentGenerator.cs:line 51
2>   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.GenerateDocumentWithDocumentProviderAsync(IServiceProvider serviceProvider) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 299
2>   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.GenerateDocumentAsync(AssemblyLoader assemblyLoader, IServiceProvider serviceProvider, String currentWorkingDirectory) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 289
2>   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.RunIsolatedAsync(AssemblyLoader assemblyLoader) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 325
2>   at NSwag.Commands.IsolatedCommandBase`1.IsolatedCommandAssemblyLoader`1.Run(String commandType, String commandData, String[] assemblyPaths, String[] referencePaths) in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedCommandBase.cs:line 76
2>   at NSwag.Commands.IsolatedCommandBase`1.<>c__DisplayClass17_0.<RunIsolatedAsync>b__0() in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedCommandBase.cs:line 61
2>   at System.Threading.Tasks.Task`1.InnerInvoke()
2>   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
2>   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
2>--- End of stack trace from previous location where exception was thrown ---
2>   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
2>   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
2>--- End of stack trace from previous location where exception was thrown ---
2>   at NSwag.Commands.IsolatedCommandBase`1.RunIsolatedAsync(String configurationFile) in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedCommandBase.cs:line 61
2>   at NSwag.Commands.IsolatedSwaggerOutputCommandBase`1.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedSwaggerOutputCommandBase.cs:line 51
2>   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 98
2>   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
2>   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
2>   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
2>   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 56

**Comment by HypeillingerChillinger** [comment]
@tobindh Did you manage to get the enum values as strings in the swagger UI as available options?

**Comment by tobindh** [comment]
@HypeillingerChillinger I have not - it looks like there's a dependency issue somewhere, just haven't had the time to debug it.
