### ISSUE TITLE
[npm] .NET version autodetection logic is incorrect

### ISSUE THREAD

**Issue by ascott18** [RicoSuter/NSwag#3522]
In https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Npm/bin/nswag.js#L58-L61, the logic here to autodetect the right binaries to used based on the output of `dotnet --version` is incorrect.

`dotnet --version` produces an output like `5.0.201\r\n`. This string is then being compared against the known supported .NET versions, like `21`, `31`, and `50`. However, `5.0.201` does not contain the string `50`, so the comparison fails and the version is not autoselected to .NET 5. 

Furthermore, this logic could lead to false matches if the patch version of the installed .NET SDK happens to contain one of the supported versions like `21`. For example. SDK 2.1.509 ([an actual release of .NET 2.1](https://dotnet.microsoft.com/download/dotnet/2.1)) would be a false match for Net50.

**Comment by RicoSuter** [comment]
Strange, i wonder whether this ever worked somehow - either it never worked or some commit introduced a regression. Can you create a PR to fix that?

**Comment by KaaCee** [comment]
Not sure if this is the same issue:

Running
> $(NSwagExe_Net50) run nswag.json

throws this error:
`System.InvalidOperationException: The specified runtime in the document (NetCore21) differs from the current process runtime (Net50). Change the runtime with the '/runtime:NetCore21' parameter or run the file with the correct command line binary.
   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 68
   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 39
   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 55`

Adding parameter /runtime as in
> $(NSwagExe_Net50) run /runtime:NetCore21 nswag.json

or
> $(NSwagExe_Net50) run /runtime:Net50 nswag.json

yields no differences in the behavior.

Is this related and is there a workaround for that?
I'm on Manjaro Linux.

**Comment by RicoSuter** [comment]
So can we actually close this issue? @ascott18?

**Comment by ascott18** [comment]
No, this is still an issue. I haven't had a change to make a PR for it.

**Comment by worthy7** [comment]
Returning to a project I occasionally update and I get this when trying to update my clients
```
NSwag NPM CLI
Found runtime from config: Net80
Using runtime: Net80
You must install or update .NET to run this application.

App: E:\source\repos\calendr\src\Calendr.Web.Host\node_modules\nswag\bin\binaries\Net80\dotnet-nswag.dll
Architecture: x64
Framework: 'Microsoft.AspNetCore.App', version '8.0.0' (x64)
.NET location: C:\Program Files\dotnet\

The following frameworks were found:
  9.0.15 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  10.0.7 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]

The following frameworks for other architectures were found:
  x86
    9.0.15 at [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
    10.0.7 at [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]

Learn more:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=8.0.0&arch=x64&rid=win-x64&os=win10
```

But why is it trying to use 8 instead of the installed 10? My config is simply "runtime:Default"

Running the same config in NSwagStudio works fine, its just the npm version that doesn't work
