### ISSUE TITLE
NSwagStudio 13.13.0.0 crashing on load

### ISSUE THREAD

**Issue by scottkocur-sc** [RicoSuter/NSwag#3583]
upgraded nswag to 13.13.0.0 and the app just crashes on load

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileLoadException: Could not load file or assembly 'Namotion.Reflection, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c2f9c3bdfae56102' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at NSwag.Generation.OpenApiDocumentGeneratorSettings..ctor()
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGeneratorSettings..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance[T]()
   at NSwag.Commands.Generation.OpenApiGeneratorCommandBase`1..ctor()
   at NSwag.Commands.NSwagDocument..ctor()
   at CreateNSwag.Commands.NSwagDocument()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NSwag.Commands.NSwagDocumentBase.FromJson[TDocument](String filePath, String data)
   at NSwag.Commands.NSwagDocumentBase.<>c__DisplayClass35_0`1.<<LoadAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.NSwagDocument.<LoadAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwagStudio.ViewModels.MainWindowModel.<>c__DisplayClass38_0.<<OpenDocumentAsync>b__0>d.MoveNext() in C:\projects\nswag\src\NSwagStudio\ViewModels\MainWindowModel.cs:line 159
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MyToolkit.Mvvm.ViewModelBase.<>c__DisplayClass14_0.<<RunTaskAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MyToolkit.Mvvm.ViewModelBase.<RunTaskAsync>d__12`1.MoveNext()

![Capture](https://user-images.githubusercontent.com/74327937/128256329-52bf3f29-9619-4359-a711-419085767314.PNG)

**Comment by ImGonaRot** [comment]
I got it to work by going here https://www.nuget.org/packages/Namotion.Reflection/2.0.0 and extracting the Namotion.Reflection.dll from the net45 folder into the C:\Program Files (x86)\Rico Suter\NSwagStudio folder.
Make sure to replace the current 1.0.23 version.

**Comment by SMERKY** [comment]
@ImGonaRot Are you able to extract the Namotion.Reflection.dll without actually having to install the package to a project?

**Comment by SMERKY** [comment]
Managed to extract it by downloading nupkg file and changing to .ZIP and extracting

**Comment by svrooij** [comment]
I had the same issue....
This was my fix:

```bash
winget install nswagstudio -v 13.12.1.0
```

**Comment by RicoSuter** [comment]
Not all NuGet packages have been correctly updated... 
Will release a fix in the next hours (v13.13.1)

**Comment by svrooij** [comment]
I also saw that the latest package in winget is `13.12.1.0` and was wondering how that package reaches winget and if this can also be automated some way, for instance with a Github action

**Comment by RicoSuter** [comment]
@svrooij I think winget uses chocolatey, that's where we deploy the NSwagStudio package, it's currently on v13.13.0
https://community.chocolatey.org/packages/NSwagStudio

Will be releasing v13.13.1 soon with the fixes.

**Comment by svrooij** [comment]
They use some sort of manual git repository. Maybe this can be automated.

@jadieaston seems to be doing it manual for now, can this be automated is some way?

**Comment by denelon** [comment]
@RicoSuter we have a [CI/CD tool](https://github.com/microsoft/winget-create#using-windows-package-manager-manifest-creator-in-a-cicd-pipeline) that can help with automation for publishing to the Windows Package Manager Community repository.
