### ISSUE TITLE
Error: Cannot generate swagger.json with generic types

### ISSUE THREAD

**Issue by NovichikhinAlexey** [RicoSuter/NSwag#3591]
version 13.13.1
Cannot generate swagger.json in case if response model uses generic type.

NET 5.0

exception
```
System.InvalidOperationException: This operation is only valid on generic types.
   at System.RuntimeType.GetGenericTypeDefinition()
   at Namotion.Reflection.ContextualType.<get_Properties>b__42_0(PropertyInfo property)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at Namotion.Reflection.ContextualType.get_Properties()
   at Namotion.Reflection.ContextualTypeExtensions.GetContextualProperties(Type type)
   at NJsonSchema.Generation.JsonSchemaGenerator.ApplyAdditionalProperties[TSchemaType](TSchemaType schema, Type type, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateInheritance(ContextualType type, JsonSchema schema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateObject(JsonSchema schema, JsonTypeDescription typeDescription, JsonSchemaResolver schemaResolver)
   at NSwag.Generation.OpenApiSchemaGenerator.GenerateObject(JsonSchema schema, JsonTypeDescription typeDescription, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.Generate[TSchemaType](TSchemaType schema, ContextualType contextualType, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.Generate[TSchemaType](ContextualType contextualType, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateWithReferenceAndNullability[TSchemaType](ContextualType contextualType, Boolean isNullable, JsonSchemaResolver schemaResolver, Action`2 transformation)
   at NSwag.Generation.OpenApiSchemaGenerator.GenerateWithReferenceAndNullability[TSchemaType](ContextualType contextualType, Boolean isNullable, JsonSchemaResolver schemaResolver, Action`2 transformation)
   at NSwag.Generation.AspNetCore.Processors.OperationResponseProcessor.Process(OperationProcessorContext operationProcessorContext)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.RunOperationProcessors(OpenApiDocument document, ApiDescription apiDescription, Type controllerType, MethodInfo methodInfo, OpenApiOperationDescription operationDescription, List`1 allOperations, OpenApiDocumentGenerator swaggerGenerator, OpenApiSchemaResolver schemaResolver)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.AddOperationDescriptionsToDocument(OpenApiDocument document, Type controllerType, List`1 operations, OpenApiDocumentGenerator swaggerGenerator, OpenApiSchemaResolver schemaResolver)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateForControllers(OpenApiDocument document, IGrouping`2[] apiGroups, OpenApiSchemaResolver schemaResolver)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateAsync(ApiDescriptionGroupCollection apiDescriptionGroups)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GenerateDocumentAsync(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GetDocumentAsync(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

example

```csharp

[Route("/api/v1/hello")]
public class HelloController 
{
    [HttpGet]
    public async Task<Response<string>> Hello()
    {
        return new Response<string>(ApiResponseCodes.Error);
    }
}  
  
  
public class Response<T> : Response where T : class
{
    public T Data { get; set; }
    
    public Response(T data)
	    : base(ApiResponseCodes.OK)
    {
	    this.Data = data;
    }
    
    public Response(ApiResponseCodes result)
	    : base(result)
    {
	    this.Data = default (T);
    }
}
```

In version 13.12.1 this case works well.

**Comment by RicoSuter** [comment]
v13.13.2 with a fix released soon (next hours)

**Comment by NovichikhinAlexey** [comment]
thank you

**Comment by tjrobinson** [comment]
A very similar issue has been raised here, also caused by the Namotion upgrade as far as I can tell: https://github.com/RicoSuter/NSwag/issues/3600

**Comment by patrick129** [comment]
I get the same error with a generic query parameter using NSwag 14.0.3 and .Net 6.

**Comment by simeyla** [comment]
The problem with the 'generics error' is if you've upgraded from a previous version you're sort of in the dark as to which controller or method is broken. I have dozens of methods!

Tip:

Use logging to find which controller or method is causing problems.

1) Create an OperationProcessor

            services.AddOpenApiDocument(document =>
            {
                document.OperationProcessors.Insert(0, new ControllerFilterProcessor());
            })

2) Output the controller and method name. The last line output will indicate the method with an issue.

```
public class ControllerFilterProcessor : IOperationProcessor
{
    public bool Process(OperationProcessorContext context)
    {
        Console.WriteLine("[NSWAG] CONTROLLER " + context.ControllerType.Name + " " + context.MethodInfo.Name);

        // Optional: temporarily skip controllers you know or suspect to have issues
        switch (context.ControllerType.Name)
        {
            case "CartController":
            return false; 
        }

        return true;
    }
}
```

3) Use `[JsonIgnore]` attribute (for me this was the System.Text one) to narrow down further.

4) Not all errors are about 'generic type', so check the error message each time for additional clues.

5) The issue may be the return type or one of the input parameters to your webmethod.

@RicoSuter  Is it possible for the error message to indicate the ControllerType and MethodInfo so we don't have to do this?

**Comment by stephendritchie** [comment]
Hi

Has this been resolved as I'm getting this error using NSwag 14.0.7 and .Net8..?

I'm using the following class as part of a request sent to a controller

```
    public class GridOptions<T> where T : class
    {
        public List<FilterDefinition<T>> Filter { get; set; }
    }
```

The controller definition is

```

        [HttpPost]
        [Route("api/[controller]/list")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<HighbayItemModel>))]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        public async Task<IActionResult> GetHighbayItems(HighbayRequest criteria)
        {

```

The model passed as the input parameter is

```
    public  class HighbayRequest
    {
        public HighbaySnapshotFilterModel Filter { get; set; }
    }


    public class HighbaySnapshotFilterModel
    {
        public GridOptions<HighbayItemModel> Grid { get; set; } 
    }

```

I've removed other properties for brevity.

I have narrowed it down to the GridOptions<T> parameter as other controllers process fine and this one does if I remove it from the request.

**Comment by barnuri-cp** [comment]
any update about the issue ? keep happening in nswag 14.1.0 and .net 6
