### ISSUE TITLE
Issue running NSwag cli on .NET 5 projects

### ISSUE THREAD

**Issue by brian-welsh** [RicoSuter/NSwag#3639]
I'm currently running NSwag as a task in an Azure DevOps pipeline when targeting dotnet 5.

Early in the pipeline executing:

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 5.x'
  inputs:
    packageType: 'sdk'
    version: '5.x'

# Install nswag
    npm install nswag -g

# Set runtime
    nswag version /runtime:Net50  #no error

    nswag webapi2openapi `  # Error thrown from here
        /assembly:<path to assembly>/MyService.Service.Implementation.dll `
       /output:<swagger out path>/MyService.Service.Implementation.json

-- Errors thrown -- 

`
NSwag version: 13.13.2.0
NJsonSchema version: 10.5.2.0 (Newtonsoft.Json v12.0.0.0)

Duration: 00:00:00.0074533
NSwag NPM CLI
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      5.0.10 at [C:\hostedtoolcache\windows\dotnet\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=win10-x64
child_process.js:836
    throw err;
    ^

Error: Command failed: dotnet "C:\npm\prefix\node_modules\nswag\bin/binaries/NetCore21/dotnet-nswag.dll" webapi2openapi /assembly:<path to assembly>/MyService.Service.Implementation.dll /output:<swagger out path>/MyService.Service.Implementation.json
    at checkExecSyncError (child_process.js:760:11)
    at Object.execSync (child_process.js:833:15)
    at C:\npm\prefix\node_modules\nswag\bin\nswag.js:65:11
    at ChildProcess.exithandler (child_process.js:381:7)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  status: 2147516566,
  signal: null,
  output: [ null, null, null ],
  pid: 1336,
  stdout: null,
  stderr: null
}
`

**Comment by brian-welsh** [comment]
additional: Executing identical commands on my workstation successfully generates the swagger json document.

**Comment by grufffta** [comment]
I think you need to add another UseDotNet task to the pipeline to install version 2.x of the SDK

**Comment by TonyHenrique** [comment]
I think that I am having a similar issue, but on Desktop. This error is being displayed on NSwagStudio:

```
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' (x64) was not found.
  - The following frameworks were found:
      3.1.22 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      5.0.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      5.0.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      5.0.14 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      6.0.0-preview.7.21377.19 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      6.0.2 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=win10-x64
```
![image](https://user-images.githubusercontent.com/6307623/161462367-19ba3e4b-3725-4bf2-9b28-e36d39bc6fba.png)
