### ISSUE TITLE
NSwag 13.13.2 can not use Microsoft.Extensions.DependencyInjection.Abstractions 5.0.0 

### ISSUE THREAD

**Issue by husilan** [RicoSuter/NSwag#3643]
Previous I am using Microsoft.Extensions.DependencyInjection.Abstractions 3.1 and it succeeded.

And I am trying to upgrade Microsoft.Extensions.DependencyInjection.Abstractions to 5.0.0, but it failed

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.MissingMethodException: Method not found: 'Microsoft.AspNetCore.Hosting.IWebHostBuilder Microsoft.AspNetCore.Hosting.IWebHostBuilder.ConfigureServices(System.Action`1<Microsoft.Extensions.DependencyInjection.IServiceCollection>)'.
   at Microsoft.HDInsight.ApiSvc.SwaggerHostBuilderProvider.CreateSwaggerWebHostBuilder()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)

**Comment by robv8r** [comment]
Did you happen to find a solution for this?

**Comment by robv8r** [comment]
I wasn't able to get `aspnetcore2openapi` working.  After reviewing the documentation, I found [a reference to `webapi2openapi`](https://github.com/RicoSuter/NSwag/wiki/WebApiToOpenApiCommand).

My command was very similar to the one posted by @husilan.  I replaced the `aspnetcore2openapi` command with `webapi2openapi` and it worked.

Please note the following:

> Important: This reflection based generator is deprecated for ASP.NET Core projects and replaced by the new APi Explorer based generator [AspNetCoreOpenApiDocumentGenerator](https://github.com/RicoSuter/NSwag/wiki/AspNetCoreOpenApiDocumentGenerator)!

Also, please read the [Assembly Loading](https://github.com/RicoSuter/NSwag/wiki/Assembly-loading) wiki document to ensure NSwag can find your assemblies.

If I stumble on a way to make `aspnetcore2openapi` work properly, I'll post it here.

**Comment by robv8r** [comment]
I found that `aspnetcore2openapi` doesn't work as expected when using `$(NSwagExe_Core31)` from the MSBuild NuGet package.  Like @husilan, I'm working on an aspnetcore 3.1 app.

Using `$(NSwagExe_Net60)` worked on the first try.

For reference:

global.json

```
{
  "sdk": {
    "version": "3.1.102",
    "rollForward": "latestFeature"
  }
}
```

Project file:

```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <!-- omitted for brevity -->
  </PropertyGroup>

  <Target Name="NswagGen" BeforeTargets="AfterBuild">
    <PropertyGroup>
      <_NSwagOutputDirectory>$(MSBuildProjectDirectory)/ClientApp/src/services</_NSwagOutputDirectory>
      <_NSwagOpenApiJsonPath>$(_NSwagOutputDirectory)/openapi.json</_NSwagOpenApiJsonPath>
    </PropertyGroup>
    <Exec Command="$(NSwagExe_Net60) aspnetcore2openapi /assembly:$(TargetPath) /documentName:v1 /output:$(_NSwagOpenApiJsonPath) /outputtype:OpenApi3">
      <Output TaskParameter="ExitCode" PropertyName="_NSwagExitCode" />
      <Output TaskParameter="ConsoleOutput" PropertyName="_NSwagOutput" />
    </Exec>
    <Message Text="$(_NSwagOutput)" Condition="'$(_NSwagExitCode)' == '0'" Importance="high" />
    <Error Text="$(_NSwagOutput)" Condition="'$(_NSwagExitCode)' != '0'" />
 </Target>

</Project>
```
