### ISSUE TITLE
nswag CLI 13.14.1 cannot load Fluid.dll on .NET Core

### ISSUE THREAD

**Issue by MadSciencist** [RicoSuter/NSwag#3714]
The error:
```
nswag openapi2tsclient /input:swagger.json /classname:Client /template:Fetch /typeStyle:Interface /markOptionalProperties:false /output:index.ts

NSwag NPM CLI
NSwag command line tool for .NET Core NetCore21, toolchain v13.14.1.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v11.0.0.0))
Visit http://NSwag.org for more information.
NSwag bin directory: C:\repo\Project\contract\node_modules\nswag\bin\binaries\NetCore21
System.TypeInitializationException: The type initializer for 'LiquidTemplate' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Fluid, Version=0.0.0.0, Culture=neutral, PublicKeyToken=51cdb8c1938e4789'. The system cannot find the file specified.
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.LiquidTemplate..cctor()
   --- End of inner exception stack trace ---
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.CreateTemplate(String language, String template, Object model)
   at NSwag.CodeGeneration.TypeScript.TypeScriptClientGenerator.GenerateFile(IEnumerable`1 clientTypes, IEnumerable`1 dtoTypes, ClientGeneratorOutputType outputType) in D:\Projects\NSwag\src\NSwag.CodeGeneration.TypeScript\TypeScriptClientGenerator.cs:line 97
   at NSwag.CodeGeneration.ClientGeneratorBase`3.GenerateFile(ClientGeneratorOutputType outputType) in D:\Projects\NSwag\src\NSwag.CodeGeneration\ClientGeneratorBase.cs:line 96
   at NSwag.Commands.CodeGeneration.SwaggerToTypeScriptClientCommand.<RunAsync>b__159_0() in D:\Projects\NSwag\src\NSwag.Commands\Commands\CodeGeneration\OpenApiToTypeScriptClientCommand.cs:line 417
   at NSwag.Commands.CodeGeneration.SwaggerToTypeScriptClientCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in D:\Projects\NSwag\src\NSwag.Commands\Commands\CodeGeneration\OpenApiToTypeScriptClientCommand.cs:line 399
   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in D:\Projects\NSwag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 56node:child_process:747
    throw err;
```

Worked perfectly fine on the 13.14.0

**Comment by Powerz** [comment]
13.14.0 failed for .net 5.0
13.14.1 complains about this Fluid

**Comment by RicoSuter** [comment]
Really strange, build copied a preview version of NJsonSchema to the NPM binaries..

**Comment by RicoSuter** [comment]
The v13.14.2 should now contain the correct DLLs.

**Comment by Powerz** [comment]
Works on mac.

**Comment by hisuwh** [comment]
In 13.17.0 this seems to be broken again
