### ISSUE TITLE
aspnetcore2openapi  CLI Command fails in version 13.4.5

### ISSUE THREAD

**Issue by esond** [RicoSuter/NSwag#3750]
In the [latest version](https://www.npmjs.com/package/nswag/v/13.14.5) of the CLI, the aspnetcore2openapi command fails with the exception: 

```log
System.TypeLoadException: Could not load type 'NJsonSchema.Generation.PropertyNameHandling' from assembly 'NJsonSchema, Version=10.5.2.0, Culture=neutral, PublicKeyToken=c2f9c3bdfae56102'.
```

I confirmed that this does work in 13.14.4 (we pinned the version to 13.14.4 and it works fine again). See attached excerpt from our Azure Pipelines build log (with redactions).

[2021-11-23_nswag-13.14.5-error.log](https://github.com/RicoSuter/NSwag/files/7591199/2021-11-23_nswag-13.14.5-error.log)

**Comment by mtrenouth** [comment]
Not sure if this is the same issue, but openApiToCSharpClient fails too

nswag run config.json /runtime:NetCore31

Json Configuration:
```
{
  "runtime": "NetCore31",
  "documentGenerator": {
    "fromDocument": {
      "url": "https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/api-with-examples.yaml",
      "output": null,
      "newLineBehavior": "Auto"
    }
  },
  "codeGenerators": {
    "openApiToCSharpClient": {
      "output": "../NSWag/SampleClient.cs",
      "namespace": "Client",
      "generateClientInterfaces": "true",
      "UseHttpRequestMessageCreationMethod": "true",
      "ConfigurationClass": "NSwagClientConfiguration",
      "ClientBaseClass": "NSwagClientBase"
    }
  }
}

```

Output
```
NSwag NPM CLI
NSwag command line tool for .NET Core NetCore31, toolchain v13.14.5.0 (NJsonSchema v10.5.2.0 (Newtonsoft.Json v12.0.0.0))
Visit http://NSwag.org for more information.
NSwag bin directory: 

Executing file '.\sample.json' with variables ''...
System.InvalidOperationException: Instances of abstract classes cannot be created.
   at NSwag.Commands.Generation.TypesToSwaggerCommand..ctor()
   at NSwag.Commands.Generation.TypesToOpenApiCommand..ctor()
   at NSwag.Commands.NSwagDocument..ctor() in D:\Projects\NSwag\src\NSwag.Commands\NSwagDocument.cs:line 40
   at lambda_method(Closure )
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NSwag.Commands.NSwagDocumentBase.FromJson[TDocument](String filePath, String data) in D:\Projects\NSwag\src\NSwag.Commands\NSwagDocumentBase.cs:line 230
   at NSwag.Commands.NSwagDocumentBase.LoadDocument[TDocument](String filePath, IDictionary`2 mappings, String data) in D:\Projects\NSwag\src\NSwag.Commands\NSwagDocumentBase.cs:line 217
   at NSwag.Commands.NSwagDocumentBase.<>c__DisplayClass35_0`1.<<LoadAsync>b__0>d.MoveNext() in D:\Projects\NSwag\src\NSwag.Commands\NSwagDocumentBase.cs:line 207
--- End of stack trace from previous location where exception was thrown ---
   at NSwag.Commands.NSwagDocument.LoadWithTransformationsAsync(String filePath, String variables) in D:\Projects\NSwag\src\NSwag.Commands\NSwagDocument.cs:line 69
   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in D:\Projects\NSwag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 63
   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in D:\Projects\NSwag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 32
   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in D:\Projects\NSwag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 56child_process.js:682
    throw err;
    ^

Error: Command failed: dotnet "XXXXX/dotnet-nswag.dll" run .\sample.json /runtime:NetCore31
    at checkExecSyncError (child_process.js:643:11)
    at Object.execSync (child_process.js:679:15)
    at C:\Users\mtrenouth\AppData\Roaming\npm\node_modules\nswag\bin\nswag.js:54:19
    at ChildProcess.exithandler (child_process.js:310:7)
    at ChildProcess.emit (events.js:375:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  status: 4294967295,
  signal: null,
  output: [ null, null, null ],
  pid: 18576,
  stdout: null,
  stderr: null
}
```

**Comment by brkzr** [comment]
We have this problem too in our project. After rollback to previous version "npm nswag run" command running flawless. But 13.4.5 gives this error. 
```
Executing file 'nswag.json' with variables ''...
System.InvalidOperationException: Instances of abstract classes cannot be created.
   at NSwag.Commands.Generation.TypesToSwaggerCommand..ctor()
   at NSwag.Commands.NSwagDocument..ctor() in D:\Projects\NSwag\src\NSwag.Commands\NSwagDocument.cs:line 40
   at lambda_method(Closure )
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NSwag.Commands.NSwagDocumentBase.FromJson[TDocument](String filePath, String data) in D:\Projects\NSwag\src\NSwag.Commands\NSwagDocumentBase.cs:line 230
   at NSwag.Commands.NSwagDocumentBase.<>c__DisplayClass35_0`1.<<LoadAsync>b__0>d.MoveNext() in D:\Projects\NSwag\src\NSwag.Commands\NSwagDocumentBase.cs:line 207
--- End of stack trace from previous location where exception was thrown ---
   at NSwag.Commands.NSwagDocument.LoadWithTransformationsAsync(String filePath, String variables) in D:\Projects\NSwag\src\NSwag.Commands\NSwagDocument.cs:line 69
   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in D:\Projects\NSwag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 63
   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in D:\Projects\NSwag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 42
   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in D:\Projects\NSwag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 56node:child_process:903
    throw err;
    ^
```
We stayed on version 13.4.4 as a workaround 

```
npm uninstall nswag -g
npm install nswag@13.14.4 -g
```

**Comment by RicoSuter** [comment]
Sorry for the inconveniences, we migrated the pipelines to NUKE and stuff is currently not working as expected... let my try to fix it v13.14.6

**Comment by RicoSuter** [comment]
Can you try again with the NPM package v13.14.6?

**Comment by esond** [comment]
No worries Rico, sh*t happens! Thanks for the quick response.

I am encountering a different error with 13.4.6, running the identical command. The new error is:

```
Application references version '13.14.4.0' of 'NSwag.Core' which is lower than the required version '13.14.5.0'.

Done executing command. Exit Code: 4.
System.InvalidOperationException: Swagger generation failed with non-zero exit code '4'.
   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 240
   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
 ```

P.S.. I love Nuke. In fact I use it in combination with NSwag a ton (there are some gremlins to work out with the tooling I think, a contribution I had been looking at making!)

**Comment by esond** [comment]
I just deleted a comment on the issue that was entirely incorrect, sorry. Just starting my day here.

**Comment by esond** [comment]
The reported issue appears to be fixed in v13.14.6.

No worries Rico, sh*t happens and the turnaround on a response is highly appreciated. Thank you.

**Comment by brkzr** [comment]
problem solved. But the package version shows as 13.14.5. thx for quick response.  

```
NSwag NPM CLI
NSwag command line tool for .NET Core NetCore21, toolchain v13.14.5.0 (NJsonSchema v10.5.2.0 (Newtonsoft.Json v11.0.0.0))
Visit http://NSwag.org for more information.
NSwag bin directory: C:\Projects\Mobile\Mobile.Services\Domain Services\Security Service\node_modules\nswag\bin\binaries\NetCore21

Executing file 'nswag.json' with variables ''...
Done.
```

**Comment by esond** [comment]
I get the following error for the command `aspnetcore2openapi /project:PROJECT.csproj /output:SCHEMA.json /configuration:Debug /targetFramework:net6.0 /verbose:true /noBuild:true` in v13.14.6

```
Application references version '13.14.4.0' of 'NSwag.Core' which is lower than the required version '13.14.5.0'.


Done executing command. Exit Code: 4.
System.InvalidOperationException: Swagger generation failed with non-zero exit code '4'.
   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 240
   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
```

**Comment by esond** [comment]
Oh, updated my package references in the API project now too to 13.14.5, working now. Looks resolved (I mean it this time).

Thank you very much!

**Comment by DerekLiang** [comment]
I am experiencing the similar problem with 13.14.5. It worked fine with 13.14.4.  @esond 

```
npx nswag@13.14.5 run src/app/swagger-api/swagger-api.nswag /runtime:Net50 

npx: installed 1 in 1.238s
NSwag NPM CLI
NSwag command line tool for .NET Core Net50, toolchain v13.14.5.0 (NJsonSchema v10.5.2.0 (Newtonsoft.Json v12.0.0.0))
Visit http://NSwag.org for more information.
NSwag bin directory: /Users/xxx/.npm/_npx/92556/lib/node_modules/nswag/bin/binaries/Net50

Executing file 'src/app/swagger-api/swagger-api.nswag' with variables ''...
System.InvalidOperationException: Instances of abstract classes cannot be created.
   at NSwag.Commands.Generation.TypesToSwaggerCommand..ctor()
   at NSwag.Commands.Generation.TypesToOpenApiCommand..ctor()
   at NSwag.Commands.NSwagDocument..ctor() in D:\Projects\NSwag\src\NSwag.Commands\NSwagDocument.cs:line 40
   at lambda_method6(Closure )
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NSwag.Commands.NSwagDocumentBase.FromJson[TDocument](String filePath, String data) in D:\Projects\NSwag\src\NSwag.Commands\NSwagDocumentBase.cs:line 230
   at NSwag.Commands.NSwagDocumentBase.LoadDocument[TDocument](String filePath, IDictionary`2 mappings, String data) in D:\Projects\NSwag\src\NSwag.Commands\NSwagDocumentBase.cs:line 217
   at NSwag.Commands.NSwagDocumentBase.<>c__DisplayClass35_0`1.<<LoadAsync>b__0>d.MoveNext() in D:\Projects\NSwag\src\NSwag.Commands\NSwagDocumentBase.cs:line 207
--- End of stack trace from previous location ---
   at NSwag.Commands.NSwagDocument.LoadWithTransformationsAsync(String filePath, String variables) in D:\Projects\NSwag\src\NSwag.Commands\NSwagDocument.cs:line 69
   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in D:\Projects\NSwag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 63
   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in D:\Projects\NSwag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 32
   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in D:\Projects\NSwag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 55child_process.js:836
    throw err;
    ^

Error: Command failed: dotnet "/Users/xxx/.npm/_npx/92556/lib/node_modules/nswag/bin/binaries/Net50/dotnet-nswag.dll" run src/app/swagger-api/swagger-api.nswag /runtime:Net50
    at checkExecSyncError (child_process.js:760:11)
    at Object.execSync (child_process.js:833:15)
    at /Users/xxx/.npm/_npx/92556/lib/node_modules/nswag/bin/nswag.js:54:19
    at ChildProcess.exithandler (child_process.js:381:7)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  status: 255,
  signal: null,
  output: [ null, null, null ],
  pid: 92562,
  stdout: null,
  stderr: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yyy-web@0.0.1 api: `npx nswag@13.14.5 run src/app/swagger-api/swagger-api.nswag /runtime:Net50 && node src/app/swagger-api/patch-api.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the yyy-web@0.0.1 api script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2021-11-24T17_48_49_271Z-debug.log
```


swagger configuration: 

```
{
  "runtime": "Net50",
  "defaultVariables": null,
  "documentGenerator": {
    "fromDocument": {
      "json": "",
      "url": "./sample-swagger.json",
      "output": null
    }
  },
  "codeGenerators": {
    "openApiToTypeScriptClient": {
      "className": "{controller}xxxApiClient",
      "moduleName": "",
      "namespace": "",
      "typeScriptVersion": 2.7,
      "template": "Angular",
      "promiseType": "Promise",
      "httpClass": "HttpClient",
      "withCredentials": false,
      "useSingletonProvider": true,
      "injectionTokenType": "InjectionToken",
      "rxJsVersion": 6.0,
      "dateTimeType": "Date",
      "nullValue": "Null",
      "generateClientClasses": true,
      "generateClientInterfaces": true,
      "generateOptionalParameters": false,
      "exportTypes": true,
      "wrapDtoExceptions": false,
      "exceptionClass": "ApiException",
      "clientBaseClass": "yyyApiClientBase",
      "wrapResponses": false,
      "wrapResponseMethods": [],
      "generateResponseClasses": true,
      "responseClass": "SwaggerResponse",
      "protectedMethods": [],
      "configurationClass": "",
      "useTransformOptionsMethod": true,
      "useTransformResultMethod": false,
      "generateDtoTypes": true,
      "operationGenerationMode": "MultipleClientsFromOperationId",
      "markOptionalProperties": false,
      "generateCloneMethod": false,
      "typeStyle": "Interface",
      "enumStyle": "Enum",
      "useLeafType": true,
      "classTypes": [],
      "extendedClasses": [],
      "extensionCode": "swagger-api-base.ts",
      "generateDefaultValues": true,
      "excludedTypeNames": [],
      "excludedParameterNames": [],
      "handleReferences": false,
      "generateConstructorInterface": true,
      "convertConstructorInterfaceData": false,
      "importRequiredTypes": true,
      "useGetBaseUrlMethod": false,
      "baseUrlTokenName": "API_BASE_URL",
      "queryNullValue": "",
      "inlineNamedDictionaries": false,
      "inlineNamedAny": false,
      "templateDirectory": null,
      "typeNameGeneratorType": null,
      "propertyNameGeneratorType": null,
      "enumNameGeneratorType": null,
      "serviceHost": null,
      "serviceSchemes": null,
      "output": "swagger-api.ts"
    }
  }
}

```
