### ISSUE TITLE
nswag CLI for mac error

### ISSUE THREAD

**Issue by franconeilglovasa** [RicoSuter/NSwag#3753]
has anyone tried nswag cli on mac m1? Im getting this erorr:

```
franco@Francos-MacBook-Air taskapp % nswag run nswag-taskapp.nswag
NSwag NPM CLI
NSwag command line tool for .NET Core NetCore21, toolchain v13.14.7.0 (NJsonSchema v10.5.2.0 (Newtonsoft.Json v11.0.0.0))
Visit http://NSwag.org for more information.
NSwag bin directory: /usr/local/lib/node_modules/nswag/bin/binaries/NetCore21

Executing file 'nswag-taskapp.nswag' with variables ''...
System.InvalidOperationException: The specified runtime in the document (Net50) differs from the current process runtime (NetCore21). Change the runtime with the '/runtime:Net50' parameter or run the file with the correct command line binary.
   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in D:\a\NSwag\NSwag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 85
   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in D:\a\NSwag\NSwag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 32
   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in D:\a\NSwag\NSwag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 56child_process.js:866
    throw err;
    ^

Error: Command failed: dotnet "/usr/local/lib/node_modules/nswag/bin/binaries/NetCore21/dotnet-nswag.dll" run nswag-taskapp.nswag
    at checkExecSyncError (child_process.js:790:11)
    at Object.execSync (child_process.js:863:15)
    at /usr/local/lib/node_modules/nswag/bin/nswag.js:66:11
    at ChildProcess.exithandler (child_process.js:374:7)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5) {
  status: 255,
  signal: null,
  output: [ null, null, null ],
  pid: 76880,
  stdout: null,
  stderr: null
}
```

anyone tried to make nswag cli work on m1?

**Comment by jzs11** [comment]
@RicoSuter thanks for bringing this wonderful tool, just want to know are you planning to have a mac version in any near future? Thanks

**Comment by RicoSuter** [comment]
It seems to be running with the wrong runtime, try:

nswag run nswag-taskapp.nswag /runtime:Net50

**Comment by franconeilglovasa** [comment]
HI!

Where does the .ts code being generated?

I added this code on c#

 ```
[AllowAnonymous]
        [HttpGet("RunTest")]
        public async Task<bool> RunTest()
        {

            return true;
        }
```

Configure the nswag on Nswag studio (on windows), copy all the code to mac and run the command and this is what it says.


```
franco@Francos-Air TaskApp % nswag run nswag-taskapp.nswag /runtime:Net50
NSwag NPM CLI
NSwag command line tool for .NET Core Net50, toolchain v13.14.7.0 (NJsonSchema v10.5.2.0 (Newtonsoft.Json v12.0.0.0))
Visit http://NSwag.org for more information.
NSwag bin directory: /usr/local/lib/node_modules/nswag/bin/binaries/Net50

Executing file 'nswag-taskapp.nswag' with variables ''...
Done.

Duration: 00:00:02.9365414
```

But I couldnt see the RunTest being added on swagger-generated.ts
