### ISSUE TITLE
NSwagger Studio ASP.NET Core via API Explorer not working

### ISSUE THREAD

**Issue by abuzaforfagun** [RicoSuter/NSwag#3770]
**Project Option**: It generates empty Swagger Specification.
**Assembly Option**: It return an error about BuildWebHost or CreateWebHostBuilder not found.
```
System.InvalidOperationException: NSwag requires the assembly ZEnergy.LoyaltyCards.Frontend.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null to have either an BuildWebHost or CreateWebHostBuilder/CreateHostBuilder method. See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/hosting?tabs=aspnetcore2x for suggestions on ways to refactor your startup type.

Runtime: Net60
   at NSwag.Commands.ServiceProviderResolver.GetServiceProvider(Assembly assembly) in D:\a\NSwag\NSwag\src\NSwag.Commands\HostApplication.cs:line 87
   at NSwag.Commands.Generation.OpenApiGeneratorCommandBase`1.GetServiceProvider(AssemblyLoader assemblyLoader) in D:\a\NSwag\NSwag\src\NSwag.Commands\Commands\Generation\OpenApiGeneratorCommandBase.cs:line 299
   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.RunIsolatedAsync(AssemblyLoader assemblyLoader) in D:\a\NSwag\NSwag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 323
   at NSwag.Commands.IsolatedCommandBase`1.IsolatedCommandAssemblyLoader.Run(String commandType, String commandData, String[] assemblyPaths, String[] referencePaths) in D:\a\NSwag\NSwag\src\NSwag.Commands\Commands\IsolatedCommandBase.cs:line 76
   at NSwag.Commands.IsolatedCommandBase`1.<>c__DisplayClass17_0.<RunIsolatedAsync>b__0() in D:\a\NSwag\NSwag\src\NSwag.Commands\Commands\IsolatedCommandBase.cs:line 61
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__271_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at NSwag.Commands.IsolatedCommandBase`1.RunIsolatedAsync(String configurationFile) in D:\a\NSwag\NSwag\src\NSwag.Commands\Commands\IsolatedCommandBase.cs:line 61
   at NSwag.Commands.IsolatedSwaggerOutputCommandBase`1.RunAsync(CommandLineProcessor processor, IConsoleHost host) in D:\a\NSwag\NSwag\src\NSwag.Commands\Commands\IsolatedSwaggerOutputCommandBase.cs:line 51
   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in D:\a\NSwag\NSwag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 98
   at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in D:\a\NSwag\NSwag\src\NSwag.Commands\NSwagDocumentBase.cs:line 280
   at NSwag.Commands.NSwagDocument.ExecuteAsync() in D:\a\NSwag\NSwag\src\NSwag.Commands\NSwagDocument.cs:line 81
   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in D:\a\NSwag\NSwag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 85
   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in D:\a\NSwag\NSwag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 32
   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in D:\a\NSwag\NSwag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 55


```

Steps to reproduce:

- Create new .NET 6 web api from VS.
- Add following packages inside .csproj.
```
<ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="6.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer" Version="5.0.0" />
    <PackageReference Include="NSwag.AspNetCore" Version="13.14.7" />
  </ItemGroup>
  ```
- Replace program.cs by following source code.

```

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Versioning;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

builder.Services.AddControllers()
    .AddNewtonsoftJson(options =>
    {
        options.SerializerSettings.Converters.Add(new Newtonsoft.Json.Converters.StringEnumConverter());
    });
builder.Services.AddApiVersioning(options =>
{
    options.AssumeDefaultVersionWhenUnspecified = true;
    options.ReportApiVersions = true;
    options.DefaultApiVersion = new ApiVersion(1, 0);
    options.ApiVersionReader = new UrlSegmentApiVersionReader();
}).AddVersionedApiExplorer(options =>
{
    options.SubstituteApiVersionInUrl = true;
});
builder.Services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
builder.Services.AddHttpClient();

builder.Services.AddOpenApiDocument(document =>
{
    document.DocumentName = "v1";
    document.Version = "v1";
    document.Title = "Test API";
    document.Description = "Test API";
});

var app = builder.Build();
app.UseOpenApi();
app.UseSwaggerUi3();



app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();

```

NSwagger Studio Version: 13.14.7.0

**Comment by RicoSuter** [comment]
Using assembly is obsolete and should not be used, controllers with minimal APIs do not work (use Startup.cs), see https://github.com/RicoSuter/NSwag/issues/3794

**Comment by arielnahom** [comment]
I get the same error, I'm on dotnet7, no minimal APIs. 
maybe it's because of this [condition ](https://github.com/RicoSuter/NSwag/pull/3723/commits/b780656ebf961efe67a54edcc9b8312423b887f7#diff-1ad55db0f813fb482c588bb83b55ab27c4012cbabb2f4aeab25c5ed2eca0a9c7L72) on the above mentioned PR not having NET7 ? 

my csproj : 
`<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Configurations>Debug;Release;Test</Configurations>
    
    <PackageId>gt178.Client</PackageId>
    <Product>gt178.Client</Product>
    <IsPackable>true</IsPackable>
    <PackageTags>gt178.Client</PackageTags>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <PackageVersion>1.0.0</PackageVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Version>1.0.0</Version>
    <IncludeSymbols>true</IncludeSymbols>
    <NoWarn>$(NoWarn);NU5128</NoWarn>
	  <Nullable>enable</Nullable>

  </PropertyGroup>

  <ItemGroup>
    <None Remove="swagger.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
	<PackageReference Include="NSwag.MSBuild" Version="13.19">
		<PrivateAssets>all</PrivateAssets>
		<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
	</PackageReference>
  </ItemGroup>

  <PropertyGroup>
    <RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
  </PropertyGroup>
  	<ItemGroup>
		<ProjectReference Include="..\..\src\gt178.API\gt178.API.csproj">
			<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
			<SkipGetTargetFrameworkProperties>true</SkipGetTargetFrameworkProperties>
		</ProjectReference>
	</ItemGroup>

	<Target Name="NSwag" AfterTargets="PostBuildEvent" Condition=" '$(Configuration)' == 'Release' " >
	  <Message Importance="High" Text="$(NSwagExe_Net60) run nswag.json /variables:Configuration=$(Configuration)" />
	  <Exec WorkingDirectory="$(ProjectDir)" EnvironmentVariables="ASPNETCORE_ENVIRONMENT=Release" Command="$(NSwagExe_Net60) run nswag.json /variables:Configuration=$(Configuration)" />
	  <Delete Files="$(ProjectDir)\obj\$(MSBuildProjectFile).NSwag.targets" />
	</Target>

</Project>
`


nswag is default with 
`  "runtime": "Net70",`

**Comment by kibblewhite** [comment]
Was there a fix for ths, I have the same issue.
