### ISSUE TITLE
System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Http.TagsAttribute' from assembly 'Microsoft.AspNetCore.Http.Extensions

### ISSUE THREAD

**Issue by remohoeppli** [RicoSuter/NSwag#3775]
I am having an Issue with a `System.TypeLoadException` when I try to open the Swagger page, but I cannot figure out what is wrong.

![image](https://user-images.githubusercontent.com/8382449/144600008-f7acbc6c-ea51-46f9-b4f3-bfc0cd8f9240.png)

![image](https://user-images.githubusercontent.com/8382449/144600514-4adc6558-3b09-45c2-aeed-9166ec8f3868.png)

fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Http.TagsAttribute' from assembly 'Microsoft.AspNetCore.Http.Extensions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
         at NSwag.Generation.AspNetCore.Processors.AspNetCoreOperationTagsProcessor.Process(OperationProcessorContext context)
         at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.RunOperationProcessors(OpenApiDocument document, ApiDescription apiDescription, Type controllerType, MethodInfo methodInfo, OpenApiOperationDescription operationDescription, List`1 allOperations, OpenApiDocumentGenerator swaggerGenerator, OpenApiSchemaResolver schemaResolver)
         at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.AddOperationDescriptionsToDocument(OpenApiDocument document, Type controllerType, List`1 operations, OpenApiDocumentGenerator swaggerGenerator, OpenApiSchemaResolver schemaResolver)
         at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateApiGroups(OpenApiDocument document, IGrouping`2[] apiGroups, OpenApiSchemaResolver schemaResolver)
         at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateAsync(ApiDescriptionGroupCollection apiDescriptionGroups)
         at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GenerateDocumentAsync(HttpContext context)
         at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GetDocumentAsync(HttpContext context)
         at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.

System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Http.TagsAttribute' from assembly 'Microsoft.AspNetCore.Http.Extensions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at NSwag.Generation.AspNetCore.Processors.AspNetCoreOperationTagsProcessor.Process(OperationProcessorContext context)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.RunOperationProcessors(OpenApiDocument document, ApiDescription apiDescription, Type controllerType, MethodInfo methodInfo, OpenApiOperationDescription operationDescription, List`1 allOperations, OpenApiDocumentGenerator swaggerGenerator, OpenApiSchemaResolver schemaResolver)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.AddOperationDescriptionsToDocument(OpenApiDocument document, Type controllerType, List`1 operations, OpenApiDocumentGenerator swaggerGenerator, OpenApiSchemaResolver schemaResolver)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateApiGroups(OpenApiDocument document, IGrouping`2[] apiGroups, OpenApiSchemaResolver schemaResolver)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateAsync(ApiDescriptionGroupCollection apiDescriptionGroups)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GenerateDocumentAsync(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GetDocumentAsync(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

Theses are the Nswag packages i use from my csproj file.

PackageReference Include="NSwag.AspNetCore" Version="13.14.8"
PackageReference Include="NSwag.MSBuild" Version="13.14.8"

Running on dotnet 6

Any help or hint would be much appreciated, since I cannot make any sense of it. Thank you so much.

**Comment by it-monkey** [comment]
Downgrading to version 13.14.4 solve this for now. Seems that there was something introduced in version 13.14.5 that introduced the issue.

**Comment by RicoSuter** [comment]
Can you point to the specific commit where you suspect the change?

**Comment by it-monkey** [comment]
I don't really see what the code does, but it was introduced from version 13.14.4 to 13.14.5 in one of the files from my stack trace. It may be that it is not even the cause of the issue.

![image](https://user-images.githubusercontent.com/8382449/144805049-18187801-c0ef-4c01-a419-12a22cfd03a5.png)

**Comment by RicoSuter** [comment]
I'd rather say it's this commit, though I have no clue why this fails in your machine as it's just a .NET 6 API

**Comment by it-monkey** [comment]
If you need any information for further investigating, please, let me know.

**Comment by chrisheil** [comment]
I ran into this same exact issue today and it was only reproducible on a co-worker's machine and not mine. We tried the latest version 13.15.9 but had the same issue. Downgrading to 13.14.4 resolved it

Some more information, my coworker was still running dotnet 6.0.100-rc.1.21463.6 while I was on 6.0.200. I had them upgrade to 6.0.200 but still ran into the issue on 13.14.5

It is reproducible using the cli and VS2019 Professional (v16.11.8 Preview 1.0 if it helps). Only other difference I can tell is they're running Windows 11, I'm on Windows 10, which shouldn't matter

**Comment by bjartekh** [comment]
I experienced the same issue as reported by @chrisheil 
Nswag worked on my machine, but not on my co-worker's after upgrading to Nswag 13.15.7.

He was btw running with dotnet `6.0.100-preview.7.21379.14` and when updating to dotnet `6.0.300` this issue was resolved.
