### ISSUE TITLE
RuntimeBinderException: 'object' does not contain a definition for 'Value'

### ISSUE THREAD

**Issue by zxz524** [RicoSuter/NSwag#3776]
CallSite.Target(Closure , CallSite , object )
NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GetJsonSerializerSettings(IServiceProvider serviceProvider)
NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateAsync(object serviceProvider)
NSwag.AspNetCore.OpenApiDocumentProvider.GenerateAsync(string documentName)
NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GenerateDocumentAsync(HttpContext context)
NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GetDocumentAsync(HttpContext context)
NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by RicoSuter** [comment]
Is this still an issue with the latest version?

**Comment by zxz524** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，你的邮件已经收到，我会尽快给您回复。

**Comment by dogchunx** [comment]
We've just updated a project to .NET 6 and can confirm that we're seeing this issue with the latest version.

**Comment by RicoSuter** [comment]
Can someone provide a example where we can repro this?
Eg a PR on one of the sample projects in this repo?

**Comment by helmerm** [comment]
We got a similar issue in the JsonSchemaGenerator after upgrade to .NET6. Rollback to 3.1 fixes the issue.
NSwag version 13.15.9.

The exception says the Converter is of type 'Newtonsoft.Json.JsonConverter'. However, this should actually be the generated _JsonInheritanceConverter_ which is referenced via the _JsonConverterAttribute_

I can only explain [the exception occurring here](https://github.com/RicoSuter/NJsonSchema/blob/022ba2726bf3b32eaa8e9e130b43d633c6f916c0/src/NJsonSchema/Generation/JsonSchemaGenerator.cs#L1208) caused by [TryGetInheritanceDiscriminatorConverter](https://github.com/RicoSuter/NJsonSchema/blob/022ba2726bf3b32eaa8e9e130b43d633c6f916c0/src/NJsonSchema/Generation/JsonSchemaGenerator.cs#L1184) looking up a wrong attribute which contains a _JsonConverter_ instead of _JsonInheritanceConverter_.

fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'Newtonsoft.Json.JsonConverter' does not contain a definition for 'DiscriminatorName'
         at CallSite.Target(Closure , CallSite , Object )
         at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
         at NJsonSchema.Generation.JsonSchemaGenerator.TryGetInheritanceDiscriminatorName(Object jsonInheritanceConverter)
         at NJsonSchema.Generation.JsonSchemaGenerator.GenerateInheritanceDiscriminator(Type type, JsonSchema schema, JsonSchema typeSchema)
         at NJsonSchema.Generation.JsonSchemaGenerator.GenerateObject(JsonSchema schema, JsonTypeDescription typeDescription, JsonSchemaResolver schemaResolver)
         at NSwag.Generation.OpenApiSchemaGenerator.GenerateObject(JsonSchema schema, JsonTypeDescription typeDescription, JsonSchemaResolver schemaResolver)
         at NJsonSchema.Generation.JsonSchemaGenerator.Generate[TSchemaType](TSchemaType schema, ContextualType contextualType, JsonSchemaResolver schemaResolver)
         at NJsonSchema.Generation.JsonSchemaGenerator.Generate[TSchemaType](ContextualType contextualType, JsonSchemaResolver schemaResolver)
         at NJsonSchema.Generation.JsonSchemaGenerator.Generate[TSchemaType](Type type, JsonSchemaResolver schemaResolver)
............... shortened ..........

**Comment by zxz524** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，你的邮件已经收到，我会尽快给您回复。

**Comment by Holmslice86** [comment]
Also encountered this issue, seems to be resolved when I roll back from .net 6 to .net 5.

**Comment by mikoskinen** [comment]
Updated our project to .NET 6 and started seeing this same issue. Though in our case it seems that updating NSwag to 13.15.9 helped.

**Comment by rachkoud** [comment]
> Updated our project to .NET 6 and started seeing this same issue. Though in our case it seems that updating NSwag to 13.15.9 helped.

I also faced the same issue. Updating NSwag from 13.14.4 to 13.15.9 also solved the problem.

**Comment by helmerm** [comment]
@rachkoud @mikoskinen @Holmslice86 anyone of you is working with _JsonInheritanceConverter_?

**Comment by helmerm** [comment]
> Can someone provide a example where we can repro this? Eg a PR on one of the sample projects in this repo?

@RicoSuter any idea what could be causing the exception from my example?

**Comment by Holmslice86** [comment]
I am not working with the JsonInheritanceConverter. I tried updating NSwag to 13.15.9 and it looks like that did the trick. It is now working for me in .NET 6. 👍 🙇
