### ISSUE TITLE
Application references version '13.15.1.0' of 'NSwag.Core' which is lower than the required version '14.0.0.0'.

### ISSUE THREAD

**Issue by c1rus** [RicoSuter/NSwag#3787]
I have downloaded latest NSwagStudio, added latest NSwag.AspNetCore and im using runtime Net50 and getting this error:

```
System.InvalidOperationException: Swagger generation failed with non-zero exit code '4'.

Runtime: Net50
   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in D:\a\NSwag\NSwag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 231
   at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in D:\a\NSwag\NSwag\src\NSwag.Commands\NSwagDocumentBase.cs:line 280
   at NSwag.Commands.NSwagDocument.ExecuteAsync() in D:\a\NSwag\NSwag\src\NSwag.Commands\NSwagDocument.cs:line 81
   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in D:\a\NSwag\NSwag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 85
   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in D:\a\NSwag\NSwag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 32
   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.ProcessAsync(String[] args) in D:\a\NSwag\NSwag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 61

Application references version '13.15.1.0' of 'NSwag.Core' which is lower than the required version '14.0.0.0'.
```

so here c:\Program Files (x86)\Rico Suter\NSwagStudio\ is version '13.15.1.0' but in Net50 or Net60 is version '14.0.0.0'.

<img width="839" alt="image" src="https://user-images.githubusercontent.com/11233730/145551272-eb2b3a93-d45d-4eed-a738-2dcceaa198ea.png">

**Comment by RicoSuter** [comment]
Where did you download this version?

**Comment by RicoSuter** [comment]
The problem is that the MSI installer project builds the binaries like this: 

![image](https://user-images.githubusercontent.com/2603405/145553554-4293a514-0946-47f8-a5b5-ea10ec914c59.png)

This is why it does not pick up the git tag version but uses the preview version (from the props). For now I'll keep the props version aligned with the actual tag version... but we need a way to fix that. /cc @lahma

**Comment by c1rus** [comment]
wow, that was quick. thank you

**Comment by RicoSuter** [comment]
v13.15.3 hopefully - v13.15.2 failed and is in a broken state on CI..
