### ISSUE TITLE
Error while rendering Liquid template TypeScript/Client.RequestUrl:

### ISSUE THREAD

**Issue by stanyork** [RicoSuter/NSwag#3832]
May relate to #2131 Error while rendering Liquid template CSharp/Class 
May relate to change from DotLiquid to Fluid

The same swagger.json (attached) works with NJsonSchema.CodeGeneration [+ .TypeScript ] 10.5.2 but fails on 10.6.6

```
Unhandled exception. System.IenvalidOperationException: Error while rendering Liquid template TypeScript/JQueryPromisesClient:
System.InvalidOperationException: Error while rendering Liquid template TypeScript/Client.RequestUrl:
Fluid.ParseException: '{% endif %}' was expected at (12:1)
   at Fluid.FluidParserExtensions.Parse(FluidParser parser, String template)
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.LiquidTemplate.<Render>b__12_0(ValueTuple`2 _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.LiquidTemplate.Render()
 ---> Fluid.ParseException: '{% endif %}' was expected at (12:1)
   at Fluid.FluidParserExtensions.Parse(FluidParser parser, String template)
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.LiquidTemplate.<Render>b__12_0(ValueTuple`2 _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.LiquidTemplate.Render()
   --- End of inner exception stack trace ---
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.LiquidTemplate.Render()
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.LiquidParser.RenderTemplate(List`1 arguments, TextWriter writer, TextEncoder encoder, TemplateContext context)
   at Fluid.Parser.ParserTagStatement`1.WriteToAsync(TextWriter writer, TextEncoder encoder, TemplateContext context)
   at Fluid.Ast.ForStatement.WriteToAsync(TextWriter writer, TextEncoder encoder, TemplateContext context)
   at Fluid.Ast.IfStatement.Awaited(ValueTask`1 conditionTask, ValueTask`1 incompleteStatementTask, TextWriter writer, TextEncoder encoder, TemplateContext context, Int32 statementStartIndex)
   at Fluid.Parser.FluidTemplate.Awaited(ValueTask`1 task, TextWriter writer, TextEncoder encoder, TemplateContext context, IReadOnlyList`1 statements, Int32 startIndex)
   at Fluid.FluidTemplateExtensions.<RenderAsync>g__Awaited|3_0(ValueTask task, StringWriter writer, StringBuilderPool builder)
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.LiquidTemplate.Render()
 ---> System.InvalidOperationException: Error while rendering Liquid template TypeScript/Client.RequestUrl:
Fluid.ParseException: '{% endif %}' was expected at (12:1)
   at Fluid.FluidParserExtensions.Parse(FluidParser parser, String template)
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.LiquidTemplate.<Render>b__12_0(ValueTuple`2 _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.LiquidTemplate.Render()
 ---> Fluid.ParseException: '{% endif %}' was expected at (12:1)
   at Fluid.FluidParserExtensions.Parse(FluidParser parser, String template)
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.LiquidTemplate.<Render>b__12_0(ValueTuple`2 _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.LiquidTemplate.Render()
   --- End of inner exception stack trace ---
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.LiquidTemplate.Render()
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.LiquidParser.RenderTemplate(List`1 arguments, TextWriter writer, TextEncoder encoder, TemplateContext context)
   at Fluid.Parser.ParserTagStatement`1.WriteToAsync(TextWriter writer, TextEncoder encoder, TemplateContext context)
   at Fluid.Ast.ForStatement.WriteToAsync(TextWriter writer, TextEncoder encoder, TemplateContext context)
   at Fluid.Ast.IfStatement.Awaited(ValueTask`1 conditionTask, ValueTask`1 incompleteStatementTask, TextWriter writer, TextEncoder encoder, TemplateContext context, Int32 statementStartIndex)
   at Fluid.Parser.FluidTemplate.Awaited(ValueTask`1 task, TextWriter writer, TextEncoder encoder, TemplateContext context, IReadOnlyList`1 statements, Int32 startIndex)
   at Fluid.FluidTemplateExtensions.<RenderAsync>g__Awaited|3_0(ValueTask task, StringWriter writer, StringBuilderPool builder)
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.LiquidTemplate.Render()
   --- End of inner exception stack trace ---
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.LiquidTemplate.Render()
   at NJsonSchema.CodeGeneration.CodeArtifact..ctor(String typeName, CodeArtifactType type, CodeArtifactLanguage language, CodeArtifactCategory category, ITemplate template)
   at NSwag.CodeGeneration.TypeScript.TypeScriptClientGenerator.GenerateClientTypes(String controllerName, String controllerClassName, IEnumerable`1 operations)+MoveNext() in D:\SpitfireDev\NSwag\src\NSwag.CodeGeneration.TypeScript\TypeScriptClientGenerator.cs:line 112
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at NSwag.CodeGeneration.ClientGeneratorBase`3.GenerateAllClientTypes() in D:\SpitfireDev\NSwag\src\NSwag.CodeGeneration\ClientGeneratorBase.cs:line 117
   at NSwag.CodeGeneration.ClientGeneratorBase`3.GenerateFile(ClientGeneratorOutputType outputType) in D:\SpitfireDev\NSwag\src\NSwag.CodeGeneration\ClientGeneratorBase.cs:line 73
   at NSwag.CodeGeneration.ClientGeneratorBase`3.GenerateFile() in D:\SpitfireDev\NSwag\src\NSwag.CodeGeneration\ClientGeneratorBase.cs:line 65
   at APIClientGenerator.Program.Main(String[] args) in D:\SpitfireDev\TypeScriptClientGenerator\Program.cs:line 124
   at APIClientGenerator.Program.<Main>(String[] args)
```

[sf-swagger-8048.zip](https://github.com/RicoSuter/NSwag/files/7873650/sf-swagger-8048.zip)

**Code from C# generator** 

```csharp
var settings = new NSwag.CodeGeneration.TypeScript.TypeScriptClientGeneratorSettings
{
	ClassName = "{controller}Client",
	Template = TypeScriptTemplate.JQueryPromises,
	PromiseType = PromiseType.Promise,
	HttpClass = HttpClass.HttpClient,
	WithCredentials = false,
	UseSingletonProvider = false,
	InjectionTokenType = InjectionTokenType.OpaqueToken,
	RxJsVersion = 6.0M,
	GenerateClientClasses = true,
	GenerateClientInterfaces = false,
	WrapDtoExceptions = false,
	GenerateOptionalParameters = true,
	ExceptionClass = "ApiException",
	ClientBaseClass = "APIClientBase",
	WrapResponses = false,
	WrapResponseMethods = Array.Empty<string>(),
	GenerateResponseClasses = true,
	ResponseClass = "SwaggerResponse",
	ProtectedMethods = Array.Empty<string>(),
	ExcludedParameterNames = Array.Empty<string>(),
	ConfigurationClass = "",
	UseTransformOptionsMethod = false,
	UseTransformResultMethod = false,
	ImportRequiredTypes = true,
	UseGetBaseUrlMethod = true,
	//BaseUrlTokenName = "API_BASE_URL", // angular
	QueryNullValue = "",
	UseAbortSignal = false,
	//serviceHost = null,
	//serviceSchemes= null,
	//output = "src/SwaggerClients.ts",
	//newLineBehavior = "Auto"

	TypeScriptGeneratorSettings =
	{
		TypeScriptVersion = 2.7M,
		//propertyNameGeneratorType= null,  
		PropertyNameGenerator = UseNameGenerator,
		DateTimeType =  TypeScriptDateTimeType.Date,
		NullValue  = TypeScriptNullValue.Undefined,
		ExportTypes= true,
		//generateDtoTypes": true,
		//operationGenerationMode = "MultipleClientsFromOperationId",
		MarkOptionalProperties = true,
		GenerateCloneMethod=  true,
		TypeStyle =  TypeScriptTypeStyle.Class,
		EnumStyle = TypeScriptEnumStyle.Enum ,
		UseLeafType = false,
		ClassTypes=  Array.Empty<string>(),
		ExtendedClasses = Array.Empty<string>(),
		ExtensionCode =  "import { APIClientBase } from './APIClientBase';",
		GenerateDefaultValues = true,
		ExcludedTypeNames= Array.Empty<string>(),
		HandleReferences=  false,
		GenerateConstructorInterface = true,
		ConvertConstructorInterfaceData = false,
		InlineNamedAny = false,
		InlineNamedDictionaries= false,
		TemplateDirectory = null
		//typeNameGeneratorType = null,
		//enumNameGeneratorType= null,
	}
};

var resolver = new TypeScriptTypeResolver(settings.TypeScriptGeneratorSettings);
var generator = new NSwag.CodeGeneration.TypeScript.TypeScriptClientGenerator(document, settings, resolver);
var client = generator.GenerateFile();
```

**Comment by lahma** [comment]
Are you using a custom template? This error usually means that you have used `elseif` instead of correct Liquid syntax `elsif`.

**Comment by stanyork** [comment]
I may be answering the wrong question, but I believe that setting 

**TemplateDirectory = null** 

in TypeScriptGeneratorSettings means that I am using the default templates.

**Comment by lahma** [comment]
Tried with the attached file in NSwagStudio but didn't get an error.

**Comment by stanyork** [comment]
Ditto.  (nswag settings file attached).
The only difference is that the custom client builder includes

PropertyNameGenerator = (IPropertyNameGenerator)new CustomRespectSwaggerPropertyNameGenerator(), defined as below.

Is there a way to provide a **PropertyNameGenerator**  now in NSwagStudio?

`public class CustomRespectSwaggerPropertyNameGenerator : IPropertyNameGenerator
{
    /// <summary>Generates the property name.</summary>
    /// <param name="property">The property.</param>
    /// <returns>The new name.</returns>
    string IPropertyNameGenerator.Generate(JsonSchemaProperty property)
    {
        return property.Name.Replace('_', '_')
            .Replace("@", "")
            .Replace(".", "-") ;
    }
}`

**Comment by lahma** [comment]
So the problem goes away if you disable your custom generator? Still the error seems to be related to markup and not the generated property name.

**Comment by stanyork** [comment]
No, as expected the custom generator does not matter.
I went through DLL by DLL and found the difference between my BIN and NSwagStudio, then tracked it back.

My NuGet packages **were** NSwag.Core + **NJsonSchema**.CodeGeneration + **NJsonSchema**.CodeGeneration.Typescript

Changed NuGet packages to NSwag.Code + NSwag.CodeGeneration + NSwag.CodeGeneration.TypeScript.

Working again now!
