### ISSUE TITLE
Error: The method 'post' on path '/{controller}' is registered multiple times.

### ISSUE THREAD

**Issue by Chris-Thompson-bnsf** [RicoSuter/NSwag#3861]
NSwag.AspNetCore 13.15.7 (also tested 13.15.5, same issue)
ASP.Net Core 6.0.1 
- NOT using the minimal API, using Program.cs + Startup.cs

I am working on upgrading an ASP.NET Framework application over to ASP.NET 6.0, and in doing so, I've run into this error when generating the swagger document for the API:
> Error [0]: System.InvalidOperationException: The method 'post' on path '/{controller}' is registered multiple times.
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.AddOperationDescriptionsToDocument(OpenApiDocument document, Type controllerType, List`1 operations, OpenApiDocumentGenerator swaggerGenerator, OpenApiSchemaResolver schemaResolver)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateApiGroups(OpenApiDocument document, IGrouping`2[] apiGroups, OpenApiSchemaResolver schemaResolver)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateAsync(ApiDescriptionGroupCollection apiDescriptionGroups)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GenerateDocumentAsync(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GetDocumentAsync(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
   at App.Middleware.Logging.ExceptionLoggingMiddleware.HandleRequestAsync(HttpContext context) in C:\Git\App\Net6\App\Middleware\Logging\ExceptionLoggingMiddleware.cs:line 26

Clearly, this is an issue in our app code, but the problem is difficult to track down, because the route template variable `{controller}` doesn't tell me which controller (or in this case, controller**S**) have the route conflict.

This project has a large number of controllers (around 80), and so we are using a custom base class. I have decorated this base controller class with the following attributes:
```csharp
[ApiController]
[Route("{controller}")]
[ApiExplorerSettings(GroupName = Api1GroupName)]
```

Note - `ApiGroupName` is a constant which is used to differentiate which controllers go to which Swagger document (we have 2). This issue is only present with one of the documents.

Is there a more effective way I could investigate this issue, aside from reviewing probably 500 action methods across 80 or so controller files?

#### Startup.ConfigureServices
```csharp
services.AddControllersWithViews(ConfigureMvcOptions)
  .AddNewtonsoftJson(options =>
  {
	  options.UseCamelCasing(false);
	  options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
	  options.SerializerSettings.ContractResolver =
		  new CamelCasePropertyNamesContractResolver();
	  options.SerializerSettings.DateFormatHandling =
		  DateFormatHandling.IsoDateFormat;
  
  })
  .AddXmlSerializerFormatters()
  .AddControllersAsServices();

// doc 1
services.AddSwaggerDocument(
document =>
{
	document.DocumentName = SwaggerDocNames.Api1;
	document.ApiGroupNames = new[] { ControllerBase.Api1GroupName, };
});

// doc2 - this one is working just fine
services.AddSwaggerDocument(
document =>
{
	document.DocumentName = SwaggerDocNames.Api2;
	document.ApiGroupNames = new[] { ControllerBase.Api2GroupName, };
});
```

#### Startup.Configure
```csharp
app.UseHttpLogging();

if (env.IsDevelopment())
{
app.UseDeveloperExceptionPage();
}
else
{
app.UseCustomExceptionHandler();
}

app.UseStaticFiles();

app.UseExceptionLogging();

app.UseOpenApi();
app.UseSwaggerUi3();

app.UseRouting();
app.UseAuthentication();
app.UseAuthorization();

app.UseSession();

app.UseEndpoints(endpoints =>
{
  endpoints.MapHealthChecks("app/health");
  
  endpoints.MapControllerRoute(
	  name: "default",
	  pattern: "{controller=Home}/{action=Index}/{id?}");
  
  endpoints.MapControllers().RequireAuthorization();
});
```

## Suggested Change
- Would it be possible to update this InvalidOperationException to use the replaced {controller} template name with the value(s) which have the conflicts? 

- If not, could either a custom exception or maybe just the Exception.Data dictionary be used to give some additional context to help track down this issue?

**Comment by Chris-Thompson-bnsf** [comment]
Well I just figured something interesting out - when I update the base class to instead use `[Route("[controller]")]`, the swagger page loads just fine.

However, ASP.NET Core seems to support either syntax in attribute routing:
`[Route("[controller]")]`
`[Route("{controller}")]`
