### ISSUE TITLE
$ref in Path item fails when using Uri without fragment

### ISSUE THREAD

**Issue by hmadrigal** [RicoSuter/NSwag#3930]
Hello, 

I think there might be a bug when using `$ref` to load remote references without a fragment.  This only happens in `Path Items`, In other sections, such as schemas, it works as expected.

## Issue

In order to illustrate the issue, the test is simple. The example loads an OpenApi Spec from file `path-reference.json` and this file has a Path Item which uses `$ref` to load file `common.json`.  The C# code only gets an exception when calling `OpenApiDocument.FromFileAsync("path-reference.json");`

Here is a sample project with the test https://gitlab.com/hmadrigal/test-project-nswag or you can take a look at them as follows:

```csharp
       [Test]
        public async Task When_file_contains_path_reference_without_fragment_to_another_file_it_is_loaded()
        {
            var document = await OpenApiDocument.FromFileAsync("path-reference.json");

            Assert.NotNull(document);
            Assert.AreEqual("External path", document.Paths.First().Value.ActualPathItem.Values.First().Description);
        }
```

`path-reference.json`
```json
{
  "openapi": "3.0.2",
  "paths": {
    "/reference/test": {
      "$ref": "./common.json"
    }
  }
}
```

`common.json`
```json
{
  "get": {
    "description": "External path",
    "responses": {
      "204": {
        "description": "Test."
      }
    }
  }
}
```

Produces the following exception
```log
System.InvalidCastException: 'Unable to cast object of type 'NJsonSchema.JsonSchema' to type 'NSwag.OpenApiPathItem'.'

System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'NJsonSchema.JsonSchema' to type 'NSwag.OpenApiPathItem'.
  Source=NSwag.Core
  StackTrace:
   at NSwag.OpenApiPathItem.NJsonSchema.References.IJsonReferenceBase.set_Reference(IJsonReference value) in C:\projects\github\NSwag\src\NSwag.Core\OpenApiPathItem.cs:line 95
   at NJsonSchema.JsonSchemaReferenceUtilities.JsonReferenceUpdater.<VisitJsonReferenceAsync>d__6.MoveNext()
```

## Expected behavior
Referenced JSON document should replace the de value of the Path Item Object in `path-reference.json`.

## Note
If the Json Reference is changed to use fragment, then it works as expected. 

``path-reference.json``
```json
{
  "openapi": "3.0.2",
  "paths": {
    "/reference/test": {
      "$ref": "./common.json#/paths/foo"
    }
  }
}
```

`common.json`
```json
{
  "paths": {
    "foo": {
      "get": {
        "description": "External path",
        "responses": {
          "204": {
            "description": "Test."
          }
        }
      }
    }
  }
}
```

**Comment by Meddington** [comment]
I did some debugging of this issue and, to me, it looks like a NJsonSchema issue. Essentially during the reference resolution, a `Type targetType` is getting passed through asking for an `OpenApiPathItem` object type. When a fragement is used (`./filename#path`) we end up in `ResolveFileReferenceWithAlreadyResolvedCheckAsync` and call `ResolveReferenceAsync`. However when no fragement provided, `referencedFile` is returned without being turned into the `targetType` type first.

I made a change that made this example work, but broke a bunch of the NJsonSchema tests.

In this change we detect `targetType` is non-null and use the logic from `ResolveDocumentReferenceWithoutDereferencing` to return the expected type.

This code could also be placed into NSwag's `OpenApiPathItem` in the setter line that's exceptioning.

```csharp
        private async Task<IJsonReference> ResolveFileReferenceWithAlreadyResolvedCheckAsync(string filePath, Type targetType, IContractResolver contractResolver, string jsonPath, bool append, CancellationToken cancellationToken)
        {
            try
            {
                var fullPath = DynamicApis.GetFullPath(filePath);
                var arr = Regex.Split(jsonPath, @"(?=#)");

                fullPath = DynamicApis.HandleSubdirectoryRelativeReferences(fullPath, jsonPath);

                if (!_resolvedObjects.ContainsKey(fullPath))
                {
                    var loadedFile = await ResolveFileReferenceAsync(fullPath).ConfigureAwait(false);
                    loadedFile.DocumentPath = arr[0];
                    _resolvedObjects[fullPath] = loadedFile;
                }

                var referencedFile = _resolvedObjects[fullPath];
                IJsonReference resolvedSchema = null;

                if (arr.Length == 2)
                {
                    resolvedSchema = await ResolveReferenceAsync(referencedFile, arr[1], targetType, contractResolver).ConfigureAwait(false);
                }
                else if (targetType != null)
                {
                    var extensionObject = referencedFile as IJsonExtensionObject;
                    var settings = new JsonSerializerSettings { ContractResolver = contractResolver };
                    var json = JsonConvert.SerializeObject(extensionObject.ExtensionData, settings);
                    resolvedSchema = (IJsonReference)JsonConvert.DeserializeObject(json, targetType, settings);
                }
                else
                {
                    resolvedSchema = referencedFile;
                }

                //var resolvedSchema = arr.Length == 1 ? referencedFile : await ResolveReferenceAsync(referencedFile, arr[1], targetType, contractResolver).ConfigureAwait(false);
                if (resolvedSchema is JsonSchema && append &&
                    (_schemaAppender.RootObject as JsonSchema)?.Definitions.Values.Contains(referencedFile) != true)
                {
                    var key = jsonPath.Split('/', '\\').Last().Split('.').First();
                    _schemaAppender.AppendSchema((JsonSchema)resolvedSchema, key);
                }

                return resolvedSchema;
            }
            catch (Exception exception)
            {
                throw new InvalidOperationException("Could not resolve the JSON path '" + jsonPath + "' within the file path '" + filePath + "'.", exception);
            }
        }
```

**Comment by Meddington** [comment]
Related to https://github.com/RicoSuter/NSwag/issues/3513

**Comment by joshcomley** [comment]
I am encountering this issue - is there any progress?
