### ISSUE TITLE
Unable to generate outputs with net6; InvalidOperationException 1

### ISSUE THREAD

**Issue by MaximeMorin-Devolutions** [RicoSuter/NSwag#3942]
Hello,

When generating for our project with net5, the generation is sucessful.  After switching the .net version in our project and updated libraries to net6.  The generation fails with the following stack trace.

```Launcher directory: C:\Program Files (x86)\Rico Suter\NSwagStudio\Net60
System.InvalidOperationException: Swagger generation failed with non-zero exit code '1'.

Runtime: Net60
   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in /_/src/NSwag.Commands/Commands/Generation/AspNetCore/AspNetCoreToOpenApiCommand.cs:line 231
   at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in /_/src/NSwag.Commands/NSwagDocumentBase.cs:line 275
   at NSwag.Commands.NSwagDocument.ExecuteAsync() in /_/src/NSwag.Commands/NSwagDocument.cs:line 81
   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in /_/src/NSwag.Commands/Commands/Document/ExecuteDocumentCommand.cs:line 85
   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in /_/src/NSwag.Commands/Commands/Document/ExecuteDocumentCommand.cs:line 32
   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.ProcessAsync(String[] args) in /_/src/NSwag.Commands/NSwagCommandProcessor.cs:line 61

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at NSwag.AspNetCore.Launcher.Program.Main(String[] args) in /_/src/NSwag.AspNetCore.Launcher/Program.cs:line 132
```

We are using API Explorer with a direct link to the project.  NSwagStudio is updated to the lastest 13.15.10.0.

![image](https://user-images.githubusercontent.com/78555854/159361581-d7033307-31c4-4a59-aa9f-c09ff1c30ac8.png)

If you need more information, let me know.

Have a good day!

**Comment by MaximeMorin-Devolutions** [comment]
By commenting out my project progressively, I found the culprint.  With our migration to net 6.0, we also upgraded our ServiceBus library as such.

```
            services.AddAzureClients(
                builder =>
                    {
                        builder.AddServiceBusClient(serviceBusConfigurationSection);
                        builder.AddServiceAdministrationBusClient(serviceBusConfigurationSection.Get<ServiceBus>().ConnectionString);
                    });
```

When running the generator, the configuration was null which caused the NPE aboved.  I simply added a ? before the .ConnectionString and voilà, everything's back to normal!
