### ISSUE TITLE
Unable to run NSwagExe_x86 or NSwagExe_Net60 for net6.0-windows x86 project

### ISSUE THREAD

**Issue by chriscameron-vertexinc** [RicoSuter/NSwag#4040]
Hello!

I have a, Asp.Net Core project with a hard dependency on Windows x86:

```
	<PropertyGroup>
		<TargetFramework>net6.0-windows</TargetFramework>
		<PlatformTarget>x86</PlatformTarget>
		<Platforms>x86</Platforms>
		<RuntimeIdentifier>win-x86</RuntimeIdentifier>
		<RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
	</PropertyGroup>
...
	<Target Name="NSwag" AfterTargets="PostBuildEvent">
                <Copy SourceFiles="@(Reference)" DestinationFolder="$(OutDir)References" />
		<Exec WorkingDirectory="$(ProjectDir)" EnvironmentVariables="ASPNETCORE_ENVIRONMENT=Development" Command="$(NSwagExe_x86) run nswag.json /variables:Configuration=$(Configuration)" />  
                <RemoveDir Directories="$(OutDir)References" />
	</Target>
```

Running NSwagExe_x86 I get:

```
Executing file 'nswag.json' with variables 'Configuration=Debug'...
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.AspNetCore.Mvc.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

Server stack trace: 
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at System.Reflection.Assembly.get_ExportedTypes()
   at NSwag.Commands.ServiceProviderResolver.GetServiceProvider(Assembly assembly)
   at NSwag.Commands.Generation.OpenApiGeneratorCommandBase`1.GetServiceProvider(AssemblyLoader assemblyLoader)
   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.<RunIsolatedAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.IsolatedCommandBase`1.IsolatedCommandAssemblyLoader.Run(String commandType, String commandData, String[] assemblyPaths, String[] referencePaths)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
```

If I modify the *Copy* action:
`<Copy SourceFiles="@(Reference)" DestinationFolder="$(OutDir)" />`

I get:

```
Executing file 'nswag.json' with variables 'Configuration=Debug'...
System.BadImageFormatException: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)
File name: 'Microsoft.AspNetCore.Mvc.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' ---> System.BadImageFormatException: Cannot load a reference assembly for execution.


Server stack trace: 
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at System.Reflection.Assembly.get_ExportedTypes()
   at NSwag.Commands.ServiceProviderResolver.GetServiceProvider(Assembly assembly)
   at NSwag.Commands.Generation.OpenApiGeneratorCommandBase`1.GetServiceProvider(AssemblyLoader assemblyLoader)
   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.<RunIsolatedAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.IsolatedCommandBase`1.IsolatedCommandAssemblyLoader.Run(String commandType, String commandData, String[] assemblyPaths, String[] referencePaths)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
```

If I try with NSwagExe_Net60, either way I get:

```
Executing file 'nswag.json' with variables 'Configuration=Debug'...
System.IO.FileLoadException: Could not load file or assembly 'MyProject, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at NSwag.Commands.IsolatedSwaggerOutputCommandBase`1.<>c__DisplayClass14_0.<LoadAssemblies>b__0(String path) in /_/src/NSwag.Commands/Commands/IsolatedSwaggerOutputCommandBase.cs:line 65
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at NSwag.Commands.IsolatedSwaggerOutputCommandBase`1.LoadAssemblies(IEnumerable`1 assemblyPaths, AssemblyLoader assemblyLoader) in /_/src/NSwag.Commands/Commands/IsolatedSwaggerOutputCommandBase.cs:line 64
   at NSwag.Commands.Generation.OpenApiGeneratorCommandBase`1.GetServiceProvider(AssemblyLoader assemblyLoader) in /_/src/NSwag.Commands/Commands/Generation/OpenApiGeneratorCommandBase.cs:line 311
   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.RunIsolatedAsync(AssemblyLoader assemblyLoader) in /_/src/NSwag.Commands/Commands/Generation/AspNetCore/AspNetCoreToOpenApiCommand.cs:line 323
   at NSwag.Commands.IsolatedCommandBase`1.IsolatedCommandAssemblyLoader.Run(String commandType, String commandData, String[] assemblyPaths, String[] referencePaths) in /_/src/NSwag.Commands/Commands/IsolatedCommandBase.cs:line 76
   at NSwag.Commands.IsolatedCommandBase`1.RunIsolatedAsync(String configurationFile) in /_/src/NSwag.Commands/Commands/IsolatedCommandBase.cs:line 61
   at NSwag.Commands.IsolatedSwaggerOutputCommandBase`1.RunAsync(CommandLineProcessor processor, IConsoleHost host) in /_/src/NSwag.Commands/Commands/IsolatedSwaggerOutputCommandBase.cs:line 51
   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in /_/src/NSwag.Commands/Commands/Generation/AspNetCore/AspNetCoreToOpenApiCommand.cs:line 98
   at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in /_/src/NSwag.Commands/NSwagDocumentBase.cs:line 275
   at NSwag.Commands.NSwagDocument.ExecuteAsync() in /_/src/NSwag.Commands/NSwagDocument.cs:line 81
   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in /_/src/NSwag.Commands/Commands/Document/ExecuteDocumentCommand.cs:line 85
   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in /_/src/NSwag.Commands/Commands/Document/ExecuteDocumentCommand.cs:line 32
   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.ProcessAsync(String[] args) in /_/src/NSwag.Commands/NSwagCommandProcessor.cs:line 61
```

I get the impression that Net60 won't work because I'm not building for x64 (I actually have Net60 working for regular projects). For some reason NSwagExe_x86 is unable to resolve the Microsoft.AspNetCore.Mvc.Core dll, and if I output the dll to the output directory it resolves but can't be executed.

What is the correct way to run NSwagExe on post build for an x86 .Net 6 project?

**Comment by RicoSuter** [comment]
Did you try NSwagExe_Net60?

**Comment by Aaron-Redmond** [comment]
I have the similar error when building a 3.1 project targeting x86 but it cannot resolve 
Microsoft.AspNetCore.Http.Abstractions, Version=3.1.0.0, 

csproj:
`
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <Configurations>Debug;Release</Configurations>
    <Platforms>x86</Platforms>
  </PropertyGroup>
...
<Target Name="NSwag" AfterTargets="Build">
    <Copy SourceFiles="@(Reference)" DestinationFolder="$(OutDir)References" />
    <Exec Command="$(NSwagExe_x86) run NSwag/Services.nswag /variables:Configuration=$(Configuration)" />
    <RemoveDir Directories="$(OutDir)References" />
  </Target>
`

The output from nswag is
`
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Http.Abstractions, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.AspNetCore.Http.Abstractions, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

Server stack trace:
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at System.Reflection.Assembly.get_ExportedTypes()
   at NSwag.Generation.WebApi.WebApiOpenApiDocumentGenerator.GetControllerClasses(Assembly assembly)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at NSwag.Commands.Generation.WebApi.WebApiToSwaggerCommand.GetControllerNames(AssemblyLoader assemblyLoader)
   at NSwag.Commands.Generation.WebApi.WebApiToSwaggerCommand.<RunIsolatedAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.IsolatedCommandBase`1.IsolatedCommandAssemblyLoader.Run(String commandType, String commandData, String[] assemblyPaths, String[] referencePaths)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
`

**Comment by chriscameron-vertexinc** [comment]
What I have ultimately ended up doing as a workaround is writing the Swagger JSON to disk and running NSwag against that instead.

I added the following to my WebApplication Startup:

```csharp
if (app.Configuration.GetValueAsBoolean("GenerateSwaggerJson"))
{
    var generator = app.Services.GetRequiredService<IOpenApiDocumentGenerator>();
    var document = await generator.GenerateAsync("v1");
    var swagger = document.ToJson();
    var path = Path.Combine(Path.GetDirectoryName(typeof(T).Assembly.Location)!, "swagger.json");
    await File.WriteAllTextAsync(path, swagger);

    app.Lifetime.StopApplication();
    return;
}
```

I modified my NSwag configuration to use `fromDocument` instead of `aspNetCoreToOpenApi`:

```json
...
  "runtime": "Net60",
  "defaultVariables": null,
  "documentGenerator": {
    "fromDocument": {
      "json": "bin/x86/$(Configuration)/net6.0-windows/swagger.json"
    }
  },
  "codeGenerators": {
...
```

And finally my post-build step:

```xml
	<!-- x86 is currently broken? https://github.com/RicoSuter/NSwag/issues/4040 -->
	<!--<Target Name="NSwag" AfterTargets="PostBuild">
		<Exec Command="$(NSwagExe_Net60) run nswag.json /variables:Configuration=$(Configuration)" />
	</Target>-->
	<Target Name="NSwag" AfterTargets="PostBuild">
		<!-- Generate swagger.json document -->
		<Exec Command="$(MSBuildProjectDirectory)\$(OutputPath)$(AssemblyName).exe GenerateSwaggerJson=true" />
		<!-- Generate client -->
		<Exec Command="$(NSwagExe_Net60) run nswag.json /variables:Configuration=$(Configuration)" />
	</Target>
```

This is working great for both local development and CI/CD.

**Comment by shtefanntz** [comment]
@chriscameron-vertexinc for me it worked when i switched to NSwagExe_Net60
