### ISSUE TITLE
Can't Successfully Generate .Net 6 Web API C# Client

### ISSUE THREAD

**Issue by kingua** [RicoSuter/NSwag#4189]
I'm having trouble getting a C# client to generate in .Net 6 which worked in .Net Core 3.1

I'm not sure how to find out what 'uriString' is missing.  

We are using Azure App Configuration and have excluded that in previous (.Net Core 3.1) client builds.  I don't know if that is required or not, but when doing so, the client build also fails, saying it can't connect to Azure App Config.  In the details below, we are NOT excluding Azure App Configuration during the client build.

We are also using Azure B2C authentication (which doesn't seem to be causing any issues)

It would be greatly appreciated if anything jumps out in the below scenario as leading to the issue or some help/suggestions in how to troubleshoot issues like this.

Thanks!

**Error:**
```
Executing file 'nswag.json' with variables 'Configuration=Debug,ClientOutDir=../Hth.AdessoEngine.App.Client.V1/Client.cs,ClientNamespace=Hth.AdessoEngine.App.Client.V1,MSBuildProjectFullPath=C:\Source\Repos\src\Hth.AdessoEngine.App\Hth.AdessoEngine.App.csproj,ClientClassNamePrefix=AdessoEngineApiV1'...
Launcher directory: C:\Users\Gari\.nuget\packages\nswag.msbuild\13.17.0\tools\Net60
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'uriString')
   at System.Uri..ctor(String uriString)
   at Hth.AdessoEngine.App.AppConfigExtensions.<>c__DisplayClass0_0.<ConfigureApp>b__0(AzureAppConfigurationOptions opt) in C:\Source\Repos\src\Hth.AdessoEngine.App\AppConfigExtensions.cs:line 76
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationSource.<>c__DisplayClass3_0.<.ctor>b__0()
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationManager.AddSource(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.ConfigurationManager.Microsoft.Extensions.Configuration.IConfigurationBuilder.Add(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.AzureAppConfigurationExtensions.AddAzureAppConfiguration(IConfigurationBuilder configurationBuilder, Action`1 action, Boolean optional)
   at Hth.AdessoEngine.App.AppConfigExtensions.ConfigureApp(IConfigurationBuilder configBuilder, Action`1 configOptions) in C:\Source\Repos\src\Hth.AdessoEngine.App\AppConfigExtensions.cs:line 66
   at Program.<>c.<<Main>$>b__0_0(IConfigurationBuilder builder) in C:\Source\Repos\src\Hth.AdessoEngine.App\Program.cs:line 27
   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.<>c__DisplayClass8_0.<ConfigureAppConfiguration>b__0(HostBuilderContext context, IConfigurationBuilder builder)
   at Microsoft.AspNetCore.Builder.ConfigureHostBuilder.ConfigureAppConfiguration(Action`2 configureDelegate)
   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.ConfigureAppConfiguration(IHostBuilder hostBuilder, Action`1 configureDelegate)
   at Program.<Main>$(String[] args) in C:\Source\Repos\src\Hth.AdessoEngine.App\Program.cs:line 20
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Hosting.HostFactoryResolver.HostingListener.CreateHost() in /_/src/NSwag.Commands/HostFactoryResolver.cs:line 271
   at Microsoft.Extensions.Hosting.HostFactoryResolver.<>c__DisplayClass8_0.<ResolveHostFactory>b__0(String[] args) in /_/src/NSwag.Commands/HostFactoryResolver.cs:line 75
   at NSwag.Commands.ServiceProviderResolver.GetServiceProviderWithHostFactoryResolver(Assembly assembly) in /_/src/NSwag.Commands/HostApplication.cs:line 146
   at NSwag.Commands.ServiceProviderResolver.GetServiceProvider(Assembly assembly) in /_/src/NSwag.Commands/HostApplication.cs:line 70
   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToOpenApiGeneratorCommandEntryPoint.Process(String commandContent, String outputFile, String applicationName) in /_/src/NSwag.Commands/Commands/Generation/AspNetCore/AspNetCoreToOpenApiGeneratorCommandEntryPoint.cs:line 27
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at NSwag.AspNetCore.Launcher.Program.Main(String[] args) in /_/src/NSwag.AspNetCore.Launcher/Program.cs:line 132
System.InvalidOperationException: Swagger generation failed with non-zero exit code '1'.
   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in /_/src/NSwag.Commands/Commands/Generation/AspNetCore/AspNetCoreToOpenApiCommand.cs:line 231
   at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in /_/src/NSwag.Commands/NSwagDocumentBase.cs:line 275
   at NSwag.Commands.NSwagDocument.ExecuteAsync() in /_/src/NSwag.Commands/NSwagDocument.cs:line 81
   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in /_/src/NSwag.Commands/Commands/Document/ExecuteDocumentCommand.cs:line 85
   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in /_/src/NSwag.Commands/Commands/Document/ExecuteDocumentCommand.cs:line 32
   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.ProcessAsync(String[] args) in /_/src/NSwag.Commands/NSwagCommandProcessor.cs:line 61
```

**MS Build in Project File:**
```
  <Target Name="ApiClientGenerate" AfterTargets="Build" Condition="'$(SkipNswagClientGeneration)' != 'true'">
    <Copy SourceFiles="@(ReferencePath)" DestinationFolder="$(OutDir)References" />
    <Exec WorkingDirectory="$(MSBuildProjectDirectory)" Command="$(NSwagExe_Net60) run nswag.json /variables:Configuration=$(Configuration),ClientOutDir=../Hth.AdessoEngine.App.Client.V1/Client.cs,ClientNamespace=Hth.AdessoEngine.App.Client.V1,MSBuildProjectFullPath=$(MSBuildProjectFullPath),ClientClassNamePrefix=AdessoEngineApiV1" />
    <RemoveDir Directories="$(OutDir)References" />
  </Target>
```

**Program.cs:**
```
// Configure Swagger (NSwag)
builder.Services.AddOpenApiDocument(doc =>
{
    doc.DocumentName = "v1";
    doc.Version = "v1";
    doc.Title = "AdessoEngine API";
    doc.ApiGroupNames = new[] { "v1" };
    doc.AddSecurity("bearer", Enumerable.Empty<string>(), new OpenApiSecurityScheme
    {
        Type = OpenApiSecuritySchemeType.OAuth2,
        Description = "B2C authentication",
        Flow = OpenApiOAuth2Flow.Implicit,
        Flows = new OpenApiOAuthFlows()
        {
            Implicit = new OpenApiOAuthFlow()
            {
                Scopes = new Dictionary<string, string>
                {
                    ///
                },
                AuthorizationUrl = ///,
                TokenUrl = ///"
            }
        }
    });

    doc.OperationProcessors.Add(new AspNetCoreOperationSecurityScopeProcessor("bearer"));
});

...

app.UseOpenApi();
app.UseSwaggerUi3(settings =>
{
    settings.OAuth2Client = new OAuth2ClientSettings
    {
        ClientId = ///,
        AppName = ///
    };
});
```
**nswag.json:**
```
{
  "runtime": "Net60",
  "defaultVariables": null,
  "documentGenerator": {
    "aspNetCoreToOpenApi": {
      "project": "$(MSBuildProjectFullPath)",
      "msBuildProjectExtensionsPath": null,
      "configuration": "$(Configuration)",
      "runtime": "",
      "targetFramework": "",
      "noBuild": true,
      "msBuildOutputPath": null,
      "verbose": true,
      "workingDirectory": null,
      "requireParametersWithoutDefault": false,
      "apiGroupNames": null,
      "defaultPropertyNameHandling": "Default",
      "defaultReferenceTypeNullHandling": "Null",
      "defaultDictionaryValueReferenceTypeNullHandling": "NotNull",
      "defaultResponseReferenceTypeNullHandling": "NotNull",
      "generateOriginalParameterNames": true,
      "defaultEnumHandling": "Integer",
      "flattenInheritanceHierarchy": false,
      "generateKnownTypes": true,
      "generateEnumMappingDescription": false,
      "generateXmlObjects": false,
      "generateAbstractProperties": false,
      "generateAbstractSchemas": true,
      "ignoreObsoleteProperties": false,
      "allowReferencesWithProperties": false,
      "useXmlDocumentation": true,
      "resolveExternalXmlDocumentation": true,
      "excludedTypeNames": [],
      "serviceHost": null,
      "serviceBasePath": null,
      "serviceSchemes": [],
      "infoTitle": "My Title",
      "infoDescription": null,
      "infoVersion": "1.0.0",
      "documentTemplate": null,
      "documentProcessorTypes": [],
      "operationProcessorTypes": [],
      "typeNameGeneratorType": null,
      "schemaNameGeneratorType": null,
      "contractResolverType": null,
      "serializerSettingsType": null,
      "useDocumentProvider": true,
      "documentName": "v1",
      "aspNetCoreEnvironment": "Local",
      "createWebHostBuilderMethod": null,
      "startupType": null,
      "allowNullableBodyParameters": true,
      "useHttpAttributeNameAsOperationId": false,
      "output": null,
      "outputType": "Swagger2",
      "newLineBehavior": "Auto",
      "assemblyPaths": [],
      "assemblyConfig": null,
      "referencePaths": [],
      "useNuGetCache": false
    }
  },
  "codeGenerators": {
    "openApiToCSharpClient": {
      "clientBaseClass": null,
      "configurationClass": null,
      "generateClientClasses": true,
      "generateClientInterfaces": true,
      "clientBaseInterface": "IAdessoEngineApiClient",
      "injectHttpClient": true,
      "disposeHttpClient": true,
      "protectedMethods": [],
      "generateExceptionClasses": true,
      "exceptionClass": "ApiException",
      "wrapDtoExceptions": true,
      "useHttpClientCreationMethod": false,
      "httpClientType": "System.Net.Http.HttpClient",
      "useHttpRequestMessageCreationMethod": false,
      "useBaseUrl": true,
      "generateBaseUrlProperty": true,
      "generateSyncMethods": false,
      "generatePrepareRequestAndProcessResponseAsAsyncMethods": false,
      "exposeJsonSerializerSettings": false,
      "clientClassAccessModifier": "public",
      "typeAccessModifier": "public",
      "generateContractsOutput": false,
      "contractsNamespace": null,
      "contractsOutputFilePath": null,
      "parameterDateTimeFormat": "s",
      "parameterDateFormat": "yyyy-MM-dd",
      "generateUpdateJsonSerializerSettingsMethod": true,
      "useRequestAndResponseSerializationSettings": false,
      "serializeTypeInformation": false,
      "queryNullValue": "",
      "className": "{controller}Client",
      "operationGenerationMode": "MultipleClientsFromFirstTagAndOperationId",
      "additionalNamespaceUsages": [],
      "additionalContractNamespaceUsages": [],
      "generateOptionalParameters": false,
      "generateJsonMethods": false,
      "enforceFlagEnums": false,
      "parameterArrayType": "System.Collections.Generic.IEnumerable",
      "parameterDictionaryType": "System.Collections.Generic.IDictionary",
      "responseArrayType": "System.Collections.Generic.ICollection",
      "responseDictionaryType": "System.Collections.Generic.IDictionary",
      "wrapResponses": false,
      "wrapResponseMethods": [],
      "generateResponseClasses": true,
      "responseClass": "SwaggerResponse",
      "namespace": "$(ClientNamespace)",
      "requiredPropertiesMustBeDefined": true,
      "dateType": "System.DateTimeOffset",
      "jsonConverters": null,
      "anyType": "object",
      "dateTimeType": "System.DateTimeOffset",
      "timeType": "System.TimeSpan",
      "timeSpanType": "System.TimeSpan",
      "arrayType": "System.Collections.Generic.ICollection",
      "arrayInstanceType": "System.Collections.ObjectModel.Collection",
      "dictionaryType": "System.Collections.Generic.IDictionary",
      "dictionaryInstanceType": "System.Collections.Generic.Dictionary",
      "arrayBaseType": "System.Collections.ObjectModel.Collection",
      "dictionaryBaseType": "System.Collections.Generic.Dictionary",
      "classStyle": "Poco",
      "jsonLibrary": "NewtonsoftJson",
      "generateDefaultValues": true,
      "generateDataAnnotations": true,
      "excludedTypeNames": [],
      "excludedParameterNames": [],
      "handleReferences": false,
      "generateImmutableArrayProperties": false,
      "generateImmutableDictionaryProperties": false,
      "jsonSerializerSettingsTransformationMethod": null,
      "inlineNamedArrays": false,
      "inlineNamedDictionaries": false,
      "inlineNamedTuples": true,
      "inlineNamedAny": false,
      "generateDtoTypes": true,
      "generateOptionalPropertiesAsNullable": false,
      "generateNullableReferenceTypes": false,
      "templateDirectory": null,
      "typeNameGeneratorType": null,
      "propertyNameGeneratorType": null,
      "enumNameGeneratorType": null,
      "serviceHost": null,
      "serviceSchemes": null,
      "newLineBehavior": "Auto",
      "output": "$(ClientOutDir)"
    }
  }
}
```

**Comment by kingua** [comment]
It seems that it IS an issue w/ Azure App Config (I think).  If I put in the following to exclude Azure App Config during NSwag client generation, then the build complains that Azure App Config can't be reached (although, this worked in other .Net Core 3.1 applications).

```
if (IsRunningForNswagCodegen())
{
    return configBuilder;
}
    
configBuilder.AddAzureAppConfiguration(opt =>
{
    /// configure app config
}        

public static bool IsRunningForNswagCodegen()
{
    return System.Reflection.Assembly.GetEntryAssembly().FullName.ToLowerInvariant().Contains("nswag");
}
```

If I don't do the above, that's where the System.ArgumentNullException: Value cannot be null. (Parameter 'uriString') error gets thrown, which per the stack trace, seems to be when actually connecting to Azure App Config.

So, it seems something has potentially changed in the application lifecycle between .Net Core 3.1 and .Net 6 (with the removal of Startup.cs perhaps) and I need to find a different way to either keep Azure App Config in the code execution during NSwag client gen or find out how to exclude it successfully...

Unless I'm following a red-herring...

**Comment by kingua** [comment]
Issue Resolved!  I needed to add the inverse check for NSWAG in Program.cs

```
if (!AppConfigExtensions.IsRunningForNswagCodegen())
{
    app.UseAzureAppConfiguration();
}
```
