### ISSUE TITLE
Exception generating client from spec with tuples

### ISSUE THREAD

**Issue by altxt** [RicoSuter/NSwag#4229]
NSwagStudio 13.17.00
Generating a TypeScript client from a specification that contains a schema where `items` property of an array is represented by an array produces an exception. This is not valid syntax in OpenAPI 3.0 schema according to https://swagger.io/specification/#schema-object (*items - Value MUST be an object and not an array*), but the error message is generic and does not help to understand the problem.

**Specification**
```
{
    "openapi": "3.0.2",
    "info": {
        "title": "asd",
        "version": "1.0"
    },
    "paths": {
        "/": {
            "get": {
                "responses": {
                    "200": {
                        "description": "Successful Response"
                    },
                }
            }
        }
    },
    "components": {
        "schemas": {
            "Type1": {
                "type": "object",
                "properties": {
                    "Elements": {
                        "type": "array",
                        "items": {
                            "type": "array",
                            "items": [
                                {
                                    "type": "number"
                                },
                                {
                                    "type": "number"
                                }
                            ]
                        }
                    }
                }
            },
        }
    }
}
```

**Actual result**
```
System.InvalidOperationException: Error while rendering Liquid template TypeScript/Class:
Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.

Runtime: Net60
   at NJsonSchema.CodeGeneration.TypeScript.TypeScriptTypeResolver.GetNullableItemType(JsonSchema schema, String itemType)
   at NJsonSchema.CodeGeneration.TypeScript.TypeScriptTypeResolver.<>c__DisplayClass16_0.<ResolveArrayOrTuple>b__1(JsonSchema s)
   at System.Linq.Enumerable.SelectIListIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at NJsonSchema.CodeGeneration.TypeScript.TypeScriptTypeResolver.ResolveArrayOrTuple(JsonSchema schema, String typeNameHint, Boolean addInterfacePrefix)
   at NJsonSchema.CodeGeneration.TypeScript.TypeScriptTypeResolver.Resolve(JsonSchema schema, String typeNameHint, Boolean addInterfacePrefix)
   at NJsonSchema.CodeGeneration.TypeScript.TypeScriptTypeResolver.Resolve(JsonSchema schema, Boolean isNullable, String typeNameHint)
   at NJsonSchema.CodeGeneration.TypeScript.TypeScriptTypeResolver.ResolveArrayOrTuple(JsonSchema schema, String typeNameHint, Boolean addInterfacePrefix)
   at NJsonSchema.CodeGeneration.TypeScript.TypeScriptTypeResolver.Resolve(JsonSchema schema, String typeNameHint, Boolean addInterfacePrefix)
   at NJsonSchema.CodeGeneration.TypeScript.TypeScriptTypeResolver.Resolve(JsonSchema schema, Boolean isNullable, String typeNameHint)
   at NJsonSchema.CodeGeneration.TypeScript.Models.PropertyModel.get_Type()
   at Fluid.Accessors.PropertyInfoAccessor.Invoker`2.Invoke(Object target)
   at Fluid.Accessors.PropertyInfoAccessor.Get(Object obj, String name, TemplateContext ctx)
   at Fluid.Values.ObjectValueBase.GetValueAsync(String name, TemplateContext context)
   at Fluid.Ast.IdentifierSegment.ResolveAsync(FluidValue value, TemplateContext context)
   at Fluid.Ast.MemberExpression.EvaluateAsync(TemplateContext context)
   at Fluid.Ast.OutputStatement.WriteToAsync(TextWriter writer, TextEncoder encoder, TemplateContext context)
   at Fluid.Ast.ForStatement.WriteToAsync(TextWriter writer, TextEncoder encoder, TemplateContext context)
   at Fluid.Parser.FluidTemplate.Awaited(ValueTask`1 task, TextWriter writer, TextEncoder encoder, TemplateContext context, IReadOnlyList`1 statements, Int32 startIndex)
   at Fluid.FluidTemplateExtensions.RenderAsync(IFluidTemplate template, TemplateContext context, TextEncoder encoder)
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.LiquidTemplate.Render()
   --- End of inner exception stack trace ---
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.LiquidTemplate.Render()
   at NJsonSchema.CodeGeneration.CodeArtifact..ctor(String typeName, String baseTypeName, CodeArtifactType type, CodeArtifactLanguage language, CodeArtifactCategory category, ITemplate template)
   at NJsonSchema.CodeGeneration.TypeScript.TypeScriptGenerator.GenerateType(JsonSchema schema, String typeNameHint)
   at NJsonSchema.CodeGeneration.GeneratorBase.GenerateTypes()
   at NJsonSchema.CodeGeneration.TypeScript.TypeScriptGenerator.GenerateTypes(TypeScriptExtensionCode extensionCode)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at NJsonSchema.CodeGeneration.CodeArtifactExtensions.OrderByBaseDependency(IEnumerable`1 results)
   at NSwag.CodeGeneration.TypeScript.Models.TypeScriptFileTemplateModel..ctor(IEnumerable`1 clientTypes, IEnumerable`1 dtoTypes, OpenApiDocument document, TypeScriptExtensionCode extensionCode, TypeScriptClientGeneratorSettings settings, TypeScriptTypeResolver resolver) in /_/src/NSwag.CodeGeneration.TypeScript/Models/TypeScriptFileTemplateModel.cs:line 49
   at NSwag.CodeGeneration.TypeScript.TypeScriptClientGenerator.GenerateFile(IEnumerable`1 clientTypes, IEnumerable`1 dtoTypes, ClientGeneratorOutputType outputType) in /_/src/NSwag.CodeGeneration.TypeScript/TypeScriptClientGenerator.cs:line 96
   at NSwag.CodeGeneration.ClientGeneratorBase`3.GenerateFile(ClientGeneratorOutputType outputType) in /_/src/NSwag.CodeGeneration/ClientGeneratorBase.cs:line 89
   at NSwag.CodeGeneration.ClientGeneratorBase`3.GenerateFile() in /_/src/NSwag.CodeGeneration/ClientGeneratorBase.cs:line 65
   at NSwag.Commands.CodeGeneration.SwaggerToTypeScriptClientCommand.RunAsync() in /_/src/NSwag.Commands/Commands/CodeGeneration/OpenApiToTypeScriptClientCommand.cs:line 423
   at NSwag.Commands.CodeGeneration.SwaggerToTypeScriptClientCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in /_/src/NSwag.Commands/Commands/CodeGeneration/OpenApiToTypeScriptClientCommand.cs:line 406
   at NSwag.Commands.NSwagDocument.<>c__DisplayClass4_1.<<ExecuteAsync>b__0>d.MoveNext() in /_/src/NSwag.Commands/NSwagDocument.cs:line 95
--- End of stack trace from previous location ---
   at NSwag.Commands.NSwagDocument.ExecuteAsync() in /_/src/NSwag.Commands/NSwagDocument.cs:line 100
   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in /_/src/NSwag.Commands/Commands/Document/ExecuteDocumentCommand.cs:line 85
   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in /_/src/NSwag.Commands/Commands/Document/ExecuteDocumentCommand.cs:line 32
   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.ProcessAsync(String[] args) in /_/src/NSwag.Commands/NSwagCommandProcessor.cs:line 61


```

**Expected result**
Schema validation error, preferably including the line number and the reason (i.e. wrong type of `items`, expected `object`)

**Comment by janseris** [comment]
Try validate via https://validator.swagger.io/. That helped me diagnose OpenAPI definition validations.
