### ISSUE TITLE
Question: Any way to ignore a controller in a library?

### ISSUE THREAD

**Issue by groogiam** [RicoSuter/NSwag#4329]
Is there any way to ignore a controller in a library?

I'm running into this issue where a controller referenced by a third party I do not control and cannot annotate to ignore breaks the API explorer. I was hoping there is a mechanism to configure this in code similar to what is available in the Swashbuckle library https://stackoverflow.com/questions/39601890/not-supported-by-swagger-2-0-multiple-operations-with-path. Thanks.

```
An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: The method 'get' on path '/api/ReportDesignerControllerBase' is registered multiple times.
         at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.AddOperationDescriptionsToDocument(OpenApiDocument document, Type controllerType, List`1 operations, OpenApiDocumentGenerator swaggerGenerator, OpenApiSchemaResolver schemaResolver)
         at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateApiGroups(OpenApiDocument document, IGrouping`2[] apiGroups, OpenApiSchemaResolver schemaResolver)
         at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateAsync(ApiDescriptionGroupCollection apiDescriptionGroups)
         at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GenerateDocumentAsync(HttpContext context)
         at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GetDocumentAsync(HttpContext context)
         at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by groogiam** [comment]
The solution to this issue is to implement and operations processor to ignore operations on the controller. E.g.

```c#
    public class IncludeControllersInSwagger : IOperationProcessor
    {
        public bool Process(OperationProcessorContext context)
        {
           return ShouldIncludeController(context.ControllerType);
        }

        bool ShouldIncludeController(System.Type type)
        {
            return !(type.AssemblyQualifiedName == typeof(ControllerTypeToIgnore).AssemblyQualifiedName);
        }
    }
```

```c#
builder.Services.AddSwaggerDocument(c =>
{
    c.IgnoreObsoleteProperties = true;
    c.OperationProcessors.Add(new IncludeControllersInSwagger());
});
```
