### ISSUE TITLE
NSwag command line code gen. kills build 14.0.0-preview010

### ISSUE THREAD

**Issue by janosjanka** [RicoSuter/NSwag#4622]
Hello,

I'm trying to migrate from .NET 7 to .NET 8 but the latest command line code gen. tool seems enough instable. I have managed to setup the APIs to generate open API schema and Swagger UI, but if I want to generate CSharp or TS client from the spec., the build is stuck forever (VS progress bar) with this error output:

```
System.InvalidOperationException: Process dotnet timed out.
28>   at NSwag.Commands.Generation.AspNetCore.Exe.RunAsync(String executable, IReadOnlyList`1 args, IConsoleHost console, Nullable`1 timeout) in /_/src/NSwag.Commands/Commands/Generation/AspNetCore/Exe.cs:line 66
28>   at NSwag.Commands.Generation.AspNetCore.ProjectMetadata.GetProjectMetadata(String file, String buildExtensionsDir, String framework, String configuration, String runtime, Boolean noBuild, String outputPath, IConsoleHost console) in /_/src/NSwag.Commands/Commands/Generation/AspNetCore/ProjectMetadata.cs:line 149
28>   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToOpenApiCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in /_/src/NSwag.Commands/Commands/Generation/AspNetCore/AspNetCoreToOpenApiCommand.cs:line 70
28>   at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in /_/src/NSwag.Commands/NSwagDocumentBase.cs:line 270
28>   at NSwag.Commands.NSwagDocument.ExecuteAsync() in /_/src/NSwag.Commands/NSwagDocument.cs:line 67
28>   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in /_/src/NSwag.Commands/Commands/Document/ExecuteDocumentCommand.cs:line 76
28>   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in /_/src/NSwag.Commands/Commands/Document/ExecuteDocumentCommand.cs:line 33
28>   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
28>   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
```

It does not matter whether I use NSwag.MSBuild integration:

```
<Target Name="NSwag" AfterTargets="PostBuildEvent" Condition="'$(IsAspNetCoreApp)' == 'True'">
  <Exec WorkingDirectory="$(ProjectDir)" Command="$(NSwagExe_Net80) run nswag.json" />
</Target>
```
... or download and call the command line tool passing the json directly. VS progress bar is stuck and it gets into some infinite loop, rebuilding everything over and over. 

I do not know whether it is related to the redirected output paths:

```
  <PropertyGroup>
    <RepositoryRoot>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))</RepositoryRoot>
    <BinaryPath>$(RepositoryRoot)artifacts\</BinaryPath>
    <DeployPath>$(RepositoryRoot)artifacts\Deploy\</DeployPath>
    <OutputPath>$(BinaryPath)$(Configuration)\$(MSBuildProjectName)\</OutputPath>
    <BaseIntermediateOutputPath>$(BinaryPath)Obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    <PackageSourcePath>$(RepositoryRoot)pkg\</PackageSourcePath>
  </PropertyGroup>
```

But it is totally broken and freezes VS Build as well. I cannot even cancel the build. 
Of course, without this code gen step, API start and work, including Swagger UI.

**Comment by janosjanka** [comment]
I copied the Project.NSwag.target to \artifacts\Obj\Project folder. Now it starts (at least), but it tries to load the project even if I specified assembly path and no build for nswag.json:

```\.tools\NSwag\Net80\dotnet-nswag.exe run nswag.json /variables:Environment=Development,OutputPath=\artifacts\Debug\DemoApi\net8.0\,NSwagClientName=security```

nswag.json

```JSON
{
  "runtime": "Net80",
  "documentGenerator": {
    "aspNetCoreToOpenApi": {
      "assemblyPaths": [
        "$(OutputPath)/DemoApi.dll"
      ],
      "msBuildProjectExtensionsPath": null,
      "noBuild": true,
      "project": null
    }
  },
```
But the command line tool is trying to load the project from:

```System.InvalidOperationException: Project outputs could not be located in '**C:\...\DemoApi\artifacts\TransPerfect.ReefReview.SecurityApi\net8.0\**'. Ensure that the project has been built.```

**Comment by lahma** [comment]
Artifacts output layout was merged in https://github.com/RicoSuter/NSwag/pull/4589  but hasn't yet been released.

**Comment by janosjanka** [comment]
Oh. Thank you. I'm trying this new simplified .NET 8 MSBuild config.
So far, we had to setup all the MSBuild variables for output redirection.

**Comment by PeterStegnar** [comment]
I am having the same problem. Running:
`<Exec WorkingDirectory="$(ProjectDir)" EnvironmentVariables="ASPNETCORE_ENVIRONMENT=Development" Command="$(NSwagExe_Net80) run Clients\\SomeApi.nswag.json /variables:Configuration=$(Configuration),output=SomeApiTestClient.Generated.cs" />`

Starts spawning many .NET Host processes and stalls the whole machine. This happens with nswag .net8.0.

**Comment by fabricioferreira** [comment]
> I am having the same problem. Running: `<Exec WorkingDirectory="$(ProjectDir)" EnvironmentVariables="ASPNETCORE_ENVIRONMENT=Development" Command="$(NSwagExe_Net80) run Clients\\SomeApi.nswag.json /variables:Configuration=$(Configuration),output=SomeApiTestClient.Generated.cs" />`
> 
> Starts spawning many .NET Host processes and stalls the whole machine. This happens with nswag .net8.0.

@PeterStegnar I'm having the same issue here. Have you found a solution for that?
I had to open an admin console and kill all dotnet instances to get the system back to normal.

**Comment by PeterStegnar** [comment]
Hi,

Unfortunately not, but I will have to address it sooner or later. If you
discover something, please let me know. :)

Best,

Peter
