### ISSUE TITLE
Using OpenApiReference in csproj file is broken after upgrade to v14

### ISSUE THREAD

**Issue by jonnybee** [RicoSuter/NSwag#4640]
I have tested with NSwag.ApiDescription.Client v14.0.0.preview10 and v14.0.0.preview12

In my csproj file:
```
    <OpenApiReference Include="OpenAPIs\authorization.json" CodeGenerator="NSwagCSharp" Namespace="AcceptanceTests.Authorization.Clients" ClassName="{controller}Client">
        <SourceUri>https://localhost:44317/openapi</SourceUri>
        <Options>/GenerateClientInterfaces:true /GenerateExceptionClasses:false /AdditionalNamespaceUsages:AcceptanceTests.ApplicationBackend.Clients</Options>
    </OpenApiReference>
```

and after upgrade to v14.0.0.preview12 and .NET8 i get this build error: 

NSwag command line tool for .NET Core Net80, toolchain v14.0.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))
Visit http://NSwag.org for more information.
NSwag bin directory: C:\Users\jonbek\.nuget\packages\nswag.msbuild\14.0.0-preview012\tools\Net80
NConsole.UnusedArgumentException: Unrecognised arguments are present: []
   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.ProcessAsync(String[] args) in /_/src/NSwag.Commands/NSwagCommandProcessor.cs:line 62

When using .NET7 and NSwag.ApiDescription.Client v13.x.x this compiles just fine.

**Comment by jonnybee** [comment]
I was able to find a workaround - after removing **/GenerateExceptionClasses:false** from Options the command ran fine. 
But the error message is not very helpful and it worked just fine with v13.x.x and older versions.

**Comment by fretje** [comment]
Apparently you can now use the `<NSwagGenerateExceptionClasses>` msbuild property (and any other of the nswag options like that).
When you do that in stead of adding it to the `<Options>` property, the command runs fine.

Apparently, if a property has already being defined using the "msbuild property syntax", you can not change it anymore using the "/options syntax" (as it results in that "Unrecognised arguments are present" error), but you can still override it using the "msbuild property syntax".

For example:

```csproj
<OpenApiReference Include="swagger.json">
    <Namespace>namespace</Namespace>
    <ClassName>classname</ClassName>
    <NSwagGenerateExceptionClasses>false</NSwagGenerateExceptionClasses>
</OpenApiReference>
```

I found this out by trial and error, and browsing through the source code... not sure if this is actually documented somewhere.

**Comment by rjpowers10** [comment]
Thanks @fretje, converting from `<Options>` to `<NSwag...>` fixed my issues. I tried looking for documentation on this before finally stumbling upon your comment and didn't find anything.

**Comment by iSatishYadav** [comment]
> Apparently you can now use the `<NSwagGenerateExceptionClasses>` msbuild property (and any other of the nswag options like that). When you do that in stead of adding it to the `<Options>` property, the command runs fine.
> 
> Apparently, if a property has already been defined using the "msbuild property syntax", you can not change it anymore using the "/options syntax" (as it results in that "Unrecognised arguments are present" error), but you can still override it using the "msbuild property syntax".
> 
> For example:
> 
> ```
> <OpenApiReference Include="swagger.json">
>     <Namespace>namespace</Namespace>
>     <ClassName>classname</ClassName>
>     <NSwagGenerateExceptionClasses>false</NSwagGenerateExceptionClasses>
> </OpenApiReference>
> ```
> 
> I found this out by trial and error, and browsing through the source code... not sure if this is actually documented somewhere.

You sir, are a life-saver.
