### ISSUE TITLE
Nswag 14 exception

### ISSUE THREAD

**Issue by MoeHamdan** [RicoSuter/NSwag#4676]
Hello
I am getting the below error with NswagStudio 14

`System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'NSwag.CodeGeneration, Version=14.0.0.0, Culture=neutral, PublicKeyToken=c2d88086e098d109'. The system cannot find the file specified.
Could not load file or assembly 'NSwag.CodeGeneration.CSharp, Version=14.0.0.0, Culture=neutral, PublicKeyToken=c2d88086e098d109'. The system cannot find the file specified.
Could not load file or assembly 'NSwag.CodeGeneration, Version=14.0.0.0, Culture=neutral, PublicKeyToken=c2d88086e098d109'. The system cannot find the file specified.
Could not load file or assembly 'NSwag.CodeGeneration.CSharp, Version=14.0.0.0, Culture=neutral, PublicKeyToken=c2d88086e098d109'. The system cannot find the file specified.
Could not load file or assembly 'NSwag.CodeGeneration.TypeScript, Version=14.0.0.0, Culture=neutral, PublicKeyToken=c2d88086e098d109'. The system cannot find the file specified.
Could not load file or assembly 'NJsonSchema.Annotations, Version=11.0.0.0, Culture=neutral, PublicKeyToken=c2f9c3bdfae56102'. The system cannot find the file specified.
Could not load file or assembly 'NJsonSchema.Annotations, Version=11.0.0.0, Culture=neutral, PublicKeyToken=c2f9c3bdfae56102'. The system cannot find the file specified.
Could not load file or assembly 'NJsonSchema.Annotations, Version=11.0.0.0, Culture=neutral, PublicKeyToken=c2f9c3bdfae56102'. The system cannot find the file specified.
Could not load file or assembly 'NJsonSchema.Annotations, Version=11.0.0.0, Culture=neutral, PublicKeyToken=c2f9c3bdfae56102'. The system cannot find the file specified.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.<>c.<AddAutoMapperClasses>b__12_5(Assembly a)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.AddAutoMapperClasses(IServiceCollection services, Action`2 configAction, IEnumerable`1 assembliesToScan, ServiceLifetime serviceLifetime)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.AddAutoMapper(IServiceCollection services, Action`1 configAction, Assembly[] assemblies)
   at CampAustralia.WebApi.Setup.WebApplicationBuilderExtensions.AddCampServices(IServiceCollection services, String apiName, IHostEnvironment environment, IConfiguration configuration, AuthSettings authSettings, Action`1 automapperConfigurator, Action`1 mvcJsonConfigurator, Action`1 mvcConfigurator, Action`1 healthCheckConfigurator)
   at CampAustralia.WebApi.Setup.WebApplicationBuilderExtensions.WithCampSecureServices(WebApplicationBuilder hostBuilder, String apiName, Action`1 automapperConfigurator, Action`1 mvcJsonConfigurator, Action`1 mvcConfigurator, Action`1 healthCheckConfigurator)
   at Program.<Main>$(String[] args) in E:\Camp Australia\Repos\CampAustralia.EducatorTimeLogApi\src\EducatorTimeLogApi\Program.cs:line 15
   at Program.<Main>(String[] args)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Hosting.HostFactoryResolver.HostingListener.CreateHost() in /_/src/NSwag.Commands/HostFactoryResolver.cs:line 271
   at Microsoft.Extensions.Hosting.HostFactoryResolver.<>c__DisplayClass8_0.<ResolveHostFactory>b__0(String[] args) in /_/src/NSwag.Commands/HostFactoryResolver.cs:line 75
   at NSwag.Commands.ServiceProviderResolver.GetServiceProviderWithHostFactoryResolver(Assembly assembly) in /_/src/NSwag.Commands/HostApplication.cs:line 158
   at NSwag.Commands.ServiceProviderResolver.GetServiceProvider(Assembly assembly) in /_/src/NSwag.Commands/HostApplication.cs:line 70
   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToOpenApiGeneratorCommandEntryPoint.Process(String commandContent, String outputFile, String applicationName) in /_/src/NSwag.Commands/Commands/Generation/AspNetCore/AspNetCoreToOpenApiGeneratorCommandEntryPoint.cs:line 27
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
System.IO.FileNotFoundException: Could not load file or assembly 'NSwag.CodeGeneration, Version=14.0.0.0, Culture=neutral, PublicKeyToken=c2d88086e098d109'. The system cannot find the file specified.
File name: 'NSwag.CodeGeneration, Version=14.0.0.0, Culture=neutral, PublicKeyToken=c2d88086e098d109'
System.IO.FileNotFoundException: Could not load file or assembly 'NSwag.CodeGeneration.CSharp, Version=14.0.0.0, Culture=neutral, PublicKeyToken=c2d88086e098d109'. The system cannot find the file specified.
File name: 'NSwag.CodeGeneration.CSharp, Version=14.0.0.0, Culture=neutral, PublicKeyToken=c2d88086e098d109'
System.IO.FileNotFoundException: Could not load file or assembly 'NSwag.CodeGeneration, Version=14.0.0.0, Culture=neutral, PublicKeyToken=c2d88086e098d109'. The system cannot find the file specified.
File name: 'NSwag.CodeGeneration, Version=14.0.0.0, Culture=neutral, PublicKeyToken=c2d88086e098d109'
System.IO.FileNotFoundException: Could not load file or assembly 'NSwag.CodeGeneration.CSharp, Version=14.0.0.0, Culture=neutral, PublicKeyToken=c2d88086e098d109'. The system cannot find the file specified.
File name: 'NSwag.CodeGeneration.CSharp, Version=14.0.0.0, Culture=neutral, PublicKeyToken=c2d88086e098d109'
System.IO.FileNotFoundException: Could not load file or assembly 'NSwag.CodeGeneration.TypeScript, Version=14.0.0.0, Culture=neutral, PublicKeyToken=c2d88086e098d109'. The system cannot find the file specified.
File name: 'NSwag.CodeGeneration.TypeScript, Version=14.0.0.0, Culture=neutral, PublicKeyToken=c2d88086e098d109'
System.IO.FileNotFoundException: Could not load file or assembly 'NJsonSchema.Annotations, Version=11.0.0.0, Culture=neutral, PublicKeyToken=c2f9c3bdfae56102'. The system cannot find the file specified.
File name: 'NJsonSchema.Annotations, Version=11.0.0.0, Culture=neutral, PublicKeyToken=c2f9c3bdfae56102'
System.IO.FileNotFoundException: Could not load file or assembly 'NJsonSchema.Annotations, Version=11.0.0.0, Culture=neutral, PublicKeyToken=c2f9c3bdfae56102'. The system cannot find the file specified.
File name: 'NJsonSchema.Annotations, Version=11.0.0.0, Culture=neutral, PublicKeyToken=c2f9c3bdfae56102'
System.IO.FileNotFoundException: Could not load file or assembly 'NJsonSchema.Annotations, Version=11.0.0.0, Culture=neutral, PublicKeyToken=c2f9c3bdfae56102'. The system cannot find the file specified.
File name: 'NJsonSchema.Annotations, Version=11.0.0.0, Culture=neutral, PublicKeyToken=c2f9c3bdfae56102'
System.IO.FileNotFoundException: Could not load file or assembly 'NJsonSchema.Annotations, Version=11.0.0.0, Culture=neutral, PublicKeyToken=c2f9c3bdfae56102'. The system cannot find the file specified.
File name: 'NJsonSchema.Annotations, Version=11.0.0.0, Culture=neutral, PublicKeyToken=c2f9c3bdfae56102'
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at NSwag.AspNetCore.Launcher.Program.Main(String[] args) in /_/src/NSwag.AspNetCore.Launcher/Program.cs:line 132`

**Comment by destacey** [comment]
I had a similar exception and was able to solve it by installing each of the assemblies

- NSwag.CodeGeneration
- NSwag.CodeGeneration.CSharp
- NSwag.CodeGeneration.TypeScript

**Comment by krzyhan** [comment]
Did you try to uninstall the studio and install again? (the latest 14.0.1 version)?

This error occurs while opening the studio or along with some action?

**Comment by MoeHamdan** [comment]
@krzyhan this happens when I am generating code, and yes I have latest version.

**Comment by VerdantForge** [comment]
Any progress on this issue? I'm currently running into the same problem

**Comment by MoeHamdan** [comment]
This problem happens when you are reflecting/loading assemblies. Check which ones, it my case it was when AutoMapper trying to load all assemblies without any filter. You can skip it by checking environment variable and check if it is NSwag.

**Comment by VerdantForge** [comment]
What solved it for me in the end was to install the missing packages

```
dotnet add package NSwag.CodeGeneration
dotnet add package NSwag.CodeGeneration.CSharp
dotnet add package NSwag.CodeGeneration.TypeScript
```

Then ticking the `NoBuild` option in NswagStudio and in my `nswag.json` for MSBuild integration
