### ISSUE TITLE
UseSwaggerReDoc throws an exception using AspNet.Owin middleware

### ISSUE THREAD

**Issue by rds500rs** [RicoSuter/NSwag#4801]
UseSwaggerReDoc throws an exception using the NSwag.AspNet.Owin middleware in v14.0.3

The class 'NSwag.AspNet.Owin.Middlewares.SwaggerUiIndexMiddleware`1[[NSwag.Generation.WebApi.WebApiOpenApiDocumentGeneratorSettings, NSwag.Generation.WebApi, Version=14.0.3.0, Culture=neutral, PublicKeyToken=c2d88086e098d109]]' does not have a constructor taking 4 arguments.

	   at Microsoft.Owin.Builder.AppBuilder.ToConstructorMiddlewareFactory(Object middlewareObject, Object[] args, Delegate& middlewareDelegate)
	   at Microsoft.Owin.Builder.AppBuilder.ToMiddlewareFactory(Object middlewareObject, Object[] args)
	   at Microsoft.Owin.Builder.AppBuilder.Use(Object middleware, Object[] args)
	   at NSwag.AspNet.Owin.SwaggerExtensions.UseSwaggerReDoc(IAppBuilder app, IEnumerable`1 controllerTypes, Action`1 configure)

Looking back to the latest version of 13, the SwaggerUiIndexMiddleware constructor was changed from SwaggerUiSettingsBase<T> to SwaggerUiSettings<T>
But ReDocSettings only inherits from SwaggerUiSettingsBase<T>

**Comment by mehroz377** [comment]
I am facing the same issue. Is there any update on this?

**Comment by PVLopes** [comment]
same, using .NET Framework 4.7

**Comment by mehroz377** [comment]
Is there any update on this?

**Comment by nhatier** [comment]
Looks like this was fixed in 14.3.0.
