### ISSUE TITLE
nswag not generating typescript file my API project swagger UI working fine  

### ISSUE THREAD

**Issue by mchauhan-phyrem** [RicoSuter/NSwag#4860]
I am using **nswag version 14.0.7**

When running nswag command then it raise error like this 
D:\Projects\jira\complichain-aspnet-zero-front-end\nswag>"..\node_modules.bin\nswag" run
NSwag NPM CLI
NSwag command line tool for .NET Core Net80, toolchain v14.0.7.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))
Visit http://nswag.org/ for more information.
NSwag bin directory: D:\Projects\jira\complichain-aspnet-zero-front-end\node_modules\nswag\bin\binaries\Net80

Executing file 'D:\Projects\jira\complichain-aspnet-zero-front-end\nswag\service.config.nswag' with variables ''...
at NJsonSchema.CodeGeneration.TypeScript.TypeScriptTypeResolver.ResolveArrayOrTuple(NJsonSchema.JsonSchema, System.String, Boolean)
at NJsonSchema.CodeGeneration.TypeScript.TypeScriptTypeResolver.Resolve(NJsonSchema.JsonSchema, System.String, Boolean)
at NJsonSchema.CodeGeneration.TypeScript.TypeScriptTypeResolver.ResolveArrayOrTuple(NJsonSchema.JsonSchema, System.String, Boolean)
at NJsonSchema.CodeGeneration.TypeScript.TypeScriptTypeResolver.Resolve(NJsonSchema.JsonSchema, System.String, Boolean)
at NJsonSchema.CodeGeneration.TypeScript.TypeScriptTypeResolver.ResolveArrayOrTuple(NJsonSchema.JsonSchema, System.String, Boolean)
at NJsonSchema.CodeGeneration.TypeScript.TypeScriptTypeResolver.Resolve(NJsonSchema.JsonSchema, System.String, Boolean)
at NJsonSchema.CodeGeneration.TypeResolverBase.ResolveDictionaryValueType(NJsonSchema.JsonSchema, System.String)
at NJsonSchema.CodeGeneration.TypeScript.TypeScriptTypeResolver.Resolve(NJsonSchema.JsonSchema, System.String, Boolean)
at NJsonSchema.CodeGeneration.TypeScript.TypeScriptTypeResolver.ResolveArrayOrTuple(NJsonSchema.JsonSchema, System.String, Boolean)
at NJsonSchema.CodeGeneration.TypeScript.TypeScriptTypeResolver.Resolve(NJsonSchema.JsonSchema, System.String, Boolean)
at NJsonSchema.CodeGeneration.TypeScript.DataConversionGenerator.CreateModel(NJsonSchema.CodeGeneration.TypeScript.DataConversionParameters)
at NJsonSchema.CodeGeneration.TypeScript.DataConversionGenerator.RenderConvertToClassCode(NJsonSchema.CodeGeneration.TypeScript.DataConversionParameters)
at NSwag.CodeGeneration.TypeScript.TypeScriptClientGenerator.UpdateUseDtoClassAndDataConversionCodeProperties(System.Collections.Generic.IEnumerable1<NSwag.CodeGeneration.TypeScript.Models.TypeScriptOperationModel>) at NSwag.CodeGeneration.TypeScript.TypeScriptClientGenerator+<GenerateClientTypes>d__14.MoveNext() at System.Collections.Generic.List1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].AddRange(System.Collections.Generic.IEnumerable1<System.__Canon>) at NSwag.CodeGeneration.ClientGeneratorBase3[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GenerateAllClientTypes()
at NSwag.CodeGeneration.ClientGeneratorBase3[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GenerateFile(NSwag.CodeGeneration.ClientGeneratorOutputType) at NSwag.CodeGeneration.ClientGeneratorBase3[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GenerateFile()
at NSwag.Commands.CodeGeneration.OpenApiToTypeScriptClientCommand+d__162.MoveNext()
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[NSwag.Commands.CodeGeneration.OpenApiToTypeScriptClientCommand+d__162, NSwag.Commands, Version=14.0.7.0, Culture=neutral, PublicKeyToken=c2d88086e098d109]](d__162 ByRef)
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[NSwag.Commands.CodeGeneration.OpenApiToTypeScriptClientCommand+<RunAsync>d__162, NSwag.Commands, Version=14.0.7.0, Culture=neutral, PublicKeyToken=c2d88086e098d109]](<RunAsync>d__162 ByRef) at NSwag.Commands.CodeGeneration.OpenApiToTypeScriptClientCommand.RunAsync() at NSwag.Commands.CodeGeneration.OpenApiToTypeScriptClientCommand+<RunAsync>d__161.MoveNext() at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[NSwag.Commands.CodeGeneration.OpenApiToTypeScriptClientCommand+<RunAsync>d__161, NSwag.Commands, Version=14.0.7.0, Culture=neutral, PublicKeyToken=c2d88086e098d109]](<RunAsync>d__161 ByRef) at System.Runtime.CompilerServices.AsyncTaskMethodBuilder1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[NSwag.Commands.CodeGeneration.OpenApiToTypeScriptClientCommand+d__161, NSwag.Commands, Version=14.0.7.0, Culture=neutral, PublicKeyToken=c2d88086e098d109]](d__161 ByRef)
at NSwag.Commands.CodeGeneration.OpenApiToTypeScriptClientCommand.RunAsync(NConsole.CommandLineProcessor, NConsole.IConsoleHost)
at NSwag.Commands.NSwagDocument+<>c__DisplayClass4_1+<b__0>d.MoveNext()
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder1+AsyncStateMachineBox1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[NSwag.Commands.NSwagDocument+<>c__DisplayClass4_1+<b__0>d, NSwag.Commands, Version=14.0.7.0, Culture=neutral, PublicKeyToken=c2d88086e098d109]].ExecutionContextCallback(System.Object)
at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder1+AsyncStateMachineBox1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[NSwag.Commands.NSwagDocument+<>c__DisplayClass4_1+<b__0>d, NSwag.Commands, Version=14.0.7.0, Culture=neutral, PublicKeyToken=c2d88086e098d109]].MoveNext(System.Threading.Thread)
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder1+AsyncStateMachineBox1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[NSwag.Commands.NSwagDocument+<>c__DisplayClass4_1+<b__0>d, NSwag.Commands, Version=14.0.7.0, Culture=neutral, PublicKeyToken=c2d88086e098d109]].MoveNext()
at System.Runtime.CompilerServices.YieldAwaitable+YieldAwaiter+<>c.b__6_0(System.Action, System.Threading.Tasks.Task)
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
node:child_process:960
throw err;
^

Error: Command failed: dotnet "D:\Projects\jira\complichain-aspnet-zero-front-end\node_modules\nswag\bin/binaries/Net80/dotnet-nswag.dll" run
at checkExecSyncError (node:child_process:885:11)
at Object.execSync (node:child_process:957:15)
at D:\Projects\jira\complichain-aspnet-zero-front-end\node_modules\nswag\bin\nswag.js:65:27
at ChildProcess.exithandler (node:child_process:411:7)
at ChildProcess.emit (node:events:513:28)
at maybeClose (node:internal/child_process:1091:16)
at Socket. (node:internal/child_process:449:11)
at Socket.emit (node:events:513:28)
at Pipe. (node:net:322:12) {
status: 3221225725,
signal: null,
output: [ null, null, null ],
pid: 24808,
stdout: null,
stderr: null
}

Node.js v18.16.0

**Comment by kwabenaowusujnr** [comment]
How was this resolved
