### ISSUE TITLE
Unhandled exception generating code with openapi2csclient for PagerDuty OpenAPI v3

### ISSUE THREAD

**Issue by LazaroOnline** [RicoSuter/NSwag#4967]
Running the command to generate the C# client code from the open-API v3 json file from [the official PagerDuty url](https://raw.githubusercontent.com/PagerDuty/api-schema/main/reference/REST/openapiv3.json) results in an unhandled exception by the `nswag` command and thus doesn't get to generate any code.

```cmd
nswag openapi2csclient  /output:PagerDutyClient.cs  /namespace:MyApp /input:https://raw.githubusercontent.com/PagerDuty/api-schema/main/reference/REST/openapiv3.json
```
Error:
System.InvalidOperationException: Could not resolve the path '#/components/responses/OrchestrationPathServiceActiveResponse/content/application~1json/schema'.
   at NJsonSchema.JsonReferenceResolver.ResolveDocumentReference(Object rootObject, String jsonPath, Type targetType, IContractResolver contractResolver)
   at NJsonSchema.JsonReferenceResolver.ResolveReferenceAsync(Object rootObject, String jsonPath, Type targetType, IContractResolver contractResolver, Boolean append, CancellationToken cancellationToken)
   at NJsonSchema.JsonReferenceResolver.ResolveReferenceAsync(Object rootObject, String jsonPath, Type targetType, IContractResolver contractResolver, CancellationToken cancellationToken)
   at NJsonSchema.JsonSchemaReferenceUtilities.JsonReferenceUpdater.VisitJsonReferenceAsync(IJsonReference reference, String path, String typeNameHint, CancellationToken cancellationToken)
   at NJsonSchema.Visitors.AsyncJsonReferenceVisitorBase.VisitAsync(Object obj, String path, String typeNameHint, ISet`1 checkedObjects, Action`1 replacer, CancellationToken cancellationToken)
   at NJsonSchema.Visitors.AsyncJsonReferenceVisitorBase.VisitAsync(Object obj, String path, String typeNameHint, ISet`1 checkedObjects, Action`1 replacer, CancellationToken cancellationToken)
   at NJsonSchema.Visitors.AsyncJsonReferenceVisitorBase.VisitAsync(Object obj, String path, String typeNameHint, ISet`1 checkedObjects, Action`1 replacer, CancellationToken cancellationToken)
   at NJsonSchema.Visitors.AsyncJsonReferenceVisitorBase.VisitAsync(Object obj, String path, String typeNameHint, ISet`1 checkedObjects, Action`1 replacer, CancellationToken cancellationToken)
   at NJsonSchema.Visitors.AsyncJsonReferenceVisitorBase.VisitAsync(Object obj, String path, String typeNameHint, ISet`1 checkedObjects, Action`1 replacer, CancellationToken cancellationToken)
   at NJsonSchema.Visitors.AsyncJsonReferenceVisitorBase.VisitAsync(Object obj, String path, String typeNameHint, ISet`1 checkedObjects, Action`1 replacer, CancellationToken cancellationToken)
   at NJsonSchema.Visitors.AsyncJsonReferenceVisitorBase.VisitAsync(Object obj, String path, String typeNameHint, ISet`1 checkedObjects, Action`1 replacer, CancellationToken cancellationToken)
   at NJsonSchema.Visitors.AsyncJsonReferenceVisitorBase.VisitAsync(Object obj, CancellationToken cancellationToken)
   at NJsonSchema.JsonSchemaReferenceUtilities.JsonReferenceUpdater.VisitAsync(Object obj, CancellationToken cancellationToken)
   at NJsonSchema.JsonSchemaReferenceUtilities.UpdateSchemaReferencesAsync(Object rootObject, JsonReferenceResolver referenceResolver, IContractResolver contractResolver, CancellationToken cancellationToken)
   at NJsonSchema.Infrastructure.JsonSchemaSerialization.FromJsonWithLoaderAsync[T](Func`1 loader, SchemaType schemaType, String documentPath, Func`2 referenceResolverFactory, IContractResolver contractResolver, CancellationToken cancellationToken)
   at NSwag.OpenApiDocument.FromJsonAsync(String data, String documentPath, SchemaType expectedSchemaType, Func`2 referenceResolverFactory, CancellationToken cancellationToken) in /_/src/NSwag.Core/OpenApiDocument.cs:line 204
   at NSwag.OpenApiDocument.FromUrlAsync(String url, CancellationToken cancellationToken) in /_/src/NSwag.Core/OpenApiDocument.cs:line 236
   at NSwag.Commands.InputOutputCommandBase.GetInputSwaggerDocument() in /_/src/NSwag.Commands/Commands/InputOutputCommandBase.cs:line 47
   at NSwag.Commands.CodeGeneration.OpenApiToCSharpClientCommand.RunAsync() in /_/src/NSwag.Commands/Commands/CodeGeneration/OpenApiToCSharpClientCommand.cs:line 281
   at NSwag.Commands.CodeGeneration.OpenApiToCSharpClientCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in /_/src/NSwag.Commands/Commands/CodeGeneration/OpenApiToCSharpClientCommand.cs:line 270
   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.ProcessAsync(String[] args) in /_/src/NSwag.Commands/NSwagCommandProcessor.cs:line 65

Image screenshot:
<img width="1511" alt="image" src="https://github.com/user-attachments/assets/a577c580-4557-4c0c-b7c4-4dc1b0d3bec2">

Running windows 11, PowerShell 7.4.4,  
NSwag version: 14.1.0.0
NJsonSchema version: 11.0.2.0 (Newtonsoft.Json v13.0.0.0)

**Comment by LazaroOnline** [comment]
It seems Nswag is not happy with the "$ref" found in the json:

<img width="535" alt="image" src="https://github.com/user-attachments/assets/17f9aad9-46ab-43c2-9910-e69f4721d7c9">

that is referencing this other json property:

<img width="531" alt="image" src="https://github.com/user-attachments/assets/60d0bd82-200e-4f66-a317-6321719213f5">

Maybe there is some part of the OpenAPI v3 standar that Nswag is not yet supporting?

**Comment by LazaroOnline** [comment]
NSwag should be able to generate most of the code and skip through the schema validation errors whenever possible.
For example, the [openapi-generator](https://github.com/OpenAPITools/openapi-generator) tool is able to generate the code for this case:
```ps
npm install -g @openapitools/openapi-generator-cli
openapi-generator-cli generate -g csharp -o "./PagerDutyClient" --skip-validate-spec -i https://raw.githubusercontent.com/PagerDuty/api-schema/main/reference/REST/openapiv3.json
```

Even if the generated code has some errors, we can manually fix those latter after the tool should be able to generate 99% of the code.

**Comment by Box-Of-Hats** [comment]
@LazaroOnline Did you manage to resolve this issue? I'm having similar issues

**Comment by LazaroOnline** [comment]
@Box-Of-Hats no, I just tried a few different openapi code generators, none of them fully worked, but some others do generate almost all the code and then I manually fixed the errors from the project that looked the best.
