### ISSUE TITLE
Intermittent NSwag failure on .NET 8.0

### ISSUE THREAD

**Issue by WenningQiu** [RicoSuter/NSwag#4998]
My application is seeing intermittent build failure after being migrated to .NET 8.0 with NSwag.MSBuild upgraded to 14.1.0. So far we have been seeing the error only when the application is built by Azure DevOps pipeline and not when built locally.

```
C:\Program Files\dotnet\sdk\8.0.304\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(284,5): error MSB4018: at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [D:\csg-azure-agent\_work\1179\s\src\BillComposer.BL\BillComposer.BL.csproj] [D:\csg-azure-agent\_work\1179\s\src\BillComposer.API.NSwag\BillComposer.API.NSwag.csproj]
##[error]C:\Program Files\dotnet\sdk\8.0.304\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(284,5): Error MSB4018: at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [D:\csg-azure-agent\_work\1179\s\src\BillComposer.BL\BillComposer.BL.csproj]
C:\Program Files\dotnet\sdk\8.0.304\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(284,5): error MSB4018: at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [D:\csg-azure-agent\_work\1179\s\src\BillComposer.BL\BillComposer.BL.csproj] [D:\csg-azure-agent\_work\1179\s\src\BillComposer.API.NSwag\BillComposer.API.NSwag.csproj]
  System.InvalidOperationException: Unable to retrieve project metadata. Ensure it's an MSBuild-based .NET Core project.If you're using custom BaseIntermediateOutputPath or MSBuildProjectExtensionsPath values, Use the --msbuildprojectextensionspath option.
     at NSwag.Commands.Generation.AspNetCore.ProjectMetadata.ReadUsingMsBuildTargets(List`1 args, String file, String buildExtensionsDir, IConsoleHost console) in /_/src/NSwag.Commands/Commands/Generation/AspNetCore/ProjectMetadata.cs:line 160
     at NSwag.Commands.Generation.AspNetCore.ProjectMetadata.GetProjectMetadata(String file, String buildExtensionsDir, String framework, String configuration, String runtime, Boolean noBuild, String outputPath, IConsoleHost console) in /_/src/NSwag.Commands/Commands/Generation/AspNetCore/ProjectMetadata.cs:line 92
     at NSwag.Commands.Generation.AspNetCore.AspNetCoreToOpenApiCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in /_/src/NSwag.Commands/Commands/Generation/AspNetCore/AspNetCoreToOpenApiCommand.cs:line 70
     at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in /_/src/NSwag.Commands/NSwagDocumentBase.cs:line 270
     at NSwag.Commands.NSwagDocument.ExecuteAsync() in /_/src/NSwag.Commands/NSwagDocument.cs:line 67
     at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in /_/src/NSwag.Commands/Commands/Document/ExecuteDocumentCommand.cs:line 76
     at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in /_/src/NSwag.Commands/Commands/Document/ExecuteDocumentCommand.cs:line 33
     at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
     at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
     at NSwag.Commands.NSwagCommandProcessor.ProcessAsync(String[] args) in /_/src/NSwag.Commands/NSwagCommandProcessor.cs:line 65
##[error]src\BillComposer.API.NSwag\BillComposer.API.NSwag.csproj(27,5): Error MSB3073: The command "dotnet "D:\Cache\.nuget\packages\nswag.msbuild\14.1.0\buildTransitive\../tools/Net80/dotnet-nswag.dll" run nswag.json /variables:Configuration=Release" exited with code -1.
D:\csg-azure-agent\_work\1179\s\src\BillComposer.API.NSwag\BillComposer.API.NSwag.csproj(27,5): error MSB3073: The command "dotnet "D:\Cache\.nuget\packages\nswag.msbuild\14.1.0\buildTransitive\../tools/Net80/dotnet-nswag.dll" run nswag.json /variables:Configuration=Release" exited with code -1.
Done Building Project "D:\csg-azure-agent\_work\1179\s\src\BillComposer.API.NSwag\BillComposer.API.NSwag.csproj" (default targets) -- FAILED.
Done Building Project "D:\csg-azure-agent\_work\1179\s\src\BillComposer.API.NSwag\BillComposer.API.NSwag.csproj.metaproj" (default targets) -- FAILED.
```
Below are the .csproj snippet that is relavant to NSwag:
```
  <ItemGroup>
    <PackageReference Include="NSwag.MSBuild" Version="14.1.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <Target Name="NSwag" AfterTargets="PostBuildEvent">
    <Exec Command="$(NSwagExe_Net80) run nswag.json /variables:Configuration=$(Configuration)" />
  </Target>
```
Below is the content of nswag.json file:
```
{
  "runtime": "Net80",
  "defaultVariables": null,
  "documentGenerator": {
    "aspNetCoreToOpenApi": {
      "project": "../BillComposer.API/BillComposer.API.csproj",
      "msBuildProjectExtensionsPath": null,
      "configuration": null,
      "runtime": null,
      "targetFramework": null,
      "noBuild": false,
      "msBuildOutputPath": null,
      "verbose": true,
      "workingDirectory": null,
      "requireParametersWithoutDefault": false,
      "apiGroupNames": null,
      "defaultPropertyNameHandling": "Default",
      "defaultReferenceTypeNullHandling": "Null",
      "defaultDictionaryValueReferenceTypeNullHandling": "NotNull",
      "defaultResponseReferenceTypeNullHandling": "NotNull",
      "generateOriginalParameterNames": true,
      "defaultEnumHandling": "Integer",
      "flattenInheritanceHierarchy": false,
      "generateKnownTypes": true,
      "generateEnumMappingDescription": false,
      "generateXmlObjects": false,
      "generateAbstractProperties": false,
      "generateAbstractSchemas": true,
      "ignoreObsoleteProperties": false,
      "allowReferencesWithProperties": false,
      "useXmlDocumentation": true,
      "resolveExternalXmlDocumentation": true,
      "excludedTypeNames": [],
      "serviceHost": null,
      "serviceBasePath": null,
      "serviceSchemes": [],
      "infoTitle": "My Title",
      "infoDescription": null,
      "infoVersion": "1.0.0",
      "documentTemplate": null,
      "documentProcessorTypes": [],
      "operationProcessorTypes": [],
      "typeNameGeneratorType": null,
      "schemaNameGeneratorType": null,
      "contractResolverType": null,
      "serializerSettingsType": null,
      "useDocumentProvider": true,
      "documentName": "v1",
      "aspNetCoreEnvironment": null,
      "createWebHostBuilderMethod": null,
      "startupType": null,
      "allowNullableBodyParameters": true,
      "useHttpAttributeNameAsOperationId": false,
      "output": null,
      "outputType": "Swagger2",
      "newLineBehavior": "Auto",
      "assemblyPaths": [],
      "assemblyConfig": null,
      "referencePaths": [],
      "useNuGetCache": false
    }
  },
  "codeGenerators": {
    "openApiToTypeScriptClient": {
      "className": "{controller}Client",
      "moduleName": "",
      "namespace": "",
      "typeScriptVersion": 4.3,
      "template": "Fetch",
      "promiseType": "Promise",
      "httpClass": "HttpClient",
      "withCredentials": false,
      "useSingletonProvider": false,
      "injectionTokenType": "OpaqueToken",
      "rxJsVersion": 6.0,
      "dateTimeType": "Date",
      "nullValue": "Undefined",
      "generateClientClasses": true,
      "generateClientInterfaces": false,
      "generateOptionalParameters": false,
      "exportTypes": true,
      "wrapDtoExceptions": false,
      "exceptionClass": "ApiException",
      "clientBaseClass": null,
      "wrapResponses": false,
      "wrapResponseMethods": [],
      "generateResponseClasses": true,
      "responseClass": "SwaggerResponse",
      "protectedMethods": [],
      "configurationClass": null,
      "useTransformOptionsMethod": false,
      "useTransformResultMethod": false,
      "generateDtoTypes": true,
      "operationGenerationMode": "MultipleClientsFromOperationId",
      "markOptionalProperties": true,
      "generateCloneMethod": false,
      "typeStyle": "Class",
      "enumStyle": "Enum",
      "useLeafType": false,
      "classTypes": [],
      "extendedClasses": [],
      "extensionCode": null,
      "generateDefaultValues": true,
      "excludedTypeNames": [],
      "excludedParameterNames": [],
      "handleReferences": false,
      "generateConstructorInterface": true,
      "convertConstructorInterfaceData": false,
      "importRequiredTypes": true,
      "useGetBaseUrlMethod": false,
      "baseUrlTokenName": "API_BASE_URL",
      "queryNullValue": "",
      "useAbortSignal": false,
      "inlineNamedDictionaries": false,
      "inlineNamedAny": false,
      "includeHttpContext": false,
      "templateDirectory": null,
      "typeNameGeneratorType": null,
      "propertyNameGeneratorType": null,
      "enumNameGeneratorType": null,
      "serviceHost": null,
      "serviceSchemes": null,
      "output": "../BillComposer.UI/src/api/client.ts",
      "newLineBehavior": "Auto"
    }
  }
}
```

**Comment by WenningQiu** [comment]
Update, I see the error on my local machine too, although much less frequently than on Azure DevOps pipeline.

1. Why does NSwag drives Debug build even with "Configuration=Release"?
2. Does NSwag kicks off parallel build tasks that may result in file contention?

```
NSwag:
  dotnet "C:\Users\qiuw01\.nuget\packages\nswag.msbuild\14.1.0\buildTransitive\../tools/Net80/dotnet-nswag.dll" run nswag.json /variables:Configuration=Release
  NSwag command line tool for .NET Core Net80, toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))
  Visit http://NSwag.org for more information.
  NSwag bin directory: C:\Users\qiuw01\.nuget\packages\nswag.msbuild\14.1.0\tools\Net80

  Executing file 'nswag.json' with variables 'Configuration=Release'...
CSC : error CS2012: Cannot open 'C:\work\git\os_system\BillComposer\src\BillComposer.API\obj\Debug\net8.0-windows\BillComposer.API.dll' for writing -- 'The process cannot access the file 'C:\work\git\os_system\
BillComposer\src\BillComposer.API\obj\Debug\net8.0-windows\BillComposer.API.dll' because it is being used by another process.' [C:\work\git\os_system\BillComposer\src\BillComposer.API\BillComposer.API.csproj] [
C:\work\git\os_system\BillComposer\src\BillComposer.API.NSwag\BillComposer.API.NSwag.csproj]
  System.InvalidOperationException: Unable to retrieve project metadata. Ensure it's an MSBuild-based .NET Core project.If you're using custom BaseIntermediateOutputPath or MSBuildProjectExtensionsPath values,
  Use the --msbuildprojectextensionspath option.
     at NSwag.Commands.Generation.AspNetCore.ProjectMetadata.ReadUsingMsBuildTargets(List`1 args, String file, String buildExtensionsDir, IConsoleHost console) in /_/src/NSwag.Commands/Commands/Generation/AspNe
  tCore/ProjectMetadata.cs:line 160
     at NSwag.Commands.Generation.AspNetCore.ProjectMetadata.GetProjectMetadata(String file, String buildExtensionsDir, String framework, String configuration, String runtime, Boolean noBuild, String outputPath
  , IConsoleHost console) in /_/src/NSwag.Commands/Commands/Generation/AspNetCore/ProjectMetadata.cs:line 92
     at NSwag.Commands.Generation.AspNetCore.AspNetCoreToOpenApiCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in /_/src/NSwag.Commands/Commands/Generation/AspNetCore/AspNetCoreToOpenApiCom
  mand.cs:line 70
     at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in /_/src/NSwag.Commands/NSwagDocumentBase.cs:line 270
     at NSwag.Commands.NSwagDocument.ExecuteAsync() in /_/src/NSwag.Commands/NSwagDocument.cs:line 67
     at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in /_/src/NSwag.Commands/Commands/Document/ExecuteDocumentCommand.cs:line 76
     at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in /_/src/NSwag.Commands/Commands/Document/ExecuteDocumentCommand.cs:line 33
     at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
     at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
     at NSwag.Commands.NSwagCommandProcessor.ProcessAsync(String[] args) in /_/src/NSwag.Commands/NSwagCommandProcessor.cs:line 65
C:\work\git\os_system\BillComposer\src\BillComposer.API.NSwag\BillComposer.API.NSwag.csproj(69,5): error MSB3073: The command "dotnet "C:\Users\qiuw01\.nuget\packages\nswag.msbuild\14.1.0\buildTransitive\../too
ls/Net80/dotnet-nswag.dll" run nswag.json /variables:Configuration=Release" exited with code -1.
```

**Comment by vvdb-architecture** [comment]
The error happens intermittently. That is usually because of parallelism.
It's a file in a project called `BillComposer.BL.csproj`, and your NSwag invocation is from `BillComposer.API.NSwag.csproj`. If no direct or indirect dependencies exist between these two projects, the builds may occur in parallel, triggering the problem.

If you can't add the former as a dependency on the latter, perhaps you can try to set the build order explicitly in Visual Studio... just a thought.

**Comment by SerenaPrososki** [comment]
I added the following project dependency as suggested. I am still getting the error above that Wenning mentions.

EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "BillComposer.API.NSwag", "src\BillComposer.API.NSwag\BillComposer.API.NSwag.csproj", "{30B86CD0-25C4-4F7E-8B1F-4BAD9498DF1D}"
	ProjectSection(ProjectDependencies) = postProject
		{9DB34C69-3CB7-4FB0-B2BA-DB3F65217051} = {9DB34C69-3CB7-4FB0-B2BA-DB3F65217051}
		{ACE9289D-70F8-4615-B947-D0D6ED0857ED} = {ACE9289D-70F8-4615-B947-D0D6ED0857ED}
	EndProjectSection
EndProject

**Comment by MichaelSpencerJr** [comment]
(I'm a coworker of Serena and Wenning) We're trying some other changes on our end, and will come back to this ticket if we are still stuck after. Thanks again, NSwag team.

**Comment by vvdb-architecture** [comment]
I don't use .sln mods, but the .csproj way

~~~csharp
<ProjectReference Include="...\BillComposer.BL.csproj">
  <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
</ProjectReference>
~~~

**Comment by SerenaPrososki** [comment]
We tried the suggestion above, we also tried explicitly setting the build order for all of the projects in the solution. We are still receiving the same error messages.
Build Order:
BillComposer.BL
BillComposer.Infra
BillComposer.API
BillComposer.API.NSwag
BillComposer.Test

**Comment by WenningQiu** [comment]
@vvdb-architecture Thanks for the suggestion, but we are still getting the same error with the change.

The issue probably is not related to the possible parallel building of projects based on the evidences we have at hand:

1. We did not specify "-maxCpuCount" on MsBuild command line, so there should only be one build process.
2. The file contention is on a JSON file in the Debug folder; however, we only performed Release build (/p:configuration=Release), so the building of other projects should only be touching files in the Release folder. 

The Debug folders apparently are created and accessed by NSwag build, so it comes to the two questions that I raised 3 weeks ago that have not been answered:

![image](https://github.com/user-attachments/assets/8a1456c6-27c5-4d64-8285-756ce3d3f95e)

**Comment by WenningQiu** [comment]
The file contention issue appears to have been introduced in NSwag.MSBuild version 14.0.0 with which I saw the file contention error even for net6.0-windows build. There is no issue with version 13.20.0.

**Comment by vvdb-architecture** [comment]
Too bad. Other suggestions: could it be because of a recursive build? Do you have `"nobuild": true` in your nswag file? I forgot it once and I saw either a *lot* of recursive calls or some file locks, but I forgot which file since it's some time ago.

In general, updating from 13.x to 14.x requires some work. There's a thread at the top of the issues list that contains more information, alas in a more scattered way.

**Comment by WenningQiu** [comment]
```nobuild``` is set to ```false```. Below is our nswag.json file.

```
{
  "runtime": "Net60",
  "defaultVariables": null,
  "documentGenerator": {
    "aspNetCoreToOpenApi": {
      "project": "../BillComposer.API/BillComposer.API.csproj",
      "msBuildProjectExtensionsPath": null,
      "configuration": null,
      "runtime": null,
      "targetFramework": null,
      "noBuild": false,
      "msBuildOutputPath": null,
      "verbose": true,
      "workingDirectory": null,
      "requireParametersWithoutDefault": false,
      "apiGroupNames": null,
      "defaultPropertyNameHandling": "Default",
      "defaultReferenceTypeNullHandling": "Null",
      "defaultDictionaryValueReferenceTypeNullHandling": "NotNull",
      "defaultResponseReferenceTypeNullHandling": "NotNull",
      "generateOriginalParameterNames": true,
      "defaultEnumHandling": "Integer",
      "flattenInheritanceHierarchy": false,
      "generateKnownTypes": true,
      "generateEnumMappingDescription": false,
      "generateXmlObjects": false,
      "generateAbstractProperties": false,
      "generateAbstractSchemas": true,
      "ignoreObsoleteProperties": false,
      "allowReferencesWithProperties": false,
      "useXmlDocumentation": true,
      "resolveExternalXmlDocumentation": true,
      "excludedTypeNames": [],
      "serviceHost": null,
      "serviceBasePath": null,
      "serviceSchemes": [],
      "infoTitle": "My Title",
      "infoDescription": null,
      "infoVersion": "1.0.0",
      "documentTemplate": null,
      "documentProcessorTypes": [],
      "operationProcessorTypes": [],
      "typeNameGeneratorType": null,
      "schemaNameGeneratorType": null,
      "contractResolverType": null,
      "serializerSettingsType": null,
      "useDocumentProvider": true,
      "documentName": "v1",
      "aspNetCoreEnvironment": null,
      "createWebHostBuilderMethod": null,
      "startupType": null,
      "allowNullableBodyParameters": true,
      "useHttpAttributeNameAsOperationId": false,
      "output": null,
      "outputType": "Swagger2",
      "newLineBehavior": "Auto",
      "assemblyPaths": [],
      "assemblyConfig": null,
      "referencePaths": [],
      "useNuGetCache": false
    }
  },
  "codeGenerators": {
    "openApiToTypeScriptClient": {
      "className": "{controller}Client",
      "moduleName": "",
      "namespace": "",
      "typeScriptVersion": 4.3,
      "template": "Fetch",
      "promiseType": "Promise",
      "httpClass": "HttpClient",
      "withCredentials": false,
      "useSingletonProvider": false,
      "injectionTokenType": "OpaqueToken",
      "rxJsVersion": 6.0,
      "dateTimeType": "Date",
      "nullValue": "Undefined",
      "generateClientClasses": true,
      "generateClientInterfaces": false,
      "generateOptionalParameters": false,
      "exportTypes": true,
      "wrapDtoExceptions": false,
      "exceptionClass": "ApiException",
      "clientBaseClass": null,
      "wrapResponses": false,
      "wrapResponseMethods": [],
      "generateResponseClasses": true,
      "responseClass": "SwaggerResponse",
      "protectedMethods": [],
      "configurationClass": null,
      "useTransformOptionsMethod": false,
      "useTransformResultMethod": false,
      "generateDtoTypes": true,
      "operationGenerationMode": "MultipleClientsFromOperationId",
      "markOptionalProperties": true,
      "generateCloneMethod": false,
      "typeStyle": "Class",
      "enumStyle": "Enum",
      "useLeafType": false,
      "classTypes": [],
      "extendedClasses": [],
      "extensionCode": null,
      "generateDefaultValues": true,
      "excludedTypeNames": [],
      "excludedParameterNames": [],
      "handleReferences": false,
      "generateConstructorInterface": true,
      "convertConstructorInterfaceData": false,
      "importRequiredTypes": true,
      "useGetBaseUrlMethod": false,
      "baseUrlTokenName": "API_BASE_URL",
      "queryNullValue": "",
      "useAbortSignal": false,
      "inlineNamedDictionaries": false,
      "inlineNamedAny": false,
      "includeHttpContext": false,
      "templateDirectory": null,
      "typeNameGeneratorType": null,
      "propertyNameGeneratorType": null,
      "enumNameGeneratorType": null,
      "serviceHost": null,
      "serviceSchemes": null,
      "output": "../BillComposer.UI/src/api/client.ts",
      "newLineBehavior": "Auto"
    }
  }
}
```

**Comment by WenningQiu** [comment]
I dug into NSwag source code and likely have found the answers to my questions:

1. The reason why NSwag insists on performing Debug build is because neither```Condifuration``` command line argument nor ```Configuration``` variable in nswag.json is set to ProjectMetadata.Configuration property.
![image](https://github.com/user-attachments/assets/255036a6-6369-4e34-8a97-14da06abd702)

2.  The possible source of file contention might come from the TryReadingUsingGetProperties() method that appears to be added to version 14.*. I repost the call stack below which shows that both TryReadingUsingGetProperties() and ReadUsingMsBuildTargets() must have been invoked when file contention happens.
![image](https://github.com/user-attachments/assets/11a57432-8154-465b-8e93-037adae39e57)

```
NSwag:
  dotnet "C:\Users\qiuw01\.nuget\packages\nswag.msbuild\14.1.0\buildTransitive\../tools/Net80/dotnet-nswag.dll" run nswag.json /variables:Configuration=Release
  NSwag command line tool for .NET Core Net80, toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))
  Visit http://NSwag.org for more information.
  NSwag bin directory: C:\Users\qiuw01\.nuget\packages\nswag.msbuild\14.1.0\tools\Net80

  Executing file 'nswag.json' with variables 'Configuration=Release'...
CSC : error CS2012: Cannot open 'C:\work\git\os_system\BillComposer\src\BillComposer.API\obj\Debug\net8.0-windows\BillComposer.API.dll' for writing -- 'The process cannot access the file 'C:\work\git\os_system\
BillComposer\src\BillComposer.API\obj\Debug\net8.0-windows\BillComposer.API.dll' because it is being used by another process.' [C:\work\git\os_system\BillComposer\src\BillComposer.API\BillComposer.API.csproj] [
C:\work\git\os_system\BillComposer\src\BillComposer.API.NSwag\BillComposer.API.NSwag.csproj]
  System.InvalidOperationException: Unable to retrieve project metadata. Ensure it's an MSBuild-based .NET Core project.If you're using custom BaseIntermediateOutputPath or MSBuildProjectExtensionsPath values,
  Use the --msbuildprojectextensionspath option.
     at NSwag.Commands.Generation.AspNetCore.ProjectMetadata.ReadUsingMsBuildTargets(List`1 args, String file, String buildExtensionsDir, IConsoleHost console) in /_/src/NSwag.Commands/Commands/Generation/AspNe
  tCore/ProjectMetadata.cs:line 160
     at NSwag.Commands.Generation.AspNetCore.ProjectMetadata.GetProjectMetadata(String file, String buildExtensionsDir, String framework, String configuration, String runtime, Boolean noBuild, String outputPath
  , IConsoleHost console) in /_/src/NSwag.Commands/Commands/Generation/AspNetCore/ProjectMetadata.cs:line 92
     at NSwag.Commands.Generation.AspNetCore.AspNetCoreToOpenApiCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in /_/src/NSwag.Commands/Commands/Generation/AspNetCore/AspNetCoreToOpenApiCom
  mand.cs:line 70
     at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in /_/src/NSwag.Commands/NSwagDocumentBase.cs:line 270
     at NSwag.Commands.NSwagDocument.ExecuteAsync() in /_/src/NSwag.Commands/NSwagDocument.cs:line 67
     at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in /_/src/NSwag.Commands/Commands/Document/ExecuteDocumentCommand.cs:line 76
     at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in /_/src/NSwag.Commands/Commands/Document/ExecuteDocumentCommand.cs:line 33
     at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
     at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
     at NSwag.Commands.NSwagCommandProcessor.ProcessAsync(String[] args) in /_/src/NSwag.Commands/NSwagCommandProcessor.cs:line 65
C:\work\git\os_system\BillComposer\src\BillComposer.API.NSwag\BillComposer.API.NSwag.csproj(69,5): error MSB3073: The command "dotnet "C:\Users\qiuw01\.nuget\packages\nswag.msbuild\14.1.0\buildTransitive\../too
ls/Net80/dotnet-nswag.dll" run nswag.json /variables:Configuration=Release" exited with code -1.
```

**Comment by vvdb-architecture** [comment]
But if `"nobuild": false` then you are effectively instructing NSwag to build your project while it is building your project..... Set it to true and read the v14 migration thread on top of the issues list to find out how v14 works. We use v14 in dozens of projects without seeing problems you have (but it took some effort to move to v14)

**Comment by WenningQiu** [comment]
Oh, I see; I misread your previous message.

I believe setting ```"nobuild": true```, which disables NSwag building projects, would prevent the file contention from happening.

**Comment by WenningQiu** [comment]
To report back to the community, below is what we have done to get around the bugs in version 14.*:

1. Turn off building in nswag.json file to get around file contention issue
```"noBuild": true,```
2. Update the build type setting (```configuration```) in nswag.json to get around the issue that command line variables are not passed along
```
  <UsingTask TaskName="UpdateNSwagJson" TaskFactory="CodeTaskFactory" AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.v4.0.dll">
    <ParameterGroup>
      <!-- Build type: Release or Debug -->
      <BuildType ParameterType="System.String" Required="true" />
    </ParameterGroup>
    <Task>
      <Code Type="Fragment" Language="cs">
        <![CDATA[
        string replacement = string.IsNullOrEmpty(this.BuildType) || this.BuildType == "null" ? "null" : "\"" + this.BuildType + "\"";
        string fileName = "nswag.json";
        string jsonText = System.IO.File.ReadAllText(fileName);
        string result = System.Text.RegularExpressions.Regex.Replace(jsonText, "\"configuration\":.+,", "\"configuration\": " + replacement + ",", System.Text.RegularExpressions.RegexOptions.IgnoreCase);
        System.IO.File.WriteAllText(fileName, result);
]]>
      </Code>
    </Task>
  </UsingTask>
  <Target Name="NSwag" AfterTargets="PostBuildEvent">
    <UpdateNSwagJson BuildType="$(Configuration)"/>
    <Exec Command="$(NSwagExe_Net80) run nswag.json /variables:Configuration=$(Configuration)" />
    <UpdateNSwagJson BuildType="null"/>
  </Target>
```

**Comment by mobius127** [comment]
I have the same issue here but is not intermitent

![image](https://github.com/user-attachments/assets/82edca6e-fcc4-49dc-b631-8ecb6c2e159d)

The migration from .net6 to .net8 is becoming annoying and this issue is delaying my work.

**Comment by WenningQiu** [comment]
@mobius127 The error message suggests that your project needs to be built before running NSwag. Do the project dependencies and MSBuild task ensure NSwag task is run after the project build is completed?
